Repository mozilla-mobile/firefox-android, pull requests merged in 2022-11, with the labels that each got.

#61 Bug 1797260 - Remove code that re-enables new supported addons #12998
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/migration/SupportedAddonsChecker.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/DefaultSupportedAddonCheckerTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/migration/SupportedAddonsWorkerTest.kt
Labels: 🛬 needs landing

#43 Bug 1798359 - Have TCP as the default cookie policy.
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#65 Check the correct file path when returning a list of AC files changed in build_config.py
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#68 Uplift 106 - Check the correct file path when returning a list of AC files changed in build_config.py
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#67 Uplift 107 - Check the correct file path when returning a list of AC files changed in build_config.py
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#69 Update the repo URL in gradle.properties
  android-components/gradle.properties
Labels: 🛬 needs landing

#38 Bug 1796482 - Allow for notifying consumers on unsuccessful Save to PDF requests
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/EngineStateReducer.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  docs/changelog.md
Labels: 🛬 needs landing

#59 Bug 1795903 - Introduce StorageMaintenanceWorker in A-C that runs periodically to prune places storage.
  android-components/components/browser/storage-sync/build.gradle
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/GlobalPlacesDependencyProvider.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageWorker.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/StorageExtensions.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/StorageMaintenanceWorker.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/GlobalPlacesDependencyProviderTest.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageWorkerTest.kt
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/Storage.kt
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/StorageMaintenanceRegistry.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
  android-components/components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt
  docs/changelog.md
Labels: 🛬 needs landing

#70 Bug 1794933 - Remove autocomplete when not applicable anymore
  android-components/components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
  android-components/components/ui/autocomplete/src/test/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditTextTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#82 Bug 1795105: Don't store thumbnails in BrowserState
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SystemReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/SystemActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  android-components/components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/DefaultTabViewHolderTest.kt
  android-components/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/ThumbnailsMiddleware.kt
  android-components/components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/ThumbnailsMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/Tab.kt
  docs/changelog.md
Labels: 🛬 needs landing

#97 Fix more links to point to new repo where applicable
  docs/components.md
Labels: 🕵️‍♀️ needs review

#101 Revert "Bug 1795105 - Don't store thumbnails in BrowserState"
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SystemReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/SystemActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  android-components/components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/DefaultTabViewHolderTest.kt
  android-components/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/ThumbnailsMiddleware.kt
  android-components/components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/ThumbnailsMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/Tab.kt
  docs/changelog.md
Labels: 🛬 needs landing

#102 Bug 1799224 - Move .gitignore to the root directory
  .gitignore
Labels: 🛬 needs landing

#113 Bug 1797997 - part 7: Enable test tasks on trusted github-pull-requests
  taskcluster/ci/test/kind.yml
Labels: 🛬 needs landing

#115 Bug 1797997 - part 8: Fix nit on event name
  taskcluster/ci/test/kind.yml
Labels: 🛬 needs landing

#119 Update GeckoView (Release) to 107.0.20221107173030
  android-components/buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#105 Bug 1795105 - Don't store thumbnails in BrowserState
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SystemReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/SystemActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  android-components/components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/DefaultTabViewHolderTest.kt
  android-components/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/ThumbnailsMiddleware.kt
  android-components/components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/ThumbnailsMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/Tab.kt
  docs/changelog.md
Labels: 🛬 needs landing

#80 Updates application-services to v95.0.0
  android-components/buildSrc/src/main/java/Dependencies.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorage.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorageTest.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesStorageTest.kt
  android-components/components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/AutofillCreditCardsAddressesStorage.kt
  android-components/components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/AutofillCrypto.kt
  android-components/components/service/sync-logins/README.md
  android-components/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/DefaultLoginValidationDelegate.kt
  android-components/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt
Labels: 🛬 needs landing

#121 Bug 1797244 - part 2: monorepo-migration: Update message expressions …
  monorepo-migration/data/message-expressions.txt
  monorepo-migration/data/repo-numbers.json
Labels: 🛬 needs landing

#95 Bug 1799056 - Update onSaveToPdfError to onSaveToPdfException
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🛬 needs landing

#122 Bug 1798878 - Let `sync-focus.sh` port the last 2 release branches too
  monorepo-migration/sync-focus.sh
Labels: 🛬 needs landing

#125 Bug 1796658 - fix notifications on failure of geckoview nightly bumps
  taskcluster/ac_taskgraph/transforms/complete.py
  taskcluster/ci/complete/kind.yml
Labels: 🛬 needs landing

#118 No issue: A-C change Firebase Test Lab device to Pixel2 (ARM)
  android-components/automation/taskcluster/androidTest/flank-arm.yml
Labels: 🛬 needs landing

#132 Bug 1776677 - Ship v108.0.0 of the WebCompat System Addon.
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1799994-www.vivobarefoot.com-product-filters-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1800000-www.honda.co.uk-choose-dealer-button-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1800127-www.burgerking.es-webkit-fill-available-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1800143-www.nintendo.co.jp-zoomed-in-image-scrolling-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1784309-bet365.com-math-pow.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1795490-www.china-airlines.com-undisable-date-fields-on-mobile.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1799968-www.samsung.com-appVersion-linux-fix.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1799980-healow.com-infinite-loop-fix.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1800118-taszi.edupage.org-timetable-window.print-fix.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1800131-www.almosafer.com-undisable-date-fields.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/ua_helpers.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#137 Update leakcanary to version 2.10
  android-components/buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#127 No issue: Add matrix parsing markdown to UI checks for A-C
  android-components/automation/taskcluster/androidTest/flank-arm.yml
  android-components/automation/taskcluster/androidTest/parse-ui-test.py
  android-components/automation/taskcluster/androidTest/ui-test.sh
  taskcluster/docker/base/Dockerfile
Labels: 🛬 needs landing

#151 Start 109.0.0 development cycle
  docs/changelog.md
  version.txt
Labels: 🛬 needs landing

#153 Bug 1789398 - ensure task["metadata"]["owner"] is not empty on github…
  .taskcluster.yml
Labels: 🛬 needs landing

#152 Bug 1791748 - Fix trigger-nightly task after repository move
  taskcluster/ac_taskgraph/target_tasks.py
  taskcluster/ci/trigger-nightly/kind.yml
Labels: 🛬 needs landing

#128 Bug 1799964 - Migrate firefox-android from AWS to GCP
  .taskcluster.yml
  taskcluster/ci/config.yml
Labels: 🛬 needs landing (squash)

#156 Improve site permissions APIs
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorage.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegate.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorageTest.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/MockWebNotification.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/SitePermissionsStorage.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotification.kt
  android-components/components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/OnDeviceSitePermissionsStorageTest.kt
  android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorage.kt
  android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorageTest.kt
  android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  android-components/components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/WebNotificationFeature.kt
  android-components/components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/NativeNotificationBridgeTest.kt
  android-components/components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/WebNotificationFeatureTest.kt
Labels: 🛬 needs landing

#154 RELENG-207 - Drop obsolete code looking for github-release graphs
  taskcluster/ac_taskgraph/target_tasks.py
Labels: 🛬 needs landing

#166 Bug 1796353 - Cancel media notification explicitly on service shutdown.
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
Labels: 🛬 needs landing

#148 Bug 1800542 - Refactor Dependencies into a plugin using composite build
  .github/workflows/ac-create-release.yml
  .github/workflows/ac-update-geckoview.yml
  .mergify.yml
  android-components/build.gradle
  android-components/plugins/dependencies/build.gradle
  android-components/plugins/dependencies/settings.gradle
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  android-components/plugins/dependencies/src/main/java/Gecko.kt
  android-components/settings.gradle
  android-components/tools/list_compatible_dependency_versions.py
  docs/changelog.md
  taskcluster/ci/toolchain/android.yml
  taskcluster/ci/trigger-nightly/kind.yml
Labels: 🛬 needs landing

#169 Bug 1801022 - Update AndroidX testing libraries to the latest releases
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing

#170 CI for Bug 1799230 - Use Non-Transitive R Classes
  android-components/components/browser/errorpages/src/main/java/mozilla/components/browser/errorpages/ErrorPages.kt
  android-components/components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  android-components/components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItem.kt
  android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/BrowserMenuHighlightTest.kt
  android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilderTest.kt
  android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableItemTest.kt
  android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuHighlightableSwitchTest.kt
  android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/item/BrowserMenuItemToolbarTest.kt
  android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/item/ParentBrowserMenuItemTest.kt
  android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItemTest.kt
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/display/DisplayToolbarTest.kt
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestion.kt
  android-components/components/compose/browser-toolbar/build.gradle
  android-components/components/compose/browser-toolbar/src/main/java/mozilla/components/compose/browser/toolbar/BrowserEditToolbar.kt
  android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopupContent.kt
  android-components/components/compose/tabstray/src/main/java/mozilla/components/compose/tabstray/Tab.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/menu/WebExtensionActionMenuCandidate.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/menu/WebExtensionNestedMenuCandidate.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsPermissionsAdapterTest.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/SimpleRedirectDialogFragmentTest.kt
  android-components/components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/fill/AuthFillResponseBuilder.kt
  android-components/components/feature/awesomebar/build.gradle
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProvider.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProviderTest.kt
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragmentTest.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/ui/DownloadAppChooserDialogTest.kt
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/middleware/RecordingDevicesMiddleware.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/AlertDialogFragmentTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/AuthenticationDialogFragmentTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/ConfirmDialogFragmentTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/MultiButtonDialogFragmentTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/SaveLoginDialogFragmentTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/dialog/TextPromptDialogFragmentTest.kt
  android-components/components/feature/readerview/src/test/java/mozilla/ext/context.kt
  android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragmentTest.kt
  android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
  android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/toolbar/TabCounterToolbarButtonTest.kt
  android-components/components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ContainerToolbarAction.kt
  android-components/components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/WebExtensionToolbarAction.kt
  android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/WebExtensionToolbarTest.kt
  android-components/components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
  android-components/components/ui/autocomplete/src/test/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditTextTest.kt
  android-components/components/ui/tabcounter/build.gradle
  android-components/components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounterMenu.kt
  android-components/components/ui/widgets/src/test/java/mozilla/components/ui/widgets/WidgetSiteItemViewTest.kt
  android-components/gradle.properties
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/TabsTrayFragment.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonDetailsActivity.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/InstalledAddonDetailsActivity.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/integration/ReaderViewIntegration.kt
  android-components/samples/toolbar/src/main/java/org/mozilla/samples/toolbar/ToolbarActivity.kt
Labels: 🛬 needs landing

#176 Bug 1800542 - part 4: Rebuild every component when the dependencies p…
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#177 Bug 1800542 - Bug fix for part 4
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#180 Bug 1800542 - part 5: Bump relbot from 4.0.0 to 4.0.1
  .github/workflows/ac-create-release.yml
  .github/workflows/ac-update-geckoview.yml
Labels: 🛬 needs landing

#184 Bug 1800542 - part 6: Support multiple locations of Gecko.kt dependin…
  taskcluster/ac_taskgraph/target_tasks.py
Labels: 🛬 needs landing

#187 Update to GeckoView Nightly 109.0.20221118094451 on main
  android-components/plugins/dependencies/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#188 Bug 1800542 - part 7: Bump relbot from 4.0.1 to 4.0.2
  .github/workflows/ac-create-release.yml
  .github/workflows/ac-update-geckoview.yml
Labels: 🛬 needs landing

#194 Bug 1800542 - part 8: Fix mergify autoland of Gecko.kt updates in release branches
  .mergify.yml
Labels: 🛬 needs landing

#157 Bug 1800700 - Add default search suggest header
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  docs/changelog.md
Labels: 🛬 needs landing

#168 Don't try and record history for URLs with an invalid scheme.
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
Labels: 🛬 needs landing

#179 Removed code to report Sentry errors for Rust `log::error` calls
  android-components/components/support/rustlog/src/main/java/mozilla/components/support/rustlog/RustLog.kt
  android-components/components/support/rustlog/src/test/java/mozilla/components/support/rustlog/RustLogTest.kt
Labels: 🛬 needs landing

#185 Bug 1801349 - Sentry breadcrumb fixes
  android-components/components/lib/crash-sentry-legacy/build.gradle
  android-components/components/lib/crash-sentry-legacy/src/test/java/mozilla/components/lib/crash/sentry/legacy/SentryServiceTest.kt
  android-components/components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt
  android-components/components/lib/crash-sentry/src/test/java/mozilla/components/lib/crash/sentry/SentryServiceTest.kt
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#76 Bug 1796379 - Upstream String.toShortUrl to support-ktx
  android-components/components/lib/publicsuffixlist/build.gradle
  android-components/components/support/ktx/build.gradle
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#202 Bug 1801611: Fix CrashReporterTest
  android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
Labels: 🛬 needs landing

#199 Upgrade Application Services to v96.0.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#205 Bug 1800700 - Add default search suggest header
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  docs/changelog.md
Labels: 🛬 needs landing

#165 Add AC version of NimbusBuilder to construct AC version of Nimbus object
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/NimbusBuilder.kt
Labels: 🛬 needs landing

#164 Bug 1800885 - Increased browser menu Add/Edit checkbox touch target
  android-components/components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_text_checkbox_button.xml
  docs/changelog.md
Labels: 🛬 needs landing

#206 Revert "Bug 1800700 - Add default search suggest header"
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt
  docs/changelog.md
Labels: 🛬 needs landing

#210 Bug 1788606 - Decision task: let docker-worker cache the gradle cache
  .taskcluster.yml
  taskcluster/ac_taskgraph/loader/build_config.py
Labels: 🛬 needs landing

#209 Bug 1801834: Fix `Breadcrumbs stores only max number of breadcrumbs` …
  android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
Labels: 🛬 needs landing

#212 Bug 1801648 - Fix autoplay settings are not getting updated in private mode
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorage.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorageTest.kt
  android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorage.kt
  android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorageTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#191 Update Sentry to version 6.8.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing

#182 Bug 1801285 - Add filter by host/domain to frecent top sites
  android-components/components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt
  android-components/components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/ext/TopSite.kt
  android-components/components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt
  android-components/components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/ext/TopSiteTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#217 Add basic notification features for sample app
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing

#227 Bug 1717806 - Fix a match-pattern for the Advertising.com shim to un-…
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#233 Bug 1803117 - disable by default cookieBannerHandlingModePrivateBrowsing
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
  android-components/components/lib/crash/docs/metrics.md
  android-components/components/support/sync-telemetry/docs/metrics.md
Labels: 🛬 needs landing
