Repository mozilla-mobile/firefox-android, pull requests merged in 2022-12, with the labels that each got.

#245 Bug 1803632 - Removes remaining Fennec to Fenix migration functions
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorage.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorageTest.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/LoginsStorage.kt
  android-components/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#260 Update GeckoView (Release) to 108.0.20221205155917
  android-components/buildSrc/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#229 Bug 1799049 - Change format of SERP_SHOWN_WITH_ADDS fact
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/ads/AdsTelemetry.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/telemetry/ads/AdsTelemetryTest.kt
Labels: 🛬 needs landing

#262 Bug 1796301 - Add paddingEnd in OriginView for RTL config
  android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
  android-components/components/browser/toolbar/src/main/res/values-ldrtl/dimens.xml
  android-components/components/browser/toolbar/src/main/res/values/dimens.xml
Labels: 🛬 needs landing (squash)

#268 Bug 1796658 (followup): update notification recipients
  taskcluster/ci/complete/kind.yml
Labels: 🛬 needs landing

#276 Bug - 1804690 Expose allowEmulatorLoopback
  android-components/components/support/rusthttp/src/main/java/mozilla/components/support/rusthttp/RustHttpConfig.kt
Labels: 🛬 needs landing

#286 Bug 1776678 - Ship 109.0.0 of feature-webcompat
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1653075-livescience.com-scrollbar-width.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1751022-chotot.com-image-width-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784141-aveeno.com-acuvue.com-unsupported.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784141-aveeno.com-unsupported.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1788685-microsoftedgetips.microsoft.com-gallery-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1724764-amextravel.com-window-print.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1724764-window-print.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1772949-youtube-webshare-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1787267-nintendo-window-OnetrustActiveGroups.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1800118-taszi.edupage.org-timetable-window.print-fix.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1803976-www.youtube.com-performance-now-precision.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics-and-tag-manager.js
Labels: 🛬 needs landing

#296 Start 110 development cycle
  android-components/plugins/dependencies/src/main/java/Gecko.kt
  docs/changelog.md
  version.txt
Labels: 🛬 needs landing

#124 Bug 1799679 - Clear search terms on url load
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineSessionTest.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/SearchUseCases.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/SearchUseCasesTest.kt
  android-components/components/feature/serviceworker/src/test/java/mozilla/components/feature/serviceworker/ServiceWorkerSupportTest.kt
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
Labels: 🛬 needs landing

#273 Bug 1804594 - Differentiate search engines between "general" and "topic specific" when they are loaded
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/search/SearchEngine.kt
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/ext/SearchEngine.kt
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchEngineReader.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/ext/SearchEngineKtTest.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/storage/SearchEngineReaderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#231 Bug 1802579 - Add extra granular media permissions for devices with Android 13 and above.
  android-components/components/feature/prompts/src/main/AndroidManifest.xml
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/MimeType.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FilePickerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#278 Bug 1804716 - Consume AC via gradle build with relative path in Focus
  focus-android/app/build.gradle
  focus-android/build.gradle
  focus-android/gradle.properties
  focus-android/service-telemetry/build.gradle
  focus-android/settings.gradle
Labels: 🛬 needs landing

#282 Bug 1799666 - Import focus-android configuration in .mergify.yml
  .mergify.yml
  focus-android/.mergify.yml
Labels: do not land

#284 Bug 1803141 - part 8: Build focus only when it or one of its dependen…
  taskcluster/android_taskgraph/gradle.py
  taskcluster/android_taskgraph/transforms/build_apk.py
  taskcluster/android_taskgraph/transforms/gradle_optimization.py
  taskcluster/ci/build-apk/kind.yml
Labels: do not land

#317 Set version.txt to 109.0b1
  version.txt
Labels: 🛬 needs landing

#323 No issue: Remove redundant LICENSE file in focus-android folder
  focus-android/LICENSE
Labels: 🛬 needs landing

#328 Bug 1805629: fix chain of trust verification failure on pull requests
  .taskcluster.yml
Labels: 🛬 needs landing

#320 Bug 1804598 - Remove the AC line in the About Fragment
  focus-android/app/src/main/java/org/mozilla/focus/fragment/about/AboutFragment.kt
  focus-android/app/src/main/res/values/static_strings.xml
Labels: 🛬 needs landing

#351 Bug 1805946 - Ensure Glean and Nimbus gradle plugins are consuming the latest version
  android-components/plugins/dependencies/settings.gradle
  android-components/plugins/publicsuffixlist/settings.gradle
  focus-android/build.gradle
  focus-android/buildSrc/src/main/java/Config.kt
Labels: 🛬 needs landing

#234 Bug 1800700 - Add default search suggest header
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/SuggestionFetcher.kt
  android-components/components/compose/awesomebar/src/test/java/mozilla/components/compose/browser/awesomebar/internal/SuggestionFetcherTest.kt
  android-components/components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
  docs/changelog.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#350 Bug 1801349 - Synchronize access to the crash reporter breadcrumbs list
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
  android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbTest.kt
  android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#346 Bug 1804527 - Replace deprecated AC mailing list in lib crash
  android-components/components/lib/crash/metrics.yaml
Labels: 🛬 needs landing

#265 Bug 1804260 - Add method to specify the cursor placement when switching to URL editing mode
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  android-components/components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#367 Bug 1800542 - part 10: Bump relbot from 5.0.1 to 5.0.2
  .github/workflows/ac-create-release.yml
  .github/workflows/ac-update-geckoview.yml
Labels: 🛬 needs landing

#303 Bug 1805256 - Adding legacy telemetry id to Glean pings
  focus-android/app/metrics.yaml
Labels: 🛬 needs landing

#372 Bug 1806170 - Align detekt config between Focus and Android Components
  focus-android/build.gradle
  focus-android/quality/detekt-baseline.xml
  focus-android/quality/detekt.yml
Labels: 🛬 needs landing

#385 Bug 1797245 - Bump the versions for the Sync Strings GitHub actions
  .github/workflows/ac-sync-strings.yml
  .github/workflows/focus-sync-strings.yml
Labels: 🛬 needs landing (squash)

#374 Bug 1805383 - Change treeherder platform for focus build/signing
  taskcluster/ci/build-apk/kind.yml
  taskcluster/ci/signing-apk/kind.yml
Labels: 🛬 needs landing

#343 Bug 1796319 - Add functionality in SelectOrAddUsecase to ignore the fragment identifier part of the url
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/selector/Selectors.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/selector/SelectorsKtTest.kt
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash)

#335 Bug 1802610: Change Focus locale UI test to select a language above the fold
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SettingsGeneralTest.kt
Labels: 🛬 needs landing

#392 Bug 1805184 - Enable or disable Glean collection and upload immediately.
  focus-android/app/src/main/java/org/mozilla/focus/widget/TelemetrySwitchPreference.kt
Labels: 🛬 needs landing

#396 Bug 1804844 - Downgrade ZXing to version 3.3.3.
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing

#400 Bug 1806444 - Do not run tasks for mergify branches on git-push
  .taskcluster.yml
Labels: 🛬 needs landing

#395 Bug 1806435 - Add CookieBannerHandlingMode.DETECT_ONLY
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🛬 needs landing

#370 Bug 1805832 - Add additional checked casts when converting Array<Parcelable>
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ext/Bundle.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/BundleTest.kt
Labels: 🛬 needs landing

#390 Bug 1806411: Remove image link from message when sharing an image
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/share/ShareDownloadFeature.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/share/ShareDownloadFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#415 No issue - Bump fenix-beta-version action to 4.2.1
  .github/workflows/focus-sync-strings.yml
Labels: 🛬 needs landing

#321 Bug 1805553 - Include git revision in About Fragment
  focus-android/app/build.gradle
  focus-android/app/src/main/java/org/mozilla/focus/fragment/about/AboutFragment.kt
  focus-android/buildSrc/src/main/java/Config.kt
Labels: 🛬 needs landing

#422 Bug 1794873: Intermittent UI test failure in loadWebsitesInMultipleTabsTest
  android-components/samples/browser/src/androidTest/java/org/mozilla/samples/browser/SmokeTests.kt
Labels: 🛬 needs landing
