Repository mozilla-mobile/firefox-android, pull requests merged in 2023-11, with the labels that each got.

#4300 Bug 1862246 - Rename mozac_ic_add_to_home_screen_24 to mozac_ic_add_to_homescreen_24
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_add_to_homescreen_24.xml
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  fenix/app/src/main/res/layout/fragment_pwa_onboarding.xml
  focus-android/app/src/main/java/org/mozilla/focus/menu/browser/CustomTabMenu.kt
  focus-android/app/src/main/java/org/mozilla/focus/menu/browser/DefaultBrowserMenu.kt
Labels: 🛬 needs landing, approved

#4289 Bug 1859887 - Refactor ic_private_mode_circle_fill_48 to ui-icons
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_private_mode_circle_fill_48.xml
  android-components/components/ui/icons/src/main/res/values/attrs.xml
  fenix/app/src/main/res/layout/fragment_home.xml
  fenix/app/src/main/res/values/attrs.xml
  fenix/app/src/main/res/values/styles.xml
Labels: 🛬 needs landing, approved

#4301 Bug 1862231 - Translations UI Fix the translation icon colour if the theme is light.
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: 🛬 needs landing, approved

#4283 Bug 1861989 - Update Robolectric to version 4.11.1
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/temporary/CopyDownloadFeatureTest.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/temporary/ShareDownloadFeatureTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/MimeTypeTest.kt
  android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/net/UriTest.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/src/test/java/org/mozilla/fenix/downloads/DynamicDownloadDialogTest.kt
Labels: 🛬 needs landing, approved

#4243 Bug 1861647 - Fenix: Add new Addons high priority tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing, approved

#3859 Bug 1849073 - Part 7: Remove pill wrapper in search dialog
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarInteractor.kt
  fenix/app/src/main/res/color/toggle_text_color.xml
  fenix/app/src/main/res/drawable/search_pill_background.xml
  fenix/app/src/main/res/drawable/search_pill_background_unselected.xml
  fenix/app/src/main/res/drawable/search_pill_drawable_button_background.xml
  fenix/app/src/main/res/layout/fragment_search_dialog.xml
  fenix/app/src/main/res/values/dimens.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/values/styles.xml
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogInteractorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
Labels: 🛬 needs landing, approved

#4319 Bug 1858795 - Update moz:RemovedIn for deprecated cookie banner strings.
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4322 Bump Application Services Release to 120.0.1
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
Labels: 🛬 needs landing, approved

#4326 Bug 1862038 - Update release_checklist.md to swap two steps
  docs/contribute/release_checklist.md
Labels: 🛬 needs landing, approved

#4262 Bug 1860919 - Send Glean pings for Wikipedia Firefox Suggestion impressions and clicks.
  android-components/components/feature/fxsuggest/README.md
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/facts/FxSuggestFacts.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestFactsMiddlewareTest.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestFactsTest.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
Labels: 🛬 needs landing, approved

#4314 Bug 1862074 - Further restrict download broadcast intent to own package.
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
Labels: 🛬 needs landing, approved

#4317 Bug 1862399 - Keep review checker card expanded states in ReviewQualityCheckState
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/NoAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckCards.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckSettingsCard.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityInfoCard.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckBottomSheetStateFeatureTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4325 Bug 1862225 - Update for tesco.com override
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/ua_helpers.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing, approved

#4258 New high priority download UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing, approved

#4246 Bug 1861173 - Change timing of the Review Checker onboarding CFR
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: 🛬 needs landing, approved

#4332 Bug 1567912 - Switch pushed Fenix Beta/Release to AAB builds
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/push-bundle/kind.yml
Labels: 🛬 needs landing (squash), approved

#4324 Bug 1861732 - Split-out "terms of use" and "privacy policy" text links
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4227 Bug 1845835 - Expose shopping ad attribution events in AC
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#4309 Bug 1862350 - Remove old History delete APIs
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  android-components/components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
Labels: 🛬 needs landing, approved

#4162 Bug 1857173 - Modified page action button to adhere a11y rules
  android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
Labels: 🛬 needs landing, approved

#4342 Bug 1862744 - Update JaCoCo to version 0.8.11
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4334 Bug 1862656 - Update AndroidX Fragment to version 1.6.2
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4214 Bug 1861234 — Add SharedPreferences to NimbusBuilder
  fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  focus-android/app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
Labels: 🛬 needs landing, approved, urgent

#4306 Bug 1862996 - Search engine update
  android-components/components/feature/search/src/main/assets/search/list.json
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-au.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-ca.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-co-uk.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-de.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-es.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-fr.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-in.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-it.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-nl.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-se.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazondotcom.xml
  android-components/components/feature/search/src/main/assets/searchplugins/danawa-kr.xml
  android-components/components/feature/search/src/main/assets/searchplugins/elebila.xml
  android-components/components/feature/search/src/main/assets/searchplugins/leit-is.xml
  android-components/components/feature/search/src/main/assets/searchplugins/pledarigrond.xml
  android-components/components/feature/search/src/main/assets/searchplugins/rediff.xml
  android-components/components/feature/search/src/main/assets/searchplugins/reta-vortaro.xml
  android-components/components/feature/search/src/main/assets/searchplugins/skroutz.xml
  android-components/components/feature/search/src/main/assets/searchplugins/slovnik-sk.xml
  android-components/components/feature/search/src/main/assets/searchplugins/sztaki-en-hu.xml
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchEngineReader.kt
Labels: 🛬 needs landing, approved

#4231 Bug 1844523 - Translate and Restore to Original Engine Support
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/EngineDelegateMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/SessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationOperation.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationOptions.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/address/AddressPickerTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardPickerTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FilePickerTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/login/LoginPickerTest.kt
  android-components/components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved, urgent

#4358 Bug 1862927 — Remove duplicate nimbus enrollment/exposure events
  android-components/components/service/nimbus/docs/metrics.md
  android-components/components/service/nimbus/metrics.yaml
Labels: 🛬 needs landing, approved

#4152 Bug 1858882 - Update "Learn More" link in private browsing description
  fenix/app/src/main/java/org/mozilla/fenix/home/privatebrowsing/controller/PrivateBrowsingController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/privatebrowsing/DefaultPrivateBrowsingControllerTest.kt
Labels: 🛬 needs landing, approved

#4360 Bug 1861732 - Remove straight quotes from shopping onboarding caption
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4320 Bug 1862926 - New high priority history UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddToHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
Labels: 🛬 needs landing, approved

#4350 Bug 1862402 - Mark AnalysisPresent as Immutable for compose compiler
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
Labels: 🛬 needs landing, approved

#4352 Bug 1861173 - Correctly increment shopping CFR counter
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: 🛬 needs landing, approved

#4357 Bug 1863278 - Refactor navigation and storage deletion in downloads UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadFileTypesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PDFViewerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing, approved

#4354 Bug 1862775 - Send telemetry on "Powered by Fakespot by Mozilla" tap
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#4343 Bug 1862737 - Add telemetry for the full install referrer response
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/InstallReferrerMetricsService.kt
Labels: 🛬 needs landing, approved

#4380 Bug 1861732 - Clean up shopping onboarding caption strings
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4348 Bug 1862425 - Allow to control QPS prefs using nimbus.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: 🛬 needs landing, approved

#4381 Bug 1862403 - Remove unneeded states from RecommendedProductState
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductRecommendationMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductRecommendationMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4392 Bug 1863504 - Track Shopping CFR shown to user when it is displayed
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/interactor/BrowserToolbarInteractor.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: 🛬 needs landing, approved

#4063 Bug 1807545 - Add new "Open in regular tab" feature.
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  fenix/app/src/main/res/drawable/ic_open_in_regular_tab.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4401 Bug 1863603 - Add handling of Meta attribution in percent format
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/InstallReferrerMetricsService.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/metrics/InstallReferrerMetricsServiceTest.kt
Labels: 🛬 needs landing, approved

#4389 Bug 1856336 - Integrate rc impression and click APIs in network middleware
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4395 Bug 1863559 - Updated SafeUrl.stripUnsafeUrlSchemes to handle null unsafeText
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/SafeUrl.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/SafeUrlTest.kt
Labels: 🛬 needs landing, approved

#4166 Bug 1821701 - Added SVG decoding for favicons.
  android-components/components/browser/icons/build.gradle
  android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/SvgIconDecoder.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4413 Bug 1863744 - Update Gradle to version 8.4
  android-components/gradle/wrapper/gradle-wrapper.jar
  android-components/gradle/wrapper/gradle-wrapper.properties
  android-components/gradlew
  android-components/plugins/config/build.gradle
  android-components/plugins/dependencies/build.gradle
  android-components/plugins/github/build.gradle
  android-components/plugins/publicsuffixlist/build.gradle
  fenix/gradle/wrapper/gradle-wrapper.jar
  fenix/gradle/wrapper/gradle-wrapper.properties
  fenix/gradlew
  fenix/plugins/apksize/build.gradle
  fenix/plugins/fenixdependencies/build.gradle
  focus-android/gradle/wrapper/gradle-wrapper.jar
  focus-android/gradle/wrapper/gradle-wrapper.properties
  focus-android/gradlew
  focus-android/plugins/focusdependencies/build.gradle
Labels: 🛬 needs landing, approved

#4394 Bug 1823316 - Use 'Snackbar' themed Dialog to notify on making app full-screen
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/FullScreenNotificationDialog.kt
  android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/res/layout/full_screen_notification_dialog.xml
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  focus-android/app/src/main/res/layout/dialog_full_screen_notification.xml
  focus-android/app/src/test/java/org/mozilla/focus/browser/integration/FullScreenIntegrationTest.kt
Labels: 🛬 needs landing, approved

#4397 Bug 1863564 - Add missing param descs & order to match definition for CustomTabsToolbarFeature class
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
Labels: 🛬 needs landing, approved

#4390 Bug 1863515 - Refactor navigation and add logs for address autofill UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing, approved

#3938 Bug 1857093 - Update Sentry to version 6.33.1
  android-components/components/lib/crash-sentry/build.gradle
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/build.gradle
  focus-android/app/build.gradle
Labels: 🛬 needs landing, approved

#4398 Bug 1859391 - Update cookie banner settings page to only support private mode.
  fenix/app/metrics.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuCookieBannerReductionRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/CookieBannersFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/CookieBannersSwitchPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/LearnMoreSwitchPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  fenix/app/src/main/res/layout/preference_switch_learn_more.xml
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/cookie_banner_preferences.xml
  fenix/app/src/main/res/xml/preferences.xml
Labels: 🛬 needs landing, approved

#4414 Bug 1859392 - Update the cookie banner handling section in the quick setting to only show in private mode.
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/ProtectionsView.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsView.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannersStorageExt.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/layout/component_cookie_banner_details_panel.xml
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultConnectionDetailsControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/ProtectionsViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/DefaultCookieBannerDetailsControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelInteractorTest.kt
Labels: 🛬 needs landing, approved

#4427 Bug 1863922 - Move highlights expanded state to ReviewQualityCheckState
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4428 Bug 1859585 - WebExtensionSupport should update installExtensions entries on AddonManagerDelegate.onReady calls
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionDelegate.kt
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
Labels: 🛬 needs landing, approved

#4432 Bug 1854383 - Increase frequency for StorageMaintenanceWorker
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/StorageMaintenanceWorker.kt
Labels: 🛬 needs landing, approved

#4460 Bug 1742344 - Unbreak imgur.io on Android in PBM
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/private-browsing-web-api-fixes.js
Labels: 🛬 needs landing, approved

#4462 Bug 1861417 - Show sponsored and Wikipedia suggestions last in the awesomebar.
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
Labels: 🛬 needs landing, approved

#4409 Bug 1863700 - Add more logs to functions related to download tests and other refactoring work
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadFileTypesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing, approved

#4458 Bug 1864403 - Enable product recommendations for developer builds
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#4442 Bug 1857875 - Fix SettingsAddonsTest.noCrashWithAddonInstalledTest scrolling issue in add-ons list
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
Labels: 🛬 needs landing, approved

#4425 Bug 1864399 - Use custom assertions in UI test robots
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/AddToHomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/PwaRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionExceptionsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuExperimentsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLanguageRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuPrivateBrowsingRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsCommonRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SitePermissionsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SiteSecurityRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncSignInRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SystemSettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing, approved

#4383 Bug 1853416 - [ci] Add treescript action scope to version bump task
  taskcluster/android_taskgraph/worker_types.py
Labels: 🛬 needs landing, approved

#4079 Bug 1821703 - Fix Compose Top Site Sponsored Sites 'flashing' appearance
  android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/Favicon.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
Labels: 🛬 needs landing, approved

#4440 Bug 1859393 - Add CFR when the first cookie banner gets cleared.
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
Labels: 🛬 needs landing, approved

#4471 Bug 1864549 - Fix for IllegalStateException in full screen notification dialog
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/FullScreenNotificationDialog.kt
Labels: 🛬 needs landing, approved

#2538 Bug 1839228 - RemoteTabsStorage now catches the public error rather t…
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/RemoteTabsStorageTest.kt
Labels: 🛬 needs landing, approved

#4436 Bug 1863754 - Disable sponsored and non-sponsored suggestions when Firefox Suggest is disabled.
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
Labels: 🛬 needs landing, approved

#4435 Bug 1815002 - Enable Tabs Tray to Compose rewrite in Beta
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: 🛬 needs landing, approved

#4457 Bug 1859671 - Remember review checker card states for the session
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingState.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingStateReducer.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferencesMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckVendorsService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/appstate/ShoppingActionTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckBottomSheetStateFeatureTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckVendorsService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4483 Bug 1842154 - Disable failing notificationCanBeDismissedIfDownloadIsInterruptedTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing

#4359 Bug 1863017: Fix UX issues on the FedCM Policy Prompt.
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/PrivacyPolicyDialogFragment.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/SelectProviderDialog.kt
  android-components/components/feature/prompts/src/main/res/layout/mozac_feature_prompt_simple_text.xml
  android-components/components/feature/prompts/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4379 Bug 1862776 - Add Fakespot stale analysis shown telemetry probe
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#4477 Bug 1859817 - Align social trackers in Custom mode with desktop.
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactory.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/TrackingProtectionPolicyFactoryTest.kt
Labels: 🛬 needs landing, approved

#3646 Bug 1818321 - Update missing default engines
  android-components/components/feature/search/src/main/assets/search/list.json
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#1318 Bug 1807104 - Used unique identifier in ShortcutInfo instead of URL to make every shortcut unique
  android-components/components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt
Labels: 🛬 needs landing, approved

#3598 Bug 1837082 - Show SITE_NOT_SUPPORTED when hasException
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannersStorageExt.kt
Labels: 🛬 needs landing, approved

#4478 Bug 1864753 - Remove debug APK size alerts
  fenix/plugins/apksize/src/main/java/ApkSizePlugin.kt
Labels: 🛬 needs landing, approved

#4286 Bug 1861058 - Translations UI Make navigating from one bottom sheet to another more smooth.
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationOptionsDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationOptionsDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
Labels: 🛬 needs landing, approved

#4484 Bug 1842154 - Fix notificationCanBeDismissedIfDownloadIsInterruptedTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing, approved

#4487 Bug 1864859 - Make cookie banner handling follow the same defaults as desktop.
  fenix/app/nimbus.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/cookiebannerhandling/CustomCBHSwitchPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/xml/preferences.xml
Labels: 🛬 needs landing, approved

#4467 Bug 1858528 - Add rakuten and yahoo-jp-auctions search engines
  android-components/components/feature/search/src/main/assets/search/list.json
  android-components/components/feature/search/src/main/assets/searchplugins/rakuten.xml
  android-components/components/feature/search/src/main/assets/searchplugins/yahoo-jp-auctions.xml
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#4396 Bug 1834820 - Update RemoteSettings downloader class
  android-components/components/support/remotesettings/src/main/java/mozilla/components/support/remotesettings/RemoteSettingsClient.kt
  android-components/components/support/remotesettings/src/test/java/mozilla/components/support/remotesettings/RemoteSettingsClientTest.kt
Labels: 🛬 needs landing, approved

#4150 Bug 1859910 - Update AndroidX Benchmark to version 1.2.1
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4502 Bug 1865067 - Send surface_reanalyze_clicked only when button tapped
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
Labels: 🛬 needs landing, approved, urgent

#4491 Bug 1864926 - Update AndroidX Browser to version 1.7.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4505 Bug 1838842 - Ship v121.0.0 of the WebCompat System Addon
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1830752-afisha.ru-slider-pointer-events.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1841991-wilton.com-flexbox-painting-order.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1848711-vio.com-page-height.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1731825-office365-email-handling-prompt-autohide.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1795490-www.china-airlines.com-undisable-date-fields-on-mobile.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1864564-esri-transfrom-names-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing, approved

#4197 Bug 1860618 - Expose not_enough_reviews fields in AC Shopping
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/shopping/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4488 Bug 1864895 - Update CBH CFR title to not use Firefox hardcoded string
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4512 Bug 1865280 - Switch to high capacity AVD for legacy and robo UI tests
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🛬 needs landing, approved

#4476 Bug 1859981 - Make 'content:' URI an invalid web URL
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/WebURLFinder.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/WebURLFinderTest.kt
Labels: 🛬 needs landing, approved

#4501 Bug 1865072 - Remove redundant assertions
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/AddToHomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/PwaRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/RecentlyClosedTabsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDataCollectionRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionExceptionsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuExperimentsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLanguageRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuOpenLinksInAppsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuPrivateBrowsingRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsCommonRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsExceptionsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SitePermissionsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SiteSecurityRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncSignInRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SystemSettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing, approved

#4513 Bug 1865317 - Add correct API for redfin AVD
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#4498 Bug 1865043 - Switch browsertime tests to use arm64 builds.
  taskcluster/ci/browsertime/kind.yml
Labels: 🛬 needs landing (squash), approved

#4514 Bug 1865226 - Ignore review checker store flaky tests
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4400 Bug 1863606 - Add smoke test generation to experiment integration test suite
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/generate_smoke_tests.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/gradlewbuild.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/variables.yaml
Labels: 🛬 needs landing, approved

#4532 Bug 1865648 - Start the 122 development cycle
  android-components/components/feature/addons/src/main/res/values/strings.xml
  android-components/components/feature/prompts/src/main/res/values/strings.xml
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4101 Bug 1857558 - [a11y] Dictate Correct CFR Popup Title
  android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopupFullscreenLayout.kt
Labels: 🛬 needs landing, approved

#3980 Bug 1856470 - Add EMAIL filter to TrackingCategory for tracker protection
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
Labels: 🛬 needs landing, approved

#4534 Bug 1865452 - Remove review checker crossfade
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
Labels: 🛬 needs landing, approved

#4535 Bug 1865422 - Update review checker powered by url
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt
Labels: 🛬 needs landing, approved

#4486 Bug 1853625 - Fix Card selector in CreditCardAutofillTest.verifyMultipleCreditCardsCanBeAddedTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
Labels: 🛬 needs landing, approved

#4482 Bug 1864829 - New Firefox suggest related UI smoke tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: 🛬 needs landing, approved

#4415 Bug 1857537 - [a11y] Add heading structure to Review Checker
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckCards.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckInfoCard.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ext/HeadingResource.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4516 Bug 1865329 - Fix secret debug info text theme
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretDebugSettingsFragment.kt
Labels: 🛬 needs landing, approved

#4548 Bug 1865889 - Swap out Pixel2.arm [API 26] in robo-arm for Motorola G20
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🛬 needs landing, approved

#4465 Bug 1860844 - Add GeckoTranslateSessionDelegate to Android Components
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/translate/GeckoTranslateSessionDelegate.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/translate/GeckoTranslateSessionDelegateTest.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/DetectedLanguages.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationEngineState.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationPair.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
Labels: 🛬 needs landing, approved

#4549 Bug 1865904 - Add correct default elevation to FAB
  fenix/app/src/main/java/org/mozilla/fenix/compose/button/FloatingActionButton.kt
Labels: 🛬 needs landing, approved

#4551 Bug 1825116 - Resolve many lint issues found on oak
  android-components/components/feature/pwa/src/main/java/mozilla/components/feature/pwa/db/ManifestDao.kt
  android-components/components/service/digitalassetlinks/src/test/java/mozilla/components/service/digitalassetlinks/api/DigitalAssetLinksApiTest.kt
  android-components/components/tooling/lint/src/main/java/mozilla/components/tooling/lint/FactCollectDetector.kt
  android-components/components/tooling/lint/src/main/java/mozilla/components/tooling/lint/NotificationManagerChecks.kt
  android-components/components/tooling/lint/src/test/java/mozilla/components/tooling/lint/FactCollectDetectorTest.kt
  android-components/plugins/dependencies/src/main/java/ExtraRepositories.kt
  docs/changelog.md
  docs/rfcs/0009-remove-interactors-and-controllers.md
  docs/shared/android/writing_lint_rules.md
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/generate_smoke_tests.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/gradlewbuild.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/tests/test_generic_scenarios.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/ViewVisibilityIdlingResource.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataOnQuitRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsExceptionsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsRobot.kt
  fenix/mozilla-lint-rules/src/test/java/org/mozilla/fenix/lintrules/ContextCompatDetectorTest.kt
  fenix/mozilla-lint-rules/src/test/java/org/mozilla/fenix/lintrules/LicenseDetectorTest.kt
  focus-android/service-telemetry/src/main/java/org/mozilla/telemetry/measurement/TimezoneOffsetMeasurement.java
  taskcluster/ci/browsertime/kind.yml
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/test-apk/kind.yml
  taskcluster/ci/test-components/kind.yml
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing (squash), approved

#4565 Bug 1866060 - Add foreground permissions for feature-media
  android-components/components/feature/media/README.md
  android-components/components/feature/media/src/main/AndroidManifest.xml
  docs/changelog.md
Labels: 🛬 needs landing, approved

#4546 Bug 1866062 - New high priority Firefox suggest UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/FirefoxSuggestTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: 🛬 needs landing, approved

#4556 Bug 1865941 - Adds secret setting to enable Felt Privacy related features
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
Labels: 🛬 needs landing, approved

#4090 Bug 1803465 - extend isURLLenient to match IPv6 literals
  android-components/components/support/utils/src/main/java/mozilla/components/support/ktx/util/URLStringUtils.kt
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/WebURLFinder.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/URLStringUtilsTest.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/WebURLFinderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash), approved

#4561 Bug 1865318 - Fix review checker store tests
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4573 Bug 1862085 - Use different rc onboarding description based on tld
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckVendorsService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/DefaultReviewQualityCheckVendorsServiceTest.kt
Labels: 🛬 needs landing, approved

#4552 Bug 1865792 - FxA OriginMismatch exceptions
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Exceptions.kt
Labels: 🛬 needs landing, approved

#3264 Bug 1848623 - Re-enable errorForInvalidSearchEngineStringsTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: 🛬 needs landing, approved

#4579 Bug 1825116 - Consolidate attributes in build-apk kind.yml
  taskcluster/ci/build-apk/kind.yml
Labels: 🛬 needs landing (squash), approved

#4503 Bug 1865086 - More FxA error reporting
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/AccountStorage.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
Labels: 🛬 needs landing, approved

#4533 Bug 1865652 - Move Server Knobs configuration before Glean init
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing, approved

#4578 Bug 1866260: Update guide to merging contributor PR and add the steps to replace Bors
  fenix/docs/Guide-to-merging-contributor-PRs.md
Labels: 🛬 needs landing, approved

#4606 Bug 1812732 - Prevent empty Collection being created in Compose Tabs Tray
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
Labels: 🛬 needs landing, approved

#4188 Bug 1856431 - Encode file path in File URI scheme
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
Labels: 🛬 needs landing, approved

#4619 Bug 1866941 - Update Sentry to version 6.34.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4622 Bug 1866992 - Add product recommendations exposure telemetry
  fenix/app/metrics.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ShoppingExperienceFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferencesMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckBottomSheetStateFeatureTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeShoppingExperienceFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/DefaultReviewQualityCheckServiceTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4611 Bug 1865634 - Use legacy packaging for native code on AAB
  fenix/app/build.gradle
Labels: 🛬 needs landing, approved

#4630 Bug 1867148 - Shorten the max runtime for complete jobs to 3min
  taskcluster/ci/complete/kind.yml
Labels: 🛬 needs landing, approved

#4576 Bug 1866262 - [a11y] Clarify comment for accessibility string.
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4587 Bug 1861694 - Use analysis status to restore (re)analysis state
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingState.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingStateReducer.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/appstate/ShoppingActionTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4627 Bug 1866474 - Incorrect status is displayed after turning off the Cookie Banner Blocker feature from the panel
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorage.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorageTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/cookiehandling/CookieBannersStorage.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannersStorageExt.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/CookieBannerReducerMiddleware.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/CookieBannerReducerStore.kt
Labels: 🛬 needs landing, approved

#4641 Bump Application Services Release to 120.0.2
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
Labels: 🛬 needs landing, approved

#4568 Bug 1866293 - Add support for installing an add-on a from local file.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionRuntime.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonFilePicker.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonFilePickerTest.kt
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/preferences.xml
  fenix/app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
Labels: 🛬 needs landing, approved

#4651 Bug 1867297 - Remove the use of `BLOCKED_PERMISSIONS`
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/test/java/AddonManagerTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
Labels: 🛬 needs landing, approved

#4656 Bug 1867619: Fix the font list telemetry ping r?tlong
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/fonts/FontEnumerationWorker.kt
Labels: 🛬 needs landing, approved

#4628 Bug 1862262 - Translations Preferences
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/LanguageSetting.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationsRuntime.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
Labels: 🛬 needs landing, approved

#4489 Bug 1864759 - Add secret setting and nimbus flag for toolbar redesign
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/RedesignToolbarFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
Labels: 🛬 needs landing, approved
