Repository mozilla-mobile/firefox-android, pull requests merged in 2023-08, with the labels that each got.

#3067 Bug 1807268 - Disable failing verifyBasicNavigationToolbarFunctionality UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: 🛬 needs landing

#3021 Bug 1845905 - Add a utility to create store lazily
  fenix/app/src/main/java/org/mozilla/fenix/components/StoreProvider.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/StoreProviderTest.kt
Labels: 🛬 needs landing, approved

#3042 Bug 1842560 - Fix verifyRecentlyClosedTabsListTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/RecentlyClosedTabsRobot.kt
Labels: 🛬 needs landing, approved

#3068 Bug 1845255 - Add loading UI for review quality check
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductReviewLoading.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
Labels: 🛬 needs landing, approved

#3012 Bug 1842249 - Refactor HistoryFragment sync handlers to lib-state
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/state/HistorySyncMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/state/HistorySyncMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#3078 Bug 1839158 - Ignore invalid credit card save requests
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt
  android-components/components/concept/storage/src/test/java/mozilla/components/concept/storage/CreditCardEntryTest.kt
  android-components/components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/GeckoCreditCardsAddressesStorageDelegate.kt
  android-components/components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/GeckoCreditCardsAddressesStorageDelegateTest.kt
Labels: 🛬 needs landing, approved

#3071 Bug 1846480 - Add adjusted rating card for review quality check
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/res/values/static_strings.xml
Labels: 🛬 needs landing, approved

#3075 Bug 1845255 - Add loading UI for review quality check
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/build.gradle
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductReviewLoading.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
Labels: 🛬 needs landing

#3015 Bug 1845820 - Add the `WebExtensionInstallException.Blocklisted` class
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionException.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoWebExtensionExceptionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
Labels: 🛬 needs landing, approved

#3089 Bug 1845823 - Display a better error message when a user installs a blocklisted add-on
  android-components/components/feature/addons/src/main/res/values/strings.xml
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementFragmentTest.kt
Labels: 🛬 needs landing

#3090 Bug 1846773 - Set adjust preinstall file path in system properties
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
Labels: 🛬 needs landing, approved

#2876 Bug 1843859 - Address NullPointerException in CrashHandlerService.onStartCommand
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt
  android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/handler/CrashHandlerServiceTest.kt
Labels: 🛬 needs landing, approved

#2699 Bug 1841574 – changed menu item checkbox gravity from center horizontal to end
  android-components/components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_text_checkbox_button.xml
Labels: 🛬 needs landing, approved

#3094 Bug 1806469 - Adds an exception to `ThreadPenaltyDeath`
  fenix/app/src/main/java/org/mozilla/fenix/perf/ThreadPenaltyDeathWithIgnoresListener.kt
  fenix/app/src/test/java/org/mozilla/fenix/perf/ThreadPenaltyDeathWithIgnoresListenerTest.kt
  fenix/app/src/test/resources/IdsControllerLogcat.txt
Labels: 🛬 needs landing, approved

#3105 Bug 1840994 - Disable systemNotificationCantBeDismissedWhileDownloadingTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#2919 Bug 1817926 - Sets a max height on the logins prompt to prevent it from taking up the entire screen
  fenix/app/src/main/res/layout/fragment_browser.xml
Labels: 🛬 needs landing, approved

#3058 Bug 1845230 - Adds feature flag for felt privacy
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/pbm.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: 🛬 needs landing, approved

#3070 Bug 1840721 - For top sites we should prefer switching to open tabs vs opening a duplicate tab
  fenix/app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: 🛬 needs landing, approved

#3072 Bug 1846529 - New UI tests that verify the PB state after closing the app
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Labels: 🛬 needs landing, approved

#3023 Bug 1845944 - New custom tabs ETP settings UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
Labels: 🛬 needs landing, approved

#3106 Bug 1847082 - Update MTE team URL in Slack footer for test tasks
  taskcluster/ci/test-apk/kind.yml
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing, approved

#3119 Revert "Bug 1836971 - Respect never setting in open links in apps"
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Labels: 🛬 needs landing, approved

#3013 Bug 1842638 - Expose GeckoView isProductUrl API
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ShoppingProductStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/SessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ShoppingProductActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3118 Revert "Bug 1836971 - Respect never setting in open links in apps"
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Labels: 🛬 needs landing, approved

#3050 Bug 1813823 - stop re-recording timing distribution for recent synced tabs
  fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/recentsyncedtabs/RecentSyncedTabFeatureTest.kt
Labels: 🛬 needs landing, approved

#3115 Bug 1845823 - Fixup l10n comment
  android-components/components/feature/addons/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3057 Bug 1837524 - Contile Top Sites impression probe in Compose Top Sites
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
Labels: 🛬 needs landing, approved

#3085 Bug 1846713 - Improve package structure within shopping package
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferences.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferencesMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewGrade.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#3100 Bug 1840339 - Add review highlights card for shopping experience
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
Labels: 🛬 needs landing, approved

#3138 Bug 1845900 - deleting the last element of a collection, the entire collection is deleted
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, approved

#3099 Bug 1847211 - New unified search tab UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#3108 Bug 1845234 - Adds a new background gradient for TPBM
  fenix/app/src/main/java/org/mozilla/fenix/theme/ThemeManager.kt
  fenix/app/src/main/res/drawable/felt_private_home_background_gradient.xml
  fenix/app/src/main/res/values/styles.xml
Labels: 🛬 needs landing, approved

#3114 Bug 1847179 - Fix wrong error message displayed when trying to install an unsupported add-on
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
Labels: 🛬 needs landing, approved

#3116 Bug 1847186 - Enable the `mozAddonManager` web API on Fenix Nightly builds
  fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
Labels: 🛬 needs landing, approved

#3144 Bug 1845235 - Add "Private" label to Felt Privacy mode home screen
  fenix/app/src/main/res/drawable/ic_wordmark_text_felt_privacy.png
  fenix/app/src/main/res/layout/fragment_home.xml
  fenix/app/src/main/res/values/attrs.xml
  fenix/app/src/main/res/values/dimens.xml
  fenix/app/src/main/res/values/styles.xml
Labels: 🛬 needs landing, approved

#3164 Bug 1846287 - Catch LoginsApiException exception when fetching the list of logins and setting startup metrics
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing, approved

#3168 Bug 1833666 - Remove extra bracket from uplift video link
  docs/shared/uplift_guide.md
Labels: 🛬 needs landing, approved

#3161 Bug 1846229 - Ignore flaky test in ReviewQualityCheckStoreTest
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#3142 Bug 1836979 - Inline ListItemTabLarge.kt modifier onClick for ListItemTabSurface
  fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
Labels: 🛬 needs landing, approved

#3154 Bug 1847706 - Slightly refactor the `AddonsProvider` and its default implementation
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonsProvider.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/test/java/AddonManagerTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragmentTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
Labels: 🛬 needs landing (squash), approved

#3165 Bug 1846515 - Update Print Error Snackbar
  fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt
  fenix/app/src/main/res/layout/fenix_snackbar.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/share/SaveToPDFMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#3122 Bug 1843895 - Update AppLinksUseCases launchInApp when updating the interceptor
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
Labels: 🛬 needs landing, approved

#3053 Bug 1840692 - Expose Request Analysis Fakespot API
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/shopping/GeckoProductAnalysis.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/shopping/ProductAnalysis.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3197 Bug 1847956 - Show snackBars on top of the toolbar.
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
Labels: 🛬 needs landing, approved

#3180 Bug 1847906 - Add `getAddonIconBitmap()` to the `AddonsProvider` interface
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonsProvider.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3157 Bug 1847706 - Add `AddonsProvider.getAddonsByGUIDs()` and provide a default implementation
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonsProvider.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt
  android-components/components/feature/addons/src/test/resources/amo_search_localized_single_result.json
  android-components/components/feature/addons/src/test/resources/amo_search_multiple_results.json
  android-components/components/feature/addons/src/test/resources/amo_search_single_result.json
  android-components/components/feature/addons/src/test/resources/collection.json
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3060 Bug 1840693 - Expose Request Product Recommendations API
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/shopping/GeckoProductRecommendation.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/shopping/ProductRecommendation.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3192 Bug 1845323 - Bring back the downloading add-on dialog.
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/res/drawable/mozac_ic_extensions_black.xml
  fenix/app/src/main/res/layout/fragment_add_ons_management.xml
  fenix/app/src/main/res/layout/overlay_add_on_progress.xml
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementFragmentTest.kt
Labels: 🛬 needs landing, approved

#3160 Bug 1847916 - Refactor and re-enable toggleSearchBookmarksTest & toggleSearchHistoryTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: 🛬 needs landing, approved

#3185 Bug 1847922 - Update ReviewQualityCheckState for analysis present and not
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
Labels: 🛬 needs landing, approved

#3184 Bug 1846229 - Fix flaky ReviewQualityCheckStoreTest unit test
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#3206 Bug 1836979 - Inline ListItemTabLarge.kt modifier onClick for ListItemTabSurface
  fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
Labels: 🛬 needs landing, approved

#3179 Bug 1847908 - Remove duplicated unified tab search UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: 🛬 needs landing, approved

#3204 Bug 1848056 - Update detekt to to version 1.23.1
  android-components/config/detekt-baseline.xml
  android-components/config/detekt.yml
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/config/detekt.yml
  fenix/detekt-baseline.xml
  focus-android/quality/detekt-baseline.xml
  focus-android/quality/detekt.yml
Labels: 🛬 needs landing, approved

#3216 Bug 1848208 - Update Focus Download Link in README.md
  README.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#2635 Bug 1848191 - Add experimenter UI integration testing framework
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/Pipfile
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/Pipfile.lock
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/SurveyExperimentIntegrationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/__init__.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/conftest.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/gradlewbuild.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/launchSimScript.sh
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/pytest.ini
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/test_integration.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuExperimentsRobot.kt
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm64-v8a.yml
  fenix/automation/taskcluster/androidTest/flank-x86.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#3220 Bug 1847746 - Content Description on Print and Save to PDF
  fenix/app/src/main/java/org/mozilla/fenix/share/PrintItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFItem.kt
Labels: 🛬 needs landing, approved

#3086 Bug 1842566 - Fix flaky saveEditedPdfTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing, approved

#3207 Bug 1848144 - Onboarding tests TestRail Matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/UpgradingUsersOnboardingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#2844 Bug 1836896 - Hide statusbar when fullscreen on Android R+ devices
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
  android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
Labels: 🛬 needs landing, approved

#3193 Bug 1567912 - Add signing tasks for AABs
  taskcluster/android_taskgraph/transforms/signing_android_app.py
  taskcluster/android_taskgraph/transforms/upstream_artifacts.py
  taskcluster/ci/signing-apk/kind.yml
  taskcluster/ci/signing-bundle/kind.yml
Labels: 🛬 needs landing (squash), approved

#3147 Bug 1840338 - Add review quality info card to review product analysis.
  fenix/app/src/main/java/org/mozilla/fenix/compose/ClickableSubstringLink.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/res/values/static_strings.xml
Labels: 🛬 needs landing, approved

#3121 Bug 1842251 - Refactor HistoryController delete functions to lib-state.
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/PendingDeletionHistory.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/state/HistoryStorageMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/state/HistoryTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/state/bindings/PendingDeletionBinding.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/state/HistoryStorageMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/state/HistoryTelemetryMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#3234 Bug 1847282 - Change the default for pull-to-refresh to disabled
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: 🛬 needs landing

#3211 Bug 1847923 - Part 1: Add ProductAnalysisMapper
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
Labels: 🛬 needs landing, approved

#3238 Bug 1567912 - Add signing tasks for AABs
  taskcluster/android_taskgraph/routes.py
  taskcluster/android_taskgraph/transforms/signing_android_app.py
  taskcluster/android_taskgraph/transforms/upstream_artifacts.py
  taskcluster/ci/signing-apk/kind.yml
  taskcluster/ci/signing-bundle/kind.yml
Labels: 🛬 needs landing, approved

#3266 Bug 1848436 - Temporarily disable failing test in HistoryStorageMiddlewareTest
  fenix/app/src/test/java/org/mozilla/fenix/library/history/state/HistoryStorageMiddlewareTest.kt
Labels: 🛬 needs landing

#3209 Bug 1848142 - Homescreen TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextualHintsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#3031 Bug 1844967 - Improve performance of tab thumbnail loading in Compose
  fenix/app/src/main/java/org/mozilla/fenix/compose/TabThumbnail.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ThumbnailImage.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTabViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeGridViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeListViewHolder.kt
Labels: 🛬 needs landing, approved

#3212 Bug 1847923 - Part 2: Add network middleware for review quality check
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckServiceImplTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#3270 Bug 1848377 - Add secret setting to control the visibility of the Shopping feature
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ShoppingExperienceFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
Labels: 🛬 needs landing, approved

#3277 Bug 1848819 - Sync initial experiment from main to v116
  fenix/app/src/main/res/raw/initial_experiments.json
Labels: 🛬 needs landing, approved

#3241 Bug 1842039 - Add bread crumbs for IllegalArgumentException when navigating
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/ext/NavController.kt
  fenix/app/src/main/java/org/mozilla/fenix/nimbus/controller/NimbusBranchesController.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/controller/OnboardingController.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/DefaultOnboardingControllerTest.kt
Labels: 🛬 needs landing, approved

#3285 Bug 1842039 - Submit caught exception for IllegalArgumentException when navigating.
  fenix/app/src/main/java/org/mozilla/fenix/ext/NavController.kt
Labels: 🛬 needs landing, approved

#3290 Bug 1807268 - Disable openAllInTabsTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#3139 Bug 1847560 - New unified history search UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
Labels: 🛬 needs landing, approved

#3267 Bug 1848668 - Update Shopping lastAnalysisTime to long to avoid time …
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/shopping/GeckoProductAnalysis.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt
Labels: 🛬 needs landing, approved

#3294 Bug 1842596 - Recover from UnrecoverableKeyException when retrieving sync key
  android-components/components/lib/dataprotect/src/main/java/mozilla/components/lib/dataprotect/Keystore.kt
Labels: 🛬 needs landing, approved

#3186 Bug 1840471 - Release Menu Printing out of Nightly
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
Labels: 🛬 needs landing, approved

#3315 Bug 1845098 - reduce external-gradle-dependencies max-run-time from 4h to 40min
  taskcluster/ci/external-gradle-dependencies/kind.yml
Labels: 🛬 needs landing, approved

#3292 Bug 1845098 - give java more heap space for external-gradle-dependencies job
  taskcluster/scripts/toolchain/external-gradle-dependencies.sh
Labels: 🛬 needs landing, approved

#3279 Bug 1848862 - Update mockk to version 1.13.7
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3317 Revert "Bug 1842596 - Recover from UnrecoverableKeyException when retrieving sync key"
  android-components/components/lib/dataprotect/src/main/java/mozilla/components/lib/dataprotect/Keystore.kt
Labels: 🛬 needs landing, approved

#3321 Bug 1842596 - Recover from UnrecoverableKeyException when retrieving sync key
  android-components/components/lib/dataprotect/src/main/java/mozilla/components/lib/dataprotect/Keystore.kt
Labels: 🛬 needs landing, approved

#3327 Bug 1849278 - Ignore mainMenuOpenInAppTest failures
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: 🛬 needs landing, approved

#3314 Bug 1849146 - Add tab and history search smoke tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: 🛬 needs landing, approved

#728 Bug 1815883 - Switch to the rust_log_forwarder module
  android-components/components/support/rustlog/build.gradle
  android-components/components/support/rustlog/src/main/java/mozilla/components/support/rustlog/RustLog.kt
  android-components/components/support/rustlog/src/test/java/mozilla/components/support/rustlog/RustLogTest.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  focus-android/app/src/main/java/org/mozilla/focus/FocusApplication.kt
Labels: 🛬 needs landing, approved

#3323 Bug 1849225 - Add TextDecoration and text color to LinkText link portion`
  fenix/app/src/main/java/org/mozilla/fenix/compose/LinkText.kt
Labels: 🛬 needs landing, approved

#3345 Bug 1838839 - Ship 118.0.0 of feature-webcompat
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1848711-vio.com-page-height.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1848713-cleanrider.com-slider.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1848716-elal.com-unsupported-banner.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1848849-theaa.com-printing-mode-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1849019-axa-assistance.pl-datepicker-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1849388-kucharkaprodceru.cz-scroll-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1605611-maps.google.com-directions-time.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1784302-effectiveType-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1849058-nicochannel.jp-picture-in-picture-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#3339 Bug 1848668 - Remove Shopping lastAnalysisTime toLong conversion
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
Labels: 🛬 needs landing, approved

#2688 Bug 1813788 - Split deleting site data from browsing history (and merge with cookies)
  android-components/components/lib/crash/docs/metrics.md
  android-components/components/service/nimbus/docs/metrics.md
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataOnQuitRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuit.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataController.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataOnQuitType.kt
  fenix/app/src/main/res/layout/fragment_delete_browsing_data.xml
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/delete_browsing_data_quit_preferences.xml
  fenix/app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt
  fenix/detekt-baseline.xml
Labels: 🛬 needs landing, approved

#3371 Bug 1849326 - Use https in @string/search_add_custom_engine_suggest_string_example
  fenix/app/src/main/res/layout/fragment_save_search_engine.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3378 Bug 1849085 - Add localization for the "Search engines" setting preference header
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/search_settings_preferences.xml
Labels: 🛬 needs landing, approved

#3379 Bug 1849978 - Remove smoke test annotation from context menu related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: 🛬 needs landing, approved

#3382 Bug 1837365 - Remove lifestyle image assets
  fenix/app/onboarding.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingScreen.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageUiData.kt
  fenix/app/src/main/res/drawable-hdpi/onboarding_default_browser.webp
  fenix/app/src/main/res/drawable-hdpi/onboarding_notification.webp
  fenix/app/src/main/res/drawable-hdpi/onboarding_sync.webp
  fenix/app/src/main/res/drawable-xhdpi/onboarding_default_browser.webp
  fenix/app/src/main/res/drawable-xhdpi/onboarding_notification.webp
  fenix/app/src/main/res/drawable-xhdpi/onboarding_sync.webp
  fenix/app/src/main/res/drawable-xxhdpi/onboarding_default_browser.webp
  fenix/app/src/main/res/drawable-xxhdpi/onboarding_notification.webp
  fenix/app/src/main/res/drawable-xxhdpi/onboarding_sync.webp
  fenix/app/src/main/res/raw/keep.xml
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/OnboardingPageUiDataTest.kt
Labels: 🛬 needs landing, approved

#3320 Bug 1849189 - Update Focus telemetry probes expiring in v120
  focus-android/app/metrics.yaml
Labels: 🛬 needs landing, approved

#3389 Bug 1813788 - Part 2: Add UnusedResources specifiers to strings needing it + Remove unused testing functions
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataRobot.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3381 Bug 1841582 - Opening link from shortcuts should display the page.
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: 🛬 needs landing, approved

#3387 Bug 1846979 - Add extensions process crash dialog strings
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3397 Bug 1813521 - Disable DownloadTest.pauseResumeCancelDownloadTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing, approved

#3403 Bug 1850375: Start the 119 development cycle
  docs/changelog.md
  focus-android/app/src/main/res/drawable/ic_whats_new.xml
  focus-android/app/src/main/res/layout/menu_whatsnew.xml
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#1356 Bug 1812730 - Prevent collections with empty name from being created
  fenix/app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt
  fenix/app/src/main/java/org/mozilla/fenix/collections/CollectionsDialog.kt
Labels: 🛬 needs landing, approved

#3401 Bug 1844960 - Bookmark suggestions should appear unconcerned with the search suggestions setting.
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchEngineSuggestionProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
Labels: 🛬 needs landing, approved

#3356 Bug 1849329 - Update local GV docs
  fenix/docs/substituting-local-gv.md
Labels: 🛬 needs landing, approved

#3278 Bug 1842250 - Refactor the remaining HistoryController functions to lib-state
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryView.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/state/HistoryNavigationMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/state/HistoryTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/state/bindings/MenuBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/HistoryFragmentStoreTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/state/HistoryNavigationMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/state/HistoryTelemetryMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/state/bindings/MenuBindingTest.kt
Labels: 🛬 needs landing, approved

#3159 Bug 1796189 - List extensions installed outside the list of featured extensions
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonsProvider.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt
  android-components/components/feature/addons/src/test/java/AddonManagerTest.kt
  android-components/components/feature/addons/src/test/java/AddonTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
Labels: 🛬 needs landing, approved

#3302 Bug 1845231 - Adds a mask to the tab counter in private mode
  android-components/.buildconfig.yml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_private_mode_12.xml
  android-components/components/ui/tabcounter/build.gradle
  android-components/components/ui/tabcounter/src/main/java/mozilla/components/ui/tabcounter/TabCounter.kt
  android-components/components/ui/tabcounter/src/main/res/drawable/mozac_ui_tabcounter_badge.xml
  android-components/components/ui/tabcounter/src/main/res/layout/mozac_ui_tabcounter_layout.xml
  android-components/components/ui/tabcounter/src/test/java/mozilla/components/ui/tabcounter/TabCounterTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/home/TabCounterView.kt
  fenix/app/src/main/res/layout/fragment_home.xml
  fenix/app/src/test/java/org/mozilla/fenix/home/TabCounterViewTest.kt
Labels: 🛬 needs landing, approved

#3372 Bug 1849564 - Add support for CFR popup centered alignment
  android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopup.kt
  android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopupFullscreenLayout.kt
  android-components/components/compose/cfr/src/test/java/mozilla/components/compose/cfr/CFRPopupFullscreenLayoutTest.kt
Labels: 🛬 needs landing, approved

#3427 Bug 1850673 - Enable the `mozAddonManager` web API on Fenix Beta builds
  fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
Labels: 🛬 needs landing, approved

#3420 Bug 1850623 - Register tab/action handlers when an extension has been installed.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🛬 needs landing, approved

#3422 Bug 1850375: remove color now useless after removing an unused drawable
  focus-android/app/src/main/res/values-night/colors.xml
  focus-android/app/src/main/res/values/colors.xml
Labels: 🛬 needs landing, approved

#2794 Bug 1810780 - Add reorder gesture to composed tabs tray
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeGridViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeListViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ReorderableGrid.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ReorderableList.kt
Labels: 🛬 needs landing, approved

#1576 Bug 1807127 - Update Sync Device name after refreshing fxa devices
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsInteractor.kt
Labels: 🛬 needs landing, approved

#3337 Bug 1847740 - Add navigation middleware for review quality check
  fenix/app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#3444 Bug 1847756 - Adjust permissions dialog when there is no permission
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt
Labels: 🛬 needs landing, approved

#3446 Revert "Bug 1844960 - Bookmark suggestions should appear unconcerned with the search suggestions setting."
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchEngineSuggestionProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
Labels: 🛬 needs landing, approved

#3430 Bug 1850280 - Control extensions process rollout with Nimbus
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/extensions/ExtensionProcessTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
Labels: 🛬 needs landing, approved

#3448 Bug 1850987 - Stop sending RecordNotFoundException to crash reporter
  android-components/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3298 Bug 1849009 – extended fullscreen mode to utilize the notch area
  android-components/components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppActivityFeatureTest.kt
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
  android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
  docs/changelog.md
  focus-android/app/src/test/java/org/mozilla/focus/browser/integration/FullScreenIntegrationTest.kt
Labels: 🛬 needs landing, approved
