Repository mozilla-mobile/firefox-android, pull requests merged in 2023-03, with the labels that each got.

#876 Bug 1817524 - Do not show homepage if last tab of section is closed while not in view
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
Labels: 🛬 needs landing, approved

#983 Bug 1818774 - Navigate to search dialog when interacting with homescreen private browsing button
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: 🛬 needs landing, approved

#1047 Bug 1819578 - Fix fenix android test debug shipping product
  taskcluster/ci/build-apk/kind.yml
Labels: 🛬 needs landing

#1007 Bug 1813449 - Fix accessibility issues on Tabs Tray screen
  fenix/app/src/main/res/layout/component_tabstray2.xml
Labels: 🛬 needs landing (squash)

#873 Bug 1813451 - Fix accessibility issues on History deletion screen
  fenix/app/src/main/res/layout/delete_history_time_range_dialog.xml
Labels: 🛬 needs landing

#919 Bug 1815631 - changed height and reduced padding for `Active` text from the Studies menu
  fenix/app/src/main/res/layout/studies_section_item.xml
  fenix/app/src/main/res/values/integers.xml
  fenix/app/src/main/res/values/styles.xml
Labels: 🛬 needs landing (squash)

#1031 Bug 1819431 - Reimplement default browser notification with Nimbus Messaging equivalent
  fenix/app/metrics.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingMessageTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessor.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/home/intent/DefaultBrowserIntentProcessorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
  fenix/detekt-baseline.xml
  fenix/messaging.fml.yaml
Labels: 🛬 needs landing (squash)

#920 Bug 1810631 - Display name instead of e-mail in menu
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserMenuSignIn.kt
  fenix/app/src/test/java/org/mozilla/fenix/menu/BrowserMenuSignInTest.kt
Labels: 🛬 needs landing (squash)

#1048 Bug 1818473 - Ignore case when searching through logins
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/LoginsFragmentStore.kt
Labels: 🛬 needs landing

#975 Bug 1818056 - Delay TCP CFR until dismissing the cookie banner re-engagement dialog
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextualHintsTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialogUtils.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
Labels: 🛬 needs landing

#1006 Bug 1819012 - Change browser toolbar behavior only if view is created.
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#1059 Bug 1819733 - Fix broken tests in `TabSheetBehaviorManagerTest`
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabSheetBehaviorManager.kt
Labels: 🛬 needs landing, approved

#1074 Bug 1819914 - Call ensureMarketingChannelExists in MessageNotificationWorker
  fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/MessageNotificationWorker.kt
Labels: 🛬 needs landing

#982 Bug 1807283 - re-enable verifyJumpBackInSectionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: 🛬 needs landing

#1075 Bug 1819927 - Remove DEFAULT_BROWSER_NOTIFICATION_ID from MarketingNotificationHelper
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/MarketingNotificationHelper.kt
Labels: 🛬 needs landing

#1073 Bug 1819746 - Fix for possible NullPointerException on a potential nullable object reference in DisplayOrientationListener
  android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/helper/DisplayOrientationListener.kt
  android-components/components/compose/cfr/src/test/java/mozilla/components/compose/cfr/helper/DisplayOrientationListenerTest.kt
Labels: 🛬 needs landing, approved

#1058 Bug 1819730 - Upgrade Robolectric to latest version (4.9.2)
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#1033 Bug 1819153: Add androidx tracing dependency to resolve NoSuchMethodError
  fenix/app/build.gradle
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/app/build.gradle
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#1080 Bug 1819970 - Add uplift process documentation
  docs/shared/uplift_guide.md
Labels: 🛬 needs landing

#1084 Bug 1819776 - Remove unused test dependencies from support-rusthttp (partial backport #1061)
  android-components/components/support/rusthttp/build.gradle
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing

#1068 Bug 1819810 - Ensure the RustSyncManager is a singleton
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
Labels: 🛬 needs landing, approved

#1054 Bug 1818085 - Add preference to allow user to choose how open links in app works
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  fenix/app/metrics.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuOpenLinksInAppsRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserver.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Services.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/OpenLinksInAppsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/open_links_in_apps_preferences.xml
  fenix/app/src/main/res/xml/preferences.xml
  fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserverTest.kt
Labels: 🛬 needs landing, approved

#1076 Bug 1819910 - Update Sentry to version 6.15.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#747 Bug 1815609 - changes to Acehnese locale name
  focus-android/app/src/main/java/org/mozilla/focus/locale/screen/LocaleDescriptor.kt
Labels: 🛬 needs landing

#1108 Bug 1820129 - Fix Fenix test result report URL
  fenix/build.gradle
Labels: 🛬 needs landing

#1088 Bug 1820129 - part 1: Do not let Gradle tests silently fail anymore
  taskcluster/scripts/toolchain/external-gradle-dependencies.sh
Labels: 🛬 needs landing

#1091 Bug 1792933 - Replace deprecated requireFragmentManager method in AC tests.
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragmentTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/SimpleRedirectDialogFragmentTest.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragmentTest.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/ui/DownloadAppChooserDialogTest.kt
  android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragmentTest.kt
Labels: 🛬 needs landing, approved

#1089 Bug 1820130 - Use compose foundation insets over accompanist insets
  fenix/app/build.gradle
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/HomeNotificationPermissionDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/HomeOnboardingDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/NotificationPermissionDialogScreen.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/UpgradeOnboarding.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing, approved

#882 Bug 1812175 - Turn on Sync page and touch target suggestion is displayed.
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
Labels: 🛬 needs landing (squash)

#1014 Bug 1816421 - Disable fission performance tests
  taskcluster/ci/browsertime/kind.yml
Labels: 🛬 needs landing

#1133 Bug 1819254 - Don't exit fullscreen for user input prompts
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ext/PromptRequest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ext/PromptRequestTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#1138 Update GeckoView (Release) to 111.0.20230306162820
  android-components/plugins/dependencies/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#1100 Bug 1820242 - Remove in_progress_media_tab_opened probe
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/recenttabs/controller/RecentTabControllerTest.kt
Labels: 🛬 needs landing

#958 Bug 1817523 – fix application search engines background
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  fenix/app/src/main/res/drawable/ic_bookmarks_search.xml
  fenix/app/src/main/res/drawable/ic_history_search.xml
  fenix/app/src/main/res/drawable/ic_tabs_search.xml
Labels: 🛬 needs landing

#1139 Bug 1819909 – add telemetry for private browsing CFR
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, approved

#1123 Bug 1820169 - Ensure shortcuts snackbars are shown
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: 🛬 needs landing

#1135 Bug 1820559 - Remove PlacesStorage maintenance feature flag for enabling the feature to all users.
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing

#1003 Bug 1817519 – force search for not default engines
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: 🛬 needs landing

#1143 Bug 1820552 - Increase Site's field x button in Add new login
  fenix/app/src/main/res/layout/fragment_add_login.xml
Labels: 🛬 needs landing

#1149 Bug 1805409 - Ship v112.0.0 of the WebCompat System Addon
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1694470-myvidster.com-content-not-shown.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1754473-m.intl.taobao.com-number-arrow-buttons-overlapping-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1800127-www.burgerking.es-webkit-fill-available-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1448747-fastclick-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1778239-m.pji.co.kr-banner-hide.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1818818-fastclick-legacy-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1819450-cmbchina.com-ua-change.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1819476-axisbank.com-webkitSpeechRecognition-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1819678-cnki.net-undisable-search-field.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#1148 Bug 1819645 - Limit the cookie banner re-engagement dialog to a maximum of two shows
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialogUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing

#1101 Bug 1820271 - Renew telemetry probes expiring in v114
  fenix/app/metrics.yaml
Labels: 🛬 needs landing, approved

#861 Bug 1817029 - Add the client-deduplication ping
  fenix/.experimenter.yaml
  fenix/app/metrics.yaml
  fenix/app/pings.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/ActivationPing.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationLifecycleObserver.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPing.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPingTest.kt
  fenix/nimbus.fml.yaml
Labels: 🛬 needs landing (squash)

#1082 Bug 1820036 - Add Matrix labeling on Firebase Test Lab
  fenix/automation/taskcluster/androidTest/ui-test.sh
  taskcluster/android_taskgraph/transforms/test.py
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing

#1131 Bug 1820553 - Fix speedometer3 task naming for Fenix.
  taskcluster/ci/browsertime/kind.yml
Labels: 🛬 needs landing (squash)

#1153 Bug 1820861 - Update AC documentation Ruby dependencies
  docs/Gemfile
  docs/Gemfile.lock
Labels: 🛬 needs landing

#1018 Bug 1814988 - Add paging to `TabsTray`
  fenix/app/build.gradle
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing, approved

#1060 Bug 1806741 - Expose hasRuleForBrowsingContext API
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#985 Bug 1813252 - Refactor MessagingMiddlewareTest to use a real Store in…
  fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
Labels: 🛬 needs landing

#1157 Bug 1820961 - Add smoke test annotation to mainMenuAddToHomeScreenTest and addPrivateBrowsingShortcutTest UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddToHomeScreenTest.kt
Labels: 🛬 needs landing

#1158 Bug 1820967 - Use `id` instead of `flight_id` to identify a sponsored story
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/ext/Mappers.kt
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/api/ApiSpoc.kt
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/api/SpocsJSONParser.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/ext/MappersKtTest.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/helpers/PocketTestResources.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/db/SpocsDaoTest.kt
  docs/changelog.md
  fenix/app/metrics.yaml
Labels: 🛬 needs landing

#1166 Bug 1821088 - Update notify block in test-apk CI task
  taskcluster/ci/test-apk/kind.yml
Labels: 🛬 needs landing

#1169 Bug 1817070 - Add strings used for experimentation with Re-engagement notifications
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#852 Bug 1812144 - `Homescreen` appbar drag issue fixed
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing

#1170 Bug 1821128 - Use correct beetmover folder prefix for fenix nightly
  taskcluster/android_taskgraph/util/scriptworker.py
Labels: 🛬 needs landing, approved

#1167 Bug 1821032 - Add telemetry for the homescreen no collections placeholder close button
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: 🛬 needs landing, approved

#1156 Bug 1816743 - Create Tabs Tray banner container UI
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: 🛬 needs landing, approved

#1134 Bug 1818802 - Update strings in the ETP settings screen. Part 1 of 2
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#1168 Bug 1817029 - Add the client-deduplication ping (#861) BACKPORT
  fenix/.experimenter.yaml
  fenix/app/metrics.yaml
  fenix/app/pings.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/ActivationPing.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationLifecycleObserver.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPing.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPingTest.kt
  fenix/nimbus.fml.yaml
Labels: 🛬 needs landing

#1176 Bug 1820130 - Remove unused accompanist insets dependency
  fenix/app/build.gradle
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing

#1137 Bug 1817524 - Do not show homepage if last tab of section is closed while not in view
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
Labels: 🛬 needs landing, approved

#1041 Bug 1818826 - Remove Android Component Nimbus gradle plugin wrapper
  android-components/.buildconfig.yml
  android-components/components/tooling/nimbus-gradle-plugin/README.md
  android-components/components/tooling/nimbus-gradle-plugin/build.gradle
  android-components/components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy
  android-components/components/tooling/nimbus-gradle-plugin/src/main/resources/plugin.properties
  fenix/app/build.gradle
  fenix/app/messaging.fml.yaml
  fenix/app/nimbus.fml.yaml
  fenix/build.gradle
  focus-android/app/build.gradle
  focus-android/app/nimbus.fml.yaml
  focus-android/build.gradle
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#1163 Bug 1820984 - Follow-up on loginsAndPasswordsSettingsItemsTest missing steps
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
Labels: 🛬 needs landing

#1183 Bug 1821511 - Update comm links in Firefox-for-Android-Team-Processes
  fenix/docs/Firefox-for-Android-Team-Processes.md
Labels: 🛬 needs landing

#1182 Bug 1809809 - do not call onWallpaperSelected if user selects currently set wallpaper
  fenix/app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
Labels: 🛬 needs landing, approved

#1177 Bug 1821285 - New credit card deletion UI smoke tests and other refactoring work
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Labels: 🛬 needs landing

#1175 Bug 1821266 - Refactor privateModeScreenItemsTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddToHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing

#1147 Bug 1817525 - Voice input now appends query in EditToolbar
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/edit/EditToolbarTest.kt
  android-components/components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
  android-components/config/detekt-baseline.xml
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: 🛬 needs landing, approved

#1211 Bug 1822106 - Move experimenter.yaml file location
  android-components/components/lib/crash/docs/metrics.md
  android-components/components/support/sync-telemetry/docs/metrics.md
  fenix/app/.experimenter.yaml
  focus-android/app/.experimenter.yaml
Labels: 🛬 needs landing, approved

#1214 Bug 1822109 - Refactor OnboardingState into its own file
  fenix/app/src/main/java/org/mozilla/fenix/home/Mode.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingState.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/ModeTest.kt
Labels: 🛬 needs landing

#1210 Bug 1822073 - Start the Nightly 113 development cycle
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#1215 Bug 1822110 - Refactor HomeMenuBuilder to HomeMenuView
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenuView.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/HomeMenuViewTest.kt
Labels: 🛬 needs landing, approved

#1192 Bug 1821261 – Enables unified search on nightly
  fenix/app/nimbus.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
Labels: 🛬 needs landing, approved

#1220 Bug 1822181 - Refactor TabCounterBuilder to TabCounterView
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/TabCounterView.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/TabCounterViewTest.kt
Labels: 🛬 needs landing, approved

#1203 Bug 1821973 - New tabs option summary updates UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuTabsRobot.kt
Labels: 🛬 needs landing

#1189 Bug 1820134 - Update accompanist drawable painter
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing, approved

#1144 Bug 1811175 - Use sponsored tiles fallback protocol only when Contile outage is detected
  android-components/components/service/contile/src/main/java/mozilla/components/service/contile/ContileTopSitesProvider.kt
  android-components/components/service/contile/src/test/java/mozilla/components/service/contile/ContileTopSitesProviderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#1205 Bug 1821986 - new opening screen option summary updates UI smoke test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
Labels: 🛬 needs landing

#1232 Bug 1822198 - use relbot 6.0.0
  .github/workflows/ac-update-geckoview.yml
Labels: 🛬 needs landing

#1204 Bug 1821715 - Update OnboardingPageState to include button actions
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/NotificationPermissionDialogScreen.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageState.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/UpgradeOnboarding.kt
Labels: 🛬 needs landing, approved

#1240 Bug 1803130 - Remove leftover .git-blame-ignore-revs file
  fenix/.git-blame-ignore-revs
Labels: 🛬 needs landing

#1217 Bug 1814994 - Create Tabs Tray list and grid layouts
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
Labels: 🛬 needs landing, approved

#1241 Bug 1822375 - Remove unneeded and now incorrect AndroidComponents.kt
  fenix/buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#1244 Bug 1822378 - Refactor OnboardingInteractor into its own file
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/interactor/OnboardingInteractor.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolderTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolderTest.kt
Labels: 🛬 needs landing, approved

#1243 Bug 1822392 - Remove stray GMS reference for annotation
  fenix/app/src/main/java/org/mozilla/fenix/widget/VoiceSearchActivity.kt
Labels: 🛬 needs landing

#842 Bug 1807324 - Add macrobenchmarks for startup metrics
  fenix/.buildconfig.yml
  fenix/app/build.gradle
  fenix/app/src/main/AndroidManifest.xml
  fenix/app/src/main/java/org/mozilla/fenix/Config.kt
  fenix/benchmark/build.gradle
  fenix/benchmark/src/main/AndroidManifest.xml
  fenix/benchmark/src/main/java/org/mozilla/fenix/benchmark/StartupBenchmark.kt
  fenix/benchmark/src/main/java/org/mozilla/fenix/benchmark/utils/Constants.kt
  fenix/benchmark/src/main/java/org/mozilla/fenix/benchmark/utils/MacroBenchmarkRule.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  fenix/settings.gradle
Labels: approved

#1230 Bug 1822267 - Improve coverage for "Edit bookmarks" related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing

#1245 Bug 1821466 - Add nimbus message for fullscreen research surface
  fenix/app/messaging.fml.yaml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#1209 Bug 1814032 - Retry attempts for address autofill in UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Labels: 🛬 needs landing

#956 Bug 1812862 - Switch browsing mode on tab selected
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
Labels: 🛬 needs landing, approved

#1237 Bug 1821718 - Add feature and nimbus flag for juno onboarding
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing, approved

#1257 Bug 1822446 - Add OnboardingController for handling onboarding functionality
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/controller/OnboardingController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/DefaultOnboardingControllerTest.kt
Labels: 🛬 needs landing

#1248 Bug 1820897 - Disable the private theme from being used in the Composified Tabs Tray
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: 🛬 needs landing, approved

#1247 Bug 1815620 - Truncate long tab titles before they are composed
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
Labels: 🛬 needs landing

#1218 Bug 1822283 - Fix race condition for Ad IDs
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPing.kt
Labels: 🛬 needs landing, approved

#1020 Bug 1812149 - Add ContextWrapper before updating locale
  android-components/.buildconfig.yml
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/activity/GeckoViewActivityContextDelegate.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/activity/GeckoViewActivityContextDelegateTest.kt
  android-components/components/support/locale/src/main/java/mozilla/components/support/locale/ActivityContextWrapper.kt
  android-components/components/support/locale/src/main/java/mozilla/components/support/locale/LocaleAwareAppCompatActivity.kt
  android-components/components/support/locale/src/test/java/mozilla/components/support/locale/ActivityContextWrapperTest.kt
  android-components/samples/browser/build.gradle
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing, approved

#1262 Bug 1822606 - Refactor HomeFragment.navigateToSearch() to the ToolbarController
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
Labels: 🛬 needs landing

#1181 Bug 1821464 Add UI test to NotificationWorker
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingNotificationTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/MessageNotificationWorker.kt
Labels: 🛬 needs landing

#1260 Bug 1816059 - Show the notification for entering fullscreen as a Toast
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt
  focus-android/app/src/test/java/org/mozilla/focus/browser/integration/FullScreenIntegrationTest.kt
Labels: 🛬 needs landing

#1263 Bug 1822634 - Refactor tab counter code from HomeFragment into TabCounterView
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/TabCounterView.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/TabCounterViewTest.kt
Labels: 🛬 needs landing, approved

#1269 Bug 1814995 - Add private tabs to `TabsTray`
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
Labels: 🛬 needs landing, approved

#1242 Bug 1819153 - Add androidx tracing dependency to resolve NoSuchMethodError
  fenix/app/build.gradle
  focus-android/app/build.gradle
Labels: 🛬 needs landing

#900 Bug 1809815 - Talkback does not mention `Show all` as a button in the Recently visited section
  fenix/app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
Labels: 🛬 needs landing

#1072 Bug 1813450 - Increase tap area for autocomplete edit text in address bar
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: 🛬 needs landing

#1173 Bug 1807558 - TalkBack mentions activate actions for read only items in ETP settings info panels
  fenix/app/src/main/res/layout/fragment_tracking_protection_blocking.xml
Labels: 🛬 needs landing

#1281 Bug 1819950 - Ensure a change of orientation on new Androids will dismiss CFRs
  android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/helper/DisplayOrientationListener.kt
  android-components/components/compose/cfr/src/test/java/mozilla/components/compose/cfr/helper/DisplayOrientationListenerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#1283 Bug 1822804 - Update jna to version 5.13.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#1289 Bug 1822895 - added examples of exceptions in the uplift guide doc
  docs/shared/uplift_guide.md
Labels: 🛬 needs landing

#1291 Bug 1822899 - Limit Nimbus message display count to max display count
  fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  fenix/app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
Labels: 🛬 needs landing, approved

#1285 Bug 1822601 - Refactor toolbar related logic into a ToolbarView
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/ToolbarView.kt
Labels: 🛬 needs landing

#1178 Bug 1815951 - Increase touch area in Edit login screen
  fenix/app/src/main/res/layout/fragment_edit_login.xml
Labels: 🛬 needs landing

#1277 Bug 1812736 - Display snackbar when a new tab is added to a collection
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing

#1255 Bug 1802627 - Microphone icon is incorrectly placed on the 2x1 size widget
  android-components/components/feature/search/src/main/res/layout/mozac_search_widget_small.xml
Labels: 🛬 needs landing

#1070 Bug 1815011 - Create a top-level FAB Composable
  fenix/app/src/main/java/org/mozilla/fenix/compose/button/FloatingActionButton.kt
Labels: 🛬 needs landing

#1301 Bug 1822283 - Fix race condition for Ad IDs
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPing.kt
Labels: 🛬 needs landing

#1300 Bug 1822283 - Fix race condition for Ad IDs
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPing.kt
Labels: 🛬 needs landing

#1264 Bug 1822269 - add androidx.activity-compose dependency
  fenix/app/build.gradle
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing, approved

#1299 Bug 1823059 - Replace deprecated ktlint_disabled_rules.
  focus-android/.editorconfig
Labels: 🛬 needs landing

#1328 Bug 1819153 - Adjust startup task to resolve NoSuchMethodError on Firebase Test Lab
  taskcluster/ci/startup-test/kind.yml
Labels: 🛬 needs landing

#389 Bug 1803589 - Implement submit site support requests for cookie banners in Focus
  focus-android/app/metrics.yaml
  focus-android/app/pings.yaml
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerexception/CookieBannerExceptionDetailsPanel.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerexception/CookieBannerExceptionItem.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerexception/CookieBannerExceptionMiddleware.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerexception/CookieBannerExceptionStore.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerexception/DefaultCookieBannerExceptionInteractor.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/CookieBannerExceptionDetailsSwitch.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/CookieBannerReducerDetailsPanel.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/CookieBannerReducerItem.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/CookieBannerReducerMiddleware.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/CookieBannerReducerStatus.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/CookieBannerReducerStore.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/DefaultCookieBannerReducerInteractor.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/settings/privacy/TrackingProtectionPanel.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
  focus-android/app/src/main/res/layout/cookie_banner_reducer_details.xml
  focus-android/app/src/main/res/values/colors.xml
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#1261 Bug 1822611 - New open links in apps related UI smoke tests
  fenix/app/src/androidTest/assets/pages/externalLinks.html
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/WebControlsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuOpenLinksInAppsRobot.kt
Labels: 🛬 needs landing

#1326 Bug 1821722 - Add juno onboarding strings
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#1190 Bug 1820122 - Use b-android-xlarge to speed up external-gradle-dependencies jobs
  taskcluster/ci/config.yml
  taskcluster/ci/external-gradle-dependencies/kind.yml
Labels: 🛬 needs landing

#1332 Bug 1823532 - Remove jnaForTest from project Gradle build files.
  android-components/build.gradle
  android-components/components/service/glean/build.gradle
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/build.gradle
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/app/build.gradle
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#1339 Bug 1823442 - Remove androidx.tracing:tracing dependency
  fenix/app/build.gradle
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/app/build.gradle
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#1194 Bug 1817466 - Use new channel and certificate-alias names in push-apk
  taskcluster/ci/push-apk/kind.yml
Labels: 🛬 needs landing

#1346 Bug 1823794 - Disable re-engagement notification by default
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#1359 Bug 1823860 - Update crash monitoring docs to create a bugzilla report from Socorro
  fenix/docs/Crash-Monitoring.md
Labels: 🛬 needs landing

#1282 Bug 1822823 - Refactor settingsGeneralItemsTests UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: 🛬 needs landing

#1276 Bug 1822750 - Add option to open default browser help page in custom tab
  fenix/app/src/main/java/org/mozilla/fenix/ext/Activity.kt
Labels: 🛬 needs landing

#1340 Bug 1823707 - Refactor settingsAdvancedItemsTest UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeveloperToolsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHTTPSOnlyModeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: 🛬 needs landing

#1367 Bug 1821206 - Implement composified tab list click listeners
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
Labels: 🛬 needs landing, approved

#1341 Bug 1823492 Add timing metric for Adjust Attribution Listener
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
Labels: 🛬 needs landing

#1368 Bug 1824027 - Revert speculative fix for Onboarding RTL crash
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/UpgradeOnboarding.kt
Labels: 🛬 needs landing, approved

#1362 Bug 1823929 - New ETP UI tests
  fenix/app/src/androidTest/assets/pages/cross-site-cookies.html
  fenix/app/src/androidTest/assets/pages/trackingPage.html
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionExceptionsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionRobot.kt
Labels: 🛬 needs landing

#916 Bug 1815628 - Refactored Navigation Graph to show `Saved Login Page` after new Credentials added.
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/controller/SavedLoginsStorageController.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
Labels: 🛬 needs landing

#1397 Bug 1821722 - Update juno onboarding strings
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#907 Bug 1799622 - A password deleted in the password manager, is still visible in the list afterwards
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
Labels: 🛬 needs landing

#1394 Bug 1824341 - Use `browser_specific_settings` instead of `applications` in built-in manifests
  android-components/components/browser/icons/src/main/assets/extensions/browser-icons/manifest.template.json
  android-components/components/feature/accounts/src/main/assets/extensions/fxawebchannel/manifest.template.json
  android-components/components/feature/readerview/src/main/assets/extensions/readerview/manifest.template.json
  android-components/components/feature/search/src/main/assets/extensions/ads/manifest.template.json
  android-components/components/feature/search/src/main/assets/extensions/search/manifest.template.json
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json
  android-components/samples/browser/src/main/assets/extensions/borderify/manifest.template.json
  android-components/samples/browser/src/main/assets/extensions/test/manifest.template.json
Labels: 🛬 needs landing

#1355 Bug 1823794 - Disable re-engagement notification by default
  fenix/nimbus.fml.yaml
Labels: 🛬 needs landing

#77 Bug 1796340 - Consume login and credit card select prompts on dismiss
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardPicker.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/LoginPicker.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardPickerTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/login/LoginPickerTest.kt
Labels: 🛬 needs landing

#1373 Bug 1824052 - Fix compatibility warning by setting jvmTarget to 11 for KotlinCompile task
  android-components/components/tooling/lint/build.gradle
Labels: 🛬 needs landing

#1374 Bug 1815013 - Port over the Tabs Tray FAB
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFab.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/res/layout/component_tabstray3_fab.xml
Labels: 🛬 needs landing, approved

#1378 Bug 1824134 - Add support for clickable linkified text in OnboardingPage
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageState.kt
Labels: 🛬 needs landing

#1400 Bug 1824359 - Support retrieving expired messages
  fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/MessageNotificationWorker.kt
  fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingController.kt
  fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  fenix/app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
Labels: 🛬 needs landing, approved

#1435 Bug 1824869 - Add PrivateBrowsing[Interactor|Controller] for handling private browsing mode
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/privatebrowsing/controller/PrivateBrowsingController.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/privatebrowsing/interactor/PrivateBrowsingInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/privatebrowsing/DefaultPrivateBrowsingControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractorTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#1420 Bug 1823085 - NoSuchElementException fix
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
Labels: 🛬 needs landing (squash)

#1363 Bug 1822620 -A possible fix for NullPointerException.
  fenix/app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
Labels: 🛬 needs landing

#1460 Bug 1825015 - Remove dreamlte in legacy test configuration
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
Labels: 🛬 needs landing

#1446 Update Fenix initial_experiments.json based on the current first-run experiments in experimenter
  fenix/app/src/main/res/raw/initial_experiments.json
Labels: 🛬 needs landing, approved
