Repository mozilla-mobile/firefox-android, pull requests merged in 2023-04, with the labels that each got.

#1441 Bug 1804115 Catch errors thrown in the error reporter
  fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
Labels: 🛬 needs landing, approved

#1521 Bug 1826091 - Enable Pull to Refresh in release
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
Labels: 🛬 needs landing

#1501 Bug 1824434 - Improve visibility of license info
  android-components/.buildconfig.yml
  android-components/components/support/license/README.md
  android-components/components/support/license/build.gradle
  android-components/components/support/license/proguard-rules.pro
  android-components/components/support/license/src/main/AndroidManifest.xml
  android-components/components/support/license/src/main/java/mozilla/components/support/license/LibrariesListFragment.kt
  android-components/components/support/license/src/main/res/layout/fragment_libraries_list.xml
  android-components/components/support/license/src/test/resources/robolectric.properties
  docs/changelog.md
  focus-android/.buildconfig.yml
  focus-android/app/build.gradle
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/MozillaSupportPagesTest.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsMozillaMenuRobot.kt
  focus-android/app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  focus-android/app/src/main/java/org/mozilla/focus/settings/AboutLibrariesFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  focus-android/app/src/main/java/org/mozilla/focus/state/AppState.kt
  focus-android/app/src/main/res/layout/fragment_about_libraries.xml
  focus-android/app/src/main/res/values/preference_keys.xml
  focus-android/app/src/main/res/values/strings.xml
  focus-android/app/src/main/res/xml/mozilla_settings.xml
  focus-android/build.gradle
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#1444 Bug 1814993 - Add inactive tabs to the composified `TabsTray`
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/inactivetabs/InactiveTabs.kt
Labels: 🛬 needs landing, approved

#1527 Bug 1826176 - Syncronize Focus jvmargs with AC.
  focus-android/gradle.properties
Labels: 🛬 needs landing

#1520 Bug 1825549 Disallow messages with blank text fields
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
Labels: 🛬 needs landing

#1486 Bug 1825649 - Introduce shared-settings.gradle to allow reusing build logic.
  android-components/build.gradle
  android-components/settings.gradle
  fenix/build.gradle
  fenix/settings.gradle
  focus-android/build.gradle
  focus-android/settings.gradle
  shared-settings.gradle
Labels: 🛬 needs landing

#1499 Bug 1825306 - Updated message notification worker notification click to send 'clicked' telemetry
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingController.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingControllerTest.kt
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/messaging/MessageNotificationWorker.kt
Labels: 🛬 needs landing, approved

#1087 Bug 1813418 - Normalize search widget previews and microphone icon
  fenix/app/src/beta/res/drawable-hdpi/fenix_search_widget.png
  fenix/app/src/main/res/drawable-hdpi/fenix_search_widget.png
  fenix/app/src/main/res/drawable/ic_microphone_widget.xml
  fenix/app/src/main/res/layout/search_widget_large.xml
  fenix/app/src/main/res/layout/search_widget_medium.xml
  fenix/app/src/main/res/layout/search_widget_small.xml
  fenix/app/src/nightly/res/drawable-hdpi/fenix_search_widget.png
  fenix/app/src/release/res/drawable-hdpi/fenix_search_widget.png
Labels: 🛬 needs landing, approved

#1538 Bug 1825649 - Fix A-C nightly builds after adding shared settings.gradle
  android-components/settings.gradle
  shared-settings.gradle
Labels: 🛬 needs landing

#1494 Bug 1825503 - update taskgraph and dependencies in decision and action tasks
  .taskcluster.yml
  taskcluster/requirements.txt
Labels: 🛬 needs landing

#1539 Bug 1826370 - reduce_cookie_banner_unsupported_site_request_submitted - comment updated
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#1379 Bug 1821778 - Add card for fullscreen research surface
  fenix/app/src/main/java/org/mozilla/fenix/experiments/ResearchSurfaceDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/experiments/view/ResearchSurfaceSurvey.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/values/styles.xml
Labels: 🛬 needs landing, approved

#1382 Bug 1819153 - Add nightly-firebase build type in nightly tasks + cleanup
  taskcluster/android_taskgraph/target_tasks.py
  taskcluster/ci/startup-test/kind.yml
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing

#1528 Bug 1814991 - Implement Tabs Tray single select banner UI
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
Labels: 🛬 needs landing, approved

#1540 Bug 1826371 - Update Unified Search to depend on experiment flag instead of feature flag
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: 🛬 needs landing

#1549 Bug 1825279 - Remove dreamlte device in legacy test configuration
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
Labels: 🛬 needs landing

#1522 Bug 1826094 - Add dialog verification to existing delete browsing UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataRobot.kt
Labels: 🛬 needs landing

#1534 Bug 1819439 - Add logic to dismiss tabs tray when user taps outside
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
Labels: 🛬 needs landing, approved

#1478 Bug 1816567 - Create a top-level DropdownMenu composable
  fenix/app/src/main/java/org/mozilla/fenix/compose/DropdownMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/collections/Collection.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/collections/CollectionMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/collections/CollectionViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
Labels: 🛬 needs landing

#1544 Bug 1826378 - Update Sentry to version 6.17.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#1551 Bug 1826387 - Enable juno onboarding nimbus flag in nightly
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing

#1565 Bug 1826466 – fix unified search icons visibility
  fenix/app/src/main/java/org/mozilla/fenix/home/toolbar/SearchSelectorBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarAction.kt
Labels: 🛬 needs landing

#1343 Bug 1820211 - Adds `tabKilled` event to track when a tab was killed with form data.
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/SessionPrioritizationMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/recover/RecoverableTab.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/SessionPrioritizationMiddlewareTest.kt
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/lifecycle/StoreLifecycleObserver.kt
  fenix/app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/lifecycle/StoreLifecycleObserverTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
Labels: 🛬 needs landing (squash), approved

#1566 Bug 1821475 - Show research surface when survey message is available
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/experiments/view/ResearchSurfaceSurvey.kt
Labels: 🛬 needs landing, approved

#1497 Bug 1825786 - Refactor and create new UI tests related to logins search
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
Labels: 🛬 needs landing

#1563 Bug 1826568 - Minor changes related to system notification UI smoke tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: 🛬 needs landing

#1554 Bug 1821726 - Add juno onboarding telemetry
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingTelemetryRecorder.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingScreen.kt
Labels: 🛬 needs landing, approved

#1558 Bug 1824928 - Fix and re-enable open links in apps UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: 🛬 needs landing

#1571 Bug 1814138 - Fix nimbus branch item check mark visibility
  android-components/components/service/nimbus/src/main/res/layout/mozac_service_nimbus_branch_item.xml
Labels: 🛬 needs landing

#1574 Bug 1825130 - Mark extension as disabled/enabled when it gets disabled/enabled by Gecko(View)
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🛬 needs landing, approved

#1429 Bug 1824818 - Update manifest version strings to respect the simple versioning format
  shared-settings.gradle
Labels: 🛬 needs landing

#1585 Bug 1826874 - Disable juno onboarding on nightly and developer
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing

#1580 Bug 1826880 - Filter next message with MessageSurfaceId if current message is control
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
Labels: 🛬 needs landing, approved

#1595 Bug 1827119 - Disable notification pre permission prompt by default
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#1575 Bug 1810404 - Fix flaky scanButtonAllowPermissionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: 🛬 needs landing

#1524 Bug 1825008 - Create a storage for submitted cookie banner site reports.
  android-components/components/browser/engine-gecko/build.gradle
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorage.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/cookiebanners/ReportSiteDomainsRepository.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorageTest.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/cookiebanners/ReportSiteDomainsRepositoryTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/cookiehandling/CookieBannersStorage.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/build.gradle
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerDetailsController.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannersStorageExt.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/DefaultCookieBannerDetailsControllerTest.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/app/build.gradle
  focus-android/app/src/main/java/org/mozilla/focus/components/EngineProvider.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerreducer/CookieBannerReducerMiddleware.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#1603 Bug 1827217 - Start the Nightly 114 development cycle
  android-components/components/browser/errorpages/src/main/res/values/strings.xml
  android-components/components/feature/prompts/src/main/res/values/strings.xml
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#1605 Update GeckoView (Nightly) to 114.0.20230410150526.
  android-components/plugins/dependencies/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#821 Bug 1802584 - Announce "Find in page" edit box when using Talkback
  android-components/components/feature/findinpage/src/main/res/layout/mozac_feature_findinpage_view.xml
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/FindInPageIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/InflationAwareFeature.kt
  fenix/app/src/main/res/layout/fragment_browser.xml
  fenix/app/src/main/res/layout/stub_find_in_page.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/InflationAwareFeatureTest.kt
Labels: 🛬 needs landing, approved

#1612 Bug 1827381 - Remove running condition for UI tests related to the PDF reader feature
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt
Labels: 🛬 needs landing

#1629 Bug 1805410 - Ship v113.0.0 of the WebCompat System Addon.
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1819678-elal.com-unsupported-banner.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1819678-nppes.cms.hhs.gov-unsupported-banner.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1448747-fastclick-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1724764-window-print.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1769762-tiktok.com-plugins-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1800131-www.almosafer.com-undisable-date-fields.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1818818-fastclick-legacy-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1819678-free4talk.com-window-chrome-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#1050 Bug 1814192 - Set the delete menu item to inactive when there is no browsing data
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
Labels: 🛬 needs landing

#1627 Bug 1827607 - Enable speedometer 2 test on firefox-android.
  taskcluster/ci/browsertime/kind.yml
Labels: 🛬 needs landing (squash)

#1646 Bug 1828094 - Mark extension as uninstalled when it gets uninstalled by Gecko(View)
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🛬 needs landing

#1599 Bug 1825799 - Make MozillaOnlineHomeActivity final by default
  fenix/app/src/main/java/org/mozilla/fenix/MozillaOnlineHomeActivity.kt
Labels: 🛬 needs landing

#1579 Bug 1826882 - Open `TabsTray` in the private page when opening it from an active private tab
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing, approved

#1581 Bug 1821425 - Add the logic to show the selected tab UI and the multiselection tab UI
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
Labels: 🛬 needs landing, approved

#1674 Bug 1827686 - Add telemetry for user updating Default Search Engine
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/ext/SearchEngine.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
Labels: 🛬 needs landing

#1615 Bug 1827406 - New connection error message UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing

#1687 Bug 1814992 - Add `SyncedTabsList` to `TabsTray`
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: 🛬 needs landing, approved

#1634 Bug 1827844 - Adds file upload permission smoke test
  fenix/app/src/androidTest/assets/pages/htmlControls.html
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing

#1701 Bug 1828947 - Update notification email for permanent telemetry collections
  android-components/components/service/nimbus/metrics.yaml
  fenix/app/metrics.yaml
Labels: 🛬 needs landing, approved

#1682 Bug 1827631 - Use debugImplementation for compose tooling
  android-components/components/compose/awesomebar/build.gradle
  android-components/components/compose/browser-toolbar/build.gradle
  android-components/components/compose/cfr/build.gradle
  android-components/components/compose/engine/build.gradle
  android-components/components/compose/tabstray/build.gradle
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/build.gradle
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing

#1699 Bug 1826560 - consistently sign android-test APKs with the dep key
  taskcluster/android_taskgraph/transforms/signing_apk.py
Labels: 🛬 needs landing

#1703 Bug 1805651 - Update taskgraph to 5.1.0 and use index-path-regexes
  taskcluster/android_taskgraph/__init__.py
  taskcluster/android_taskgraph/morph.py
  taskcluster/ci/config.yml
  taskcluster/requirements.in
  taskcluster/requirements.txt
Labels: 🛬 needs landing

#1702 Bug 1822193 - Scroll to the active tab when opening the Tabs Tray
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
Labels: 🛬 needs landing, approved

#1572 Bug 1810197 - Fix condition of changeExtension
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
Labels: 🛬 needs landing

#1700 Bug 1828936 - Update first-session ping information
  fenix/app/pings.yaml
Labels: 🛬 needs landing

#1697 Bug 1807270 - Re-enable remaining closing open tabs related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Labels: 🛬 needs landing

#1711 Bug 1807270 - Re-enable selectTabOnLongTapTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: 🛬 needs landing

#1590 Bug 1816522 - Add multi selection banner UI
  fenix/app/src/main/java/org/mozilla/fenix/compose/DropdownMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: 🛬 needs landing

#1724 Bug 1807270 - Re-enable open tabs thumbnail check in UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: 🛬 needs landing

#1562 Bug 1819196 - Plug-in tabs tray fab business logic
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFab.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: 🛬 needs landing, approved

#810 Bug 1795459 - Move private browsing notification create and refresh off main thread
  android-components/components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationService.kt
  android-components/components/feature/privatemode/src/test/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationServiceTest.kt
Labels: 🛬 needs landing, approved

#1761 Bug 1829682 - Fix onboarding vertical scroll
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingScreen.kt
Labels: 🛬 needs landing, approved

#1638 Bug 1827937 - Update some application provided search engines to use https by default rather than http.
  android-components/components/feature/search/src/main/assets/searchplugins/azerdict.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ceneje.xml
  android-components/components/feature/search/src/main/assets/searchplugins/danawa-kr.xml
  android-components/components/feature/search/src/main/assets/searchplugins/faclair-beag.xml
  android-components/components/feature/search/src/main/assets/searchplugins/mapy-cz.xml
  android-components/components/feature/search/src/main/assets/searchplugins/mercadolibre-ar.xml
  android-components/components/feature/search/src/main/assets/searchplugins/mercadolibre-cl.xml
  android-components/components/feature/search/src/main/assets/searchplugins/mercadolibre-mx.xml
  android-components/components/feature/search/src/main/assets/searchplugins/odpiralni.xml
  android-components/components/feature/search/src/main/assets/searchplugins/salidzinilv.xml
  android-components/components/feature/search/src/main/assets/searchplugins/skroutz.xml
  android-components/components/feature/search/src/main/assets/searchplugins/sztaki-en-hu.xml
Labels: 🛬 needs landing

#1715 Bug 1796305 - Address lint unused resources
  android-components/components/browser/errorpages/build.gradle
  android-components/components/feature/addons/build.gradle
  android-components/components/ui/icons/build.gradle
Labels: 🛬 needs landing

#1325 Bug 1823462 - New application-services release system
  .github/workflows/ac-update-geckoview.yml
  android-components/build.gradle
  android-components/components/service/nimbus/build.gradle
  android-components/components/support/base/build.gradle
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  android-components/plugins/dependencies/src/main/java/ExtraRepositories.kt
  docs/contribute/release_checklist.md
  fenix/build.gradle
  focus-android/build.gradle
Labels: 🛬 needs landing

#1588 Bug 1825429 - Tapping on empty search result should cancel search mode.
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: 🛬 needs landing, approved

#1754 Bug 1829619 - Fix external ActivityNotFoundException for default browser settings
  fenix/app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessorTest.kt
Labels: 🛬 needs landing

#1751 Bug 1829591 - Replace StatusBarUtils.java in Focus with AC StatusBarUtils.
  focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/FirstrunFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/settings/BaseComposeFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/StatusBarUtils.java
Labels: 🛬 needs landing

#1726 Bug 1829359 - Refactor clickPageObject methods in UI tests and other repetitive methods
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddToHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextualHintsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHTTPSOnlyModeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSitePermissionsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TextSelectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/WebControlsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/PwaRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt
Labels: 🛬 needs landing

#1774 Bug 1829864 - Revert "Bug 1805651 - Update taskgraph to 5.1.0 and use index-path-regexes"
  taskcluster/android_taskgraph/__init__.py
  taskcluster/android_taskgraph/morph.py
  taskcluster/ci/config.yml
  taskcluster/requirements.in
  taskcluster/requirements.txt
Labels: 🛬 needs landing

#1770 Bug 1829228 - Update Kotlin to 1.8.20 and Compose Compiler to 1.4.6
  android-components/components/feature/tab-collections/src/test/java/mozilla/components/feature/tab/collections/ext/TabsUseCasesKtTest.kt
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ext/Bundle.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#1769 Bug 1829795 - Resize onboarding page image based on screen height
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
Labels: 🛬 needs landing

#1785 Bug 1830030 - disable failing deleteCollectionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
Labels: 🛬 needs landing

#1729 Bug 1829301 - Make fenix onboarding singleton
  fenix/app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
Labels: 🛬 needs landing

#1541 Bug 1822119 - Store new UUID in shared prefs and send in metrics ping
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: 🛬 needs landing (squash)

#1776 Bug 1829937 - Remove "Always" as an option for app links in private browsing
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuOpenLinksInAppsRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/OpenLinksInAppsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: 🛬 needs landing

#1704 Bug 1826457 - Update Compose version to 1.4.2 and Lifecycle version to 2.6.1
  android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopupFullscreenLayout.kt
  android-components/components/compose/cfr/src/test/java/mozilla/components/compose/cfr/CFRPopupFullscreenLayoutTest.kt
  android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/toolbar/TabCounterToolbarButtonTest.kt
  android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/toolbar/TabsToolbarFeatureTest.kt
  android-components/components/lib/state/src/test/java/mozilla/components/lib/state/ext/StoreExtensionsKtTest.kt
  android-components/components/support/base/src/test/java/mozilla/components/support/base/feature/ViewBoundFeatureWrapperTest.kt
  android-components/components/support/base/src/test/java/mozilla/components/support/base/observer/ObserverRegistryTest.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  android-components/samples/firefox-accounts/src/main/java/org/mozilla/samples/fxa/MainActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ComposeViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeAbstractTabViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/view/LifecycleViewProvider.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/OpenInAppOnboardingObserverTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/OnSharedPreferenceChangeListenerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragmentTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shortcut/PwaOnboardingObserverTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragmentTest.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
  focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  focus-android/app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetUtils.kt
  focus-android/app/src/main/java/org/mozilla/focus/settings/privacy/TrackingProtectionPanel.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1789 Bug 1830082 - Avoid UninitializedPropertyAccessException when MainActivity is destroyed
  focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Labels: 🛬 needs landing

#1677 Bug 1828551 - Add documentation diagrams for AutoPushFeature
  android-components/components/feature/push/README.md
  android-components/components/feature/push/assets/autopush-sequence-diagram.png
  android-components/components/lib/push-firebase/README.md
Labels: 🛬 needs landing

#1775 Bug 1825413 - Add Telemetry for Pull to Refresh
  android-components/components/feature/session/src/main/java/mozilla/components/feature/session/SwipeRefreshFeature.kt
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt
Labels: 🛬 needs landing

#1809 Bug 1810197 - Revert "Fix condition of changeExtension".
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
Labels: 🛬 needs landing

#1824 Bug 1830312 - Disable failing allowAudioVideoAutoplayPermissionTest UI test
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SitePermissionsTest.kt
Labels: 🛬 needs landing

#1830 Bug 1814032 - disable failing verifyAddressAutofillSelectionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
Labels: 🛬 needs landing

#1833 Bug 1830574 - Remove duplicate DeviceType types
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/RemoteTabsStorageTest.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceSettingsCache.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Types.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaDeviceConstellationTest.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaDeviceSettingsCacheTest.kt
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
Labels: 🛬 needs landing
