Repository mozilla-mobile/firefox-android, pull requests merged in 2023-07, with the labels that each got.

#2681 Bug 1840896 - Remove `rememberSaveable` since bitmaps are not serializable
  fenix/app/src/main/java/org/mozilla/fenix/compose/ThumbnailImage.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#2685 Bug 1841361 - Allow advance user to enable Gecko logs
  fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/preferences.xml
Labels: 🛬 needs landing, approved

#1673 Bug 1826513 - Expose FTL JUnit results in live log
  fenix/automation/taskcluster/androidTest/parse-ui-test-fromfile.py
  fenix/automation/taskcluster/androidTest/ui-test.sh
  focus-android/automation/taskcluster/androidTest/parse-ui-test-fromfile.py
  focus-android/automation/taskcluster/androidTest/ui-test.sh
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing, approved, python

#2649 Bug 1840099 - Add bottom sheet container for shopping experience
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/BottomSheetHandle.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckViewModel.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContent.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/static_strings.xml
Labels: 🛬 needs landing, approved

#2707 Bug 1841651 - Start the Nightly 117 development cycle
  android-components/components/support/ktx/src/main/res/values/strings.xml
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#2664 Bug 1836971 - Respect never setting in open links in apps
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Labels: 🛬 needs landing, approved

#2616 Bug 1840315 – added telemetry to the splash screen data fetching
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: 🛬 needs landing, approved

#2716 Bug 1841676 - Fix NavigationToolbarTest.swipeToSwitchTabInRTLTest failure
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckViewModel.kt
  fenix/app/src/main/res/drawable/ic_shopping_cart_selected.xml
Labels: 🛬 needs landing, approved

#2668 Bug 1841171 - Convert `NavigationToolbarTest` to support the Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeNavigationToolbarTest.kt
Labels: 🛬 needs landing, approved

#2717 Bug 1826470 – fixed an edge case when cached values affected unified search feature
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
Labels: 🛬 needs landing, approved

#2669 Bug 1841175 - Convert `MenuScreenShotTest` to support the Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/screenshots/ComposeMenuScreenShotTest.kt
Labels: 🛬 needs landing, approved

#2680 Bug 1841274 - Add Param to Nimbus SearchExtraParams
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/middleware/SearchMiddleware.kt
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchEngineReader.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/storage/ParseSearchPluginsTest.kt
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: 🛬 needs landing, approved

#2670 Bug 1841177 - Convert `ContextMenusTest` to support the Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt
Labels: 🛬 needs landing, approved

#2723 Bug 1836360 - Remove trailing space from mozac_feature_prompts_identity_credentials_privacy_policy_description.
  android-components/components/feature/prompts/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#863 Bug 1813787 - Hide `Add to shortcuts` menu entry if Shortcuts are disabled on the Homepage
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: 🛬 needs landing, approved

#2666 Bug 1841168 - Convert `MediaNotificationTest` to support Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeMediaNotificationTest.kt
Labels: 🛬 needs landing, approved

#2644 Bug 1840561 - Fix and refactor verifyLoginWithoutPasswordCanNotBeSavedTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
Labels: 🛬 needs landing, approved

#2677 Bug 1837986 - add the right color and alignment to the number of the normal tabs in compose tabs tray
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
Labels: 🛬 needs landing, approved

#2718 Bug 1835689 - don't include cached tasks in existing_tasks for release promotion
  taskcluster/android_taskgraph/release_promotion.py
  taskcluster/ci/config.yml
Labels: 🛬 needs landing, approved

#1963 Bug 1832097 - don't try and decrypt empty credit-card numbers.
  android-components/components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/AutofillCrypto.kt
  android-components/components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/AutofillCryptoTest.kt
Labels: 🛬 needs landing, approved

#2702 Bug 1841361 - Add extra logs to the "Setting enable Gecko" logs.
  fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
Labels: 🛬 needs landing, approved

#2737 Bug 1841978 - Update DuckDuckGo icon to match new branding.
  android-components/components/feature/search/src/main/assets/searchplugins/ddg.xml
Labels: 🛬 needs landing, approved

#2667 Bug 1839977 - Update architecture overview documentation.
  fenix/docs/architecture-overview.md
Labels: 🛬 needs landing, approved

#2721 Bug 1841493 - Update search settings tests with new unified search UI
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: 🛬 needs landing, approved

#2736 Bug 1840995 - Fix flaky closePrivateTabTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#2753 Bug 1842164 - don't optimize away tasks whose configuration changes
  taskcluster/android_taskgraph/transforms/gradle_optimization.py
Labels: 🛬 needs landing, approved

#2735 Bug 1837158 - Media playback should be stopped when the app is destroyed.
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  android-components/components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: 🛬 needs landing, approved

#2732 Bug 1841956 - New copy login credentials UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
Labels: 🛬 needs landing, approved

#2658 Bug 1841073 - Add missing conditions when verifying link related context menu options in UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing, approved

#2705 Bug 1841542 - Update Gradle to version 7.6.2
  android-components/gradle/wrapper/gradle-wrapper.properties
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/gradle/wrapper/gradle-wrapper.properties
  focus-android/gradle/wrapper/gradle-wrapper.properties
Labels: 🛬 needs landing, approved

#2673 Bug 1841155 - Update LeakCanary to version 2.12
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  focus-android/app/build.gradle
  focus-android/plugins/focusdependencies/src/main/java/FocusDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2659 Bug 1841081 - Update Kotlin Coroutines to version 1.7.2
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  focus-android/app/build.gradle
  focus-android/plugins/focusdependencies/src/main/java/FocusDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2708 Bug 1840095 - Add ReviewGrade UI component
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewGrade.kt
  fenix/app/src/main/res/values/static_strings.xml
Labels: 🛬 needs landing, approved

#2679 Bug 1826467 - Searching for words with spaces matches bookmarks and history entries in Unified Search, but not open tabs
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
Labels: 🛬 needs landing, approved

#2752 Bug 1813521 - Fix flaky pauseResumeCancelDownloadTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: 🛬 needs landing, approved

#2758 Bug 1842296 - Update Mockito to version 5.4.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2739 Bug 1828454 - Add app links do not open cache in memory to avoid prompting user for the same app
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Labels: 🛬 needs landing, approved

#2725 Bug 1841153 - new event telemetry for private tab open
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, approved

#2792 Bug 1807268 - Disable failing toggleSearchHistoryTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: 🛬 needs landing, approved

#2750 Bug 1840097 - Add StarRating UI component
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/StarRating.kt
  fenix/app/src/main/res/drawable/ic_star_half.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ui/StarRatingKtTest.kt
Labels: 🛬 needs landing, approved

#2797 Bug 1841006 - Disables Focus UI test 'verifySelectTextTest'
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/WebControlsTest.kt
Labels: 🛬 needs landing, approved

#2799 Bug 1842719 - Disables "Report site issue" button check in Focus UI test
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/ThreeDotMainMenuTest.kt
Labels: 🛬 needs landing, approved

#2804 Bug 1839239 - Add crash bread crumbs for dialogs.
  android-components/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFeature.kt
  android-components/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/facts/ContextMenuFacts.kt
  android-components/components/feature/downloads/README.md
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/facts/DownloadsFacts.kt
  android-components/components/feature/prompts/README.md
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/facts/PromptFacts.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/android/FenixDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  fenix/app/src/main/java/org/mozilla/fenix/crashes/CrashFactCollector.kt
  fenix/app/src/main/java/org/mozilla/fenix/downloads/StartDownloadDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/downloads/StartDownloadDialogTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/recentvisits/view/RecentBookmarksViewHolderTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
Labels: 🛬 needs landing, approved

#2814 Bug 1843062 - fix focus startup-test artifact-reference
  taskcluster/ci/startup-test/kind.yml
Labels: 🛬 needs landing, approved

#2801 Bug 1842886 - update the webcompat-reporter feature to un-break it
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/background.js
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/aboutConfigPrefs.js
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/actors/tabExtrasActor.jsm
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/browserInfo.js
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/browserInfo.json
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/tabExtras.js
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/tabExtras.json
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json
Labels: 🛬 needs landing, approved

#2724 Bug 1835816 - Do not try to redirect intent even if unsupported by engine
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing, approved

#2786 Bug 1815001 - Enable the Tabs Tray to Compose rewrite in Nightly
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: 🛬 needs landing, approved

#2818 Bug 1843121 - fix destination path for focus nightly apks on archive.mozilla.org
  taskcluster/android_taskgraph/util/scriptworker.py
Labels: 🛬 needs landing, approved

#2815 Bug 1843089 - stop overriding artifact name for focus test apk
  taskcluster/ci/build-apk/kind.yml
  taskcluster/ci/startup-test/kind.yml
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing, approved

#2819 Bug 1842886 - bump the version of the webcompat-reporter addon up
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json
Labels: 🛬 needs landing, approved

#2798 Bug 1837517 - Additional Print Telmetry and Nimbus setup
  fenix/app/.experimenter.yaml
  fenix/app/metrics.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/share/SaveToPDFMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
Labels: 🛬 needs landing, approved

#2808 Bug 1842904 - Remove unused GitHubPlugin and GitHubClient
  android-components/build.gradle
  android-components/buildSrc/src/main/java/Extentions.kt
  android-components/buildSrc/src/main/java/GitHubClient.kt
  android-components/buildSrc/src/main/java/GitHubPlugin.kt
Labels: 🛬 needs landing, approved

#2803 Bug 1825116 - Reformat some python files with black and avoid 'bare except' ruff warnings
  android-components/automation/taskcluster/androidTest/parse-ui-test.py
  android-components/tools/list_compatible_dependency_versions.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/syncintegration/gradlewbuild.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/syncintegration/tps.py
  fenix/automation/taskcluster/androidTest/parse-ui-test.py
  fenix/tools/data_renewal_generate.py
  fenix/tools/data_renewal_request.py
  fenix/tools/setup-startup-profiling.py
  focus-android/tools/data_renewal_generate.py
  focus-android/tools/data_renewal_request.py
Labels: 🛬 needs landing, approved

#2817 Bug 1842916 - Expose WebExtensionInstallException.UserCancelled.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionException.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoWebExtensionExceptionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
Labels: 🛬 needs landing, approved

#2824 Bug 1843243 - Mark nimbus onboarding strings as unused
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#2827 Bug 1843245 - Mark unused onboarding strings for removal
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#2826 Bug 1842719 - Enable "Report site issue" button check in Focus UI test
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/ThreeDotMainMenuTest.kt
Labels: 🛬 needs landing, approved

#2825 Bug 1842768 - Enable 'Report site issue' related tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MainMenuTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing, approved

#2755 Bug 1842177 - Update search engines tests with new unified search UI
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: 🛬 needs landing, approved

#2830 Bug 1838317 - Autocomplete url suggestion regardless of letter case
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
Labels: 🛬 needs landing, approved

#2810 Bug 1842179 - Enable Unified Search in all UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TextSelectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#2783 Bug 1842257 - Convert `SettingsDeleteBrowsingDataTest` to support Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataTest.kt
Labels: 🛬 needs landing, approved

#2782 Bug 1842095 - Convert `SettingsDeleteBrowsingDataOnQuitTest` to support Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt
Labels: 🛬 needs landing, approved

#2841 Bug 1842082 - Normal home screen view count telemetry
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, approved

#2851 Bug 1843610 - Add telemetry for deferred deep link test
  fenix/app/metrics.yaml
  fenix/app/src/main/AndroidManifest.xml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessor.kt
Labels: 🛬 needs landing, approved

#2776 Bug 1841639 - Add common Switch composable
  fenix/app/src/main/java/org/mozilla/fenix/compose/SwitchWithLabel.kt
Labels: 🛬 needs landing, approved

#2778 Bug 1843008 - New custom tabs related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
Labels: 🛬 needs landing, approved

#2855 Bug 1842890 - Add splash screen animation
  fenix/app/src/beta/res/drawable/animated_splash_screen.xml
  fenix/app/src/debug/res/drawable/animated_splash_screen.xml
  fenix/app/src/main/res/drawable-v23/splash_screen.xml
  fenix/app/src/main/res/drawable-v24/splash_screen.xml
  fenix/app/src/main/res/values-night/styles.xml
  fenix/app/src/main/res/values/dimens.xml
  fenix/app/src/main/res/values/styles.xml
  fenix/app/src/nightly/res/drawable/animated_splash_screen.xml
  fenix/app/src/release/res/drawable/animated_splash_screen.xml
Labels: 🛬 needs landing, approved

#2852 Bug 1842258 - Convert `SearchTest` to support the Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/LibrarySubMenusMultipleSelectionToolbarRobot.kt
Labels: 🛬 needs landing, approved

#2865 Bug 1843811 - Update Protobuf Gradle Plugin to version 0.9.4
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2854 Bug 1843157 - Correct link to Mobile Test Engineering
  android-components/automation/taskcluster/androidTest/parse-ui-test.py
  fenix/automation/taskcluster/androidTest/parse-ui-test.py
  focus-android/automation/taskcluster/androidTest/parse-ui-test.py
Labels: 🛬 needs landing (squash), approved

#2809 Bug 1840332 - Create ReviewQualityCheckState
  fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewGrade.kt
Labels: 🛬 needs landing, approved

#2875 Bug 1843864 - Fenix: Add tests for unified search bar placeholder
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: 🛬 needs landing, approved

#2581 Bug 1839250 - Avoid crash caused by OOM while saving a just-closed tab into storage
  android-components/components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorage.kt
  android-components/components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorageTest.kt
Labels: 🛬 needs landing, approved

#2895 Bug 1842890 - Add splash screen animation
  fenix/app/src/beta/res/drawable/animated_splash_screen.xml
  fenix/app/src/debug/res/drawable/animated_splash_screen.xml
  fenix/app/src/main/res/drawable-v23/splash_screen.xml
  fenix/app/src/main/res/drawable-v24/splash_screen.xml
  fenix/app/src/main/res/drawable/animated_splash_screen.xml
  fenix/app/src/main/res/values-night/styles.xml
  fenix/app/src/main/res/values/styles.xml
  fenix/app/src/nightly/res/drawable/animated_splash_screen.xml
  fenix/app/src/release/res/drawable/animated_splash_screen.xml
Labels: 🛬 needs landing, approved

#1586 Bug 1826933 - Avoid memory leaks in NotificationsDelegate
  android-components/components/support/base/src/main/java/mozilla/components/support/base/android/NotificationsDelegate.kt
  android-components/components/support/base/src/test/java/mozilla/components/support/base/android/NotificationsDelegateTest.kt
Labels: 🛬 needs landing, approved

#2894 Bug 1840894 - Adjust Print Error UI to use Snackbars
  fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/share/SaveToPDFMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#2917 Bug 1844386 - Update splash screen animation
  fenix/app/src/beta/res/drawable/animated_splash_screen.xml
  fenix/app/src/debug/res/drawable/animated_splash_screen.xml
  fenix/app/src/main/res/drawable/animated_splash_screen.xml
  fenix/app/src/main/res/values-night/styles.xml
  fenix/app/src/main/res/values/styles.xml
  fenix/app/src/nightly/res/drawable/animated_splash_screen.xml
  fenix/app/src/release/res/drawable/animated_splash_screen.xml
Labels: 🛬 needs landing, approved

#2927 Bug 1844580 - Disable pocket related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#2884 Bug 1840627 - don't show syncSignIn and accountAuth items in the same time.
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
Labels: 🛬 needs landing, approved

#2899 Bug 1842261 - Convert `SmokeTest` to support the Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#2877 Bug 1842267 - Convert `BookmarksTest` to support the Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeBookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/LibrarySubMenusMultipleSelectionToolbarRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuBookmarksRobot.kt
Labels: 🛬 needs landing, approved

#2928 Bug 1844386 - Only use splash screen animation for SDK 31+
  fenix/app/src/main/res/drawable-v23/splash_screen.xml
  fenix/app/src/main/res/values-v24/styles.xml
  fenix/app/src/main/res/values/styles.xml
Labels: 🛬 needs landing, approved

#2933 Bug 1843610 - Add telemetry for deferred deep link test (backport #2851)
  fenix/app/metrics.yaml
  fenix/app/src/main/AndroidManifest.xml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessor.kt
Labels: 🕵️‍♀️ needs review

#2908 Bug 1844312 - Remove verifyOpenLinkInAppViewInPrivateBrowsingTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Labels: 🛬 needs landing, approved

#2907 Bug 1844330 - Add missing steps to verifyShortcutOptionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing, approved

#2893 Bug 1844305 - Add snackbar verification in UI tests when removing tabs from a collection
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeCollectionTest.kt
Labels: 🛬 needs landing, approved

#2892 Bug 1840994 - Fix systemNotificationCantBeDismissedWhileDownloadingTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing, approved

#2950 Bug 1844804 - If wallpaper has already been changed don't show the Wallpaper prompt
  fenix/app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
Labels: 🛬 needs landing, approved

#2874 Bug 1836351 - Decrease close button size for `TabGridItem`
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
Labels: 🛬 needs landing, approved

#2913 Bug 1840332 - Add ReviewGradeCard
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_chevron_down_20.xml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_chevron_up_20.xml
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckCards.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContent.kt
  fenix/app/src/main/res/values/static_strings.xml
Labels: 🛬 needs landing, approved

#2891 Bug 1843029 - Add preferences for shopping experience
  fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckPreferences.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckPreferencesMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/test/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#2937 Bug 1844667 - Reveal Tabs Tray to Compose rewrite secret setting in Beta and Release
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
Labels: 🛬 needs landing, approved

#2974 Bug 1823492 - Add timespan metric for Adjust attribution
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/FirstSessionPing.kt
Labels: 🛬 needs landing, approved

#2947 Bug 1840721 - We should prefer switching to open tabs vs opening a duplicate tab
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentbookmarks/controller/RecentBookmarksController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/recentbookmarks/DefaultRecentBookmarksControllerTest.kt
Labels: 🛬 needs landing, approved

#2888 Bug 1843244 – fixed notch background color
  fenix/app/src/main/res/values-night-v27/styles.xml
  fenix/app/src/main/res/values-v23/styles.xml
  fenix/app/src/main/res/values-v24/styles.xml
  fenix/app/src/main/res/values-v27/styles.xml
Labels: 🛬 needs landing, approved

#2802 Bug 1841152 - New event telemetry in credential management.
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/facts/LoginAutofillDialogFacts.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/LoginPicker.kt
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/controller/LoginsListController.kt
Labels: 🛬 needs landing, approved

#2952 Bug 1842266 - Convert `HomeScreenTest` to support the Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#2902 Bug 1839697 - Report Java exceptions in the Glean crash pings
  android-components/components/concept/base/src/main/java/mozilla/components/concept/base/crash/Breadcrumb.kt
  android-components/components/lib/crash/docs/metrics.md
  android-components/components/lib/crash/metrics.yaml
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt
  android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/service/GleanCrashReporterServiceTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#2998 Bug 1845520 - Remove smoke test annotation from pwa related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
Labels: 🛬 needs landing, approved

#2889 Bug 1842604 - Telemetry to measure Search results response time
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/SearchUseCases.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/SearchUseCasesTest.kt
  android-components/components/feature/serviceworker/src/test/java/mozilla/components/feature/serviceworker/ServiceWorkerSupportTest.kt
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#2482 Bug 1831352 - Update doc for building Android via the command line.
  docs/shared/android/configure_java.md
Labels: 🛬 needs landing, approved

#2932 Bug 1842269 - Convert `HistoryTest` to support the Tabs Tray rewrite
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHistoryTest.kt
Labels: 🛬 needs landing, approved

#2999 Bug 1845525 - Upgrade Room to latest version.
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/update/UpdateAttemptStorageTest.kt
  android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorageTest.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2985 Bug 1845247 - Updated the ‘Discover more’ Pocket Story background to match the wallpaper colour
  fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLargePlaceholder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: 🛬 needs landing, approved

#2990 Bug 1845104 - Open links in the current app from a CustomTab even when OpenInApp settings is set to 'never'
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing, approved

#2964 Bug 1833666 - Update references to shared docs repo
  docs/contributing.md
  docs/shared/android/CONTRIBUTING.md
  docs/shared/android/CONTRIBUTING_code.md
  docs/shared/android/accessibility_guide.md
  docs/shared/android/ui-testing.md
  docs/shared/git_guide.md
Labels: 🛬 needs landing, approved

#2691 Bug 1807573 - Add field to set custom search engine suggestion URL
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/SaveSearchEngineFragment.kt
  fenix/app/src/main/res/layout/fragment_save_search_engine.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3010 Bug 1845677 - Correctly mock pwaOnboardingObserver in PwaOnboardingObserverTest
  fenix/app/src/test/java/org/mozilla/fenix/shortcut/PwaOnboardingObserverTest.kt
Labels: 🛬 needs landing, approved

#3006 Bug 1845644 - Update Sentry to version 6.27.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2548 Bug 1839366 - Specify if broadcast receivers should be exported or not.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/integration/LocaleSettingUpdater.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/AndroidDownloadManager.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/FetchDownloadManagerTest.kt
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  android-components/components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
  android-components/components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeature.kt
  android-components/components/feature/pwa/src/test/java/mozilla/components/feature/pwa/feature/WebAppSiteControlsFeatureTest.kt
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ext/Context.kt
  fenix/app/src/main/java/org/mozilla/fenix/perf/Performance.kt
Labels: 🛬 needs landing, approved

#2499 Bug 1822514: Save lastSyncedTime preference when sync account is succ…
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
Labels: 🛬 needs landing, approved

#2949 Bug 1845680 - Fenix: unified search UI tests for Default and Manage search engines menus
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MockBrowserDataHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: 🛬 needs landing, approved

#2784 Bug 1842694 - Refactor GithubDetailsTask into a plugin using composite build
  android-components/buildSrc/build.gradle
  android-components/buildSrc/src/main/java/GithubDetailsTask.kt
  android-components/plugins/github/build.gradle
  android-components/plugins/github/settings.gradle
  android-components/plugins/github/src/main/java/GitHubPlugin.kt
  android-components/settings.gradle
  fenix/build.gradle
  fenix/buildSrc/build.gradle
  fenix/settings.gradle
  focus-android/build.gradle
  focus-android/buildSrc/src/main/java/org/mozilla/focus/gradle/tasks/GithubDetailsTask.kt
  focus-android/settings.gradle
  taskcluster/android_taskgraph/transforms/external_gradle_dependencies.py
Labels: 🛬 needs landing, approved

#2743 Bug 1839984 - Update architecture example to use lib-state
  fenix/docs/architecture-overview.md
  fenix/docs/architectureexample/ContactsController.kt
  fenix/docs/architectureexample/ContactsFragment.kt
  fenix/docs/architectureexample/ContactsInteractor.kt
  fenix/docs/architectureexample/ContactsStore.kt
  fenix/docs/architectureexample/ContactsView.kt
  fenix/docs/architectureexample/HistoryFragmentExample.kt
  fenix/docs/architectureexample/HistoryNavigationMiddlewareExample.kt
  fenix/docs/architectureexample/HistoryStorageMiddlewareExample.kt
  fenix/docs/architectureexample/HistoryStoreExample.kt
  fenix/docs/architectureexample/HistoryTelemetryMiddlewareExample.kt
  fenix/docs/architectureexample/ThemeController.kt
  fenix/docs/architectureexample/example-app-wireframe.png
Labels: 🛬 needs landing, approved

#3027 Bug 1805412 - Ship v117.0.0 of of feature-webcompat
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1841991-wilton.com-flexbox-painting-order.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1724764-window-print.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1842437-www.youtube.com-performance-now-precision.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/ua_helpers.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing, approved

#3043 Bug 1845098 - Improve Fenix Gradle builds.
  fenix/gradle.properties
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#2983 Bug 1845260 - Create top level structure for Review Quality Check
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt
  fenix/app/src/main/res/values/static_strings.xml
Labels: 🛬 needs landing, approved

#3045 Bug 1846280: Start the 118 development cycle
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#3041 Bug 1846237 - Add smoke test annotation to testSignInPageWithNoNetworkConnection UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
Labels: 🛬 needs landing, approved

#2978 Bug 1830348 - Use do not intercept cache in app links interceptor
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Labels: 🛬 needs landing, approved

#3047 Switch to Application Services Release
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
Labels: 🛬 needs landing, approved

#3048 Switch to GeckoView Beta
  android-components/plugins/dependencies/src/main/java/Gecko.kt
Labels: approved

#3046 Bug 1807307 - Re-land disabling LeakCanary in CI fuzzy testing builds
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing, approved

#3054 Revert "Bug 1807307 - Re-land disabling LeakCanary in CI fuzzy testing builds"
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#3018 Bug 1845825 - Update AndroidX Fragment to version 1.6.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved
