Repository mozilla-mobile/firefox-android, pull requests merged in 2023-10, with the labels that each got.

#3844 Bug 1855696 - Update FxA strings
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/main/res/layout/account_preference.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/sync_debug_preferences.xml
Labels: 🛬 needs landing, approved

#3841 Bug 1807274 - Fix verifyDownloadCompleteNotificationTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: 🛬 needs landing, approved

#3846 Bug 1852083 - Do not insert extra with null or empty key
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
Labels: 🛬 needs landing, approved

#3889 Bug 1851030 - Fix review checker icon visibility on pdp detection
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: 🛬 needs landing, approved

#3850 Bug 1848658 - Make shopping analysis field adjustedRating nullable to…
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/shopping/GeckoProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
Labels: 🛬 needs landing, approved

#3757 Bug 1838541: Changed distinctUntilChanged for MediaSessionFullScreenFeature
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt
Labels: 🛬 needs landing, approved

#3862 Bug 1855841 - Update shopping feature "Powered by" link
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt
Labels: 🛬 needs landing, approved

#3909 Bug 1856537 - Sync `fenix/app/.experimenter.yaml` with latest nimbus config
  fenix/app/.experimenter.yaml
Labels: 🛬 needs landing, approved

#3887 Bug 1854644 - Undo button from tabs tray should work.
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
Labels: 🛬 needs landing, approved

#3894 Bug 1856381 - PB search engine results, search groups and search codes TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: 🛬 needs landing, approved

#3840 Bug 1847266 - Implement status message for add-ons not signed correctly in the manager
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/webextension/WebExtensionTest.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterDelegate.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt
  android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  android-components/components/feature/addons/src/main/res/values/colors.xml
  android-components/components/feature/addons/src/main/res/values/strings.xml
  android-components/components/feature/addons/src/test/java/AddonManagerTest.kt
  android-components/components/feature/addons/src/test/java/AddonTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  fenix/app/src/main/res/values-night/colors.xml
  fenix/app/src/main/res/values/colors.xml
  fenix/app/src/test/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragmentTest.kt
Labels: 🛬 needs landing, approved

#3864 Bug 1855939 - Fix crash when tapping the shopping CFR action after device rotation
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
Labels: 🛬 needs landing, approved

#3897 Bug 1855571 - Update star rating design
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_star_fill_20.xml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_star_one_half_fill_20.xml
  android-components/components/ui/icons/src/main/res/values/colors.xml
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/StarRating.kt
  fenix/app/src/main/res/drawable/ic_star_half.xml
  fenix/app/src/main/res/values-night/colors.xml
  fenix/app/src/main/res/values/colors.xml
Labels: 🛬 needs landing, approved

#3915 Bug 1856403 - Undo review grade info string changes
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityInfoCard.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3898 Bug 1848658 - Remove fakespot shopping adjusted rating toFloatOrNull …
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
Labels: 🛬 needs landing, approved

#3824 Bug 1846341 - AC automated testing for onProductUrl, requestAnalysis, …
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing, approved

#3912 Bug 1856045 - Add dialog colours to the "Start Profiler" popup.
  fenix/app/src/main/java/org/mozilla/fenix/perf/ProfilerReusableComposable.kt
  fenix/app/src/main/java/org/mozilla/fenix/perf/ProfilerStartDialogFragment.kt
Labels: 🛬 needs landing, approved

#3892 Bug 1847266 - Implement status message for incompatible add-ons in the manager
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/webextension/WebExtensionTest.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/main/res/values/strings.xml
  android-components/components/feature/addons/src/test/java/AddonManagerTest.kt
  android-components/components/feature/addons/src/test/java/AddonTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragmentTest.kt
Labels: 🛬 needs landing, approved

#3930 Bug 1856950 - Fix wrong data review link for `device_total_ram`
  fenix/app/metrics.yaml
Labels: 🛬 needs landing, approved

#3469 Bug 1851079 – refactored Activity.enterImmersiveMode to enable proper unit testing
  android-components/components/feature/pwa/src/main/java/mozilla/components/feature/pwa/feature/WebAppActivityFeature.kt
  android-components/components/support/ktx/src/androidTest/java/mozilla/components/support/ktx/android/view/WindowKtTest.kt
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Activity.kt
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Window.kt
  android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/ActivityTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BrowserFragment.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/theme/ThemeManager.kt
  focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt
Labels: 🛬 needs landing, approved

#3917 Bug 1810047 - Implement UI for webextensions optional permissions.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/extension/WebExtensionPromptRequest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionDelegate.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt
  android-components/components/feature/addons/src/main/res/values/strings.xml
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
Labels: 🛬 needs landing, approved

#3919 Bug 1856399 - Use distinct version code in Fenix AAB
  android-components/plugins/config/src/main/java/ConfigPlugin.kt
  fenix/app/build.gradle
  taskcluster/ci/build-bundle/kind.yml
Labels: 🛬 needs landing (squash), approved

#3935 Bug 1855571 - Remove padding between stars in star rating
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/StarRating.kt
Labels: 🛬 needs landing, approved

#3848 Bug 1810044 1810045 - Delay reading clipboard and allow to paste non url
  fenix/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt
Labels: 🛬 needs landing, approved

#3901 Bug 1856434 - Only show new Firefox Suggest suggestions for the default search engine.
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/SearchSelectorToolbarActionTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: 🛬 needs landing, approved

#3925 Bug 1856894 - Fix review checker shopping icon tint
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeatureTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeShoppingExperienceFeature.kt
Labels: 🛬 needs landing, approved

#3927 Bug 1856913 - Refactor ReviewQualityCheckVendorsService and repackage ext
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckVendorsService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityInfoCard.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ext/ProductVendor.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckVendorsService.kt
Labels: 🛬 needs landing, approved

#3926 Bug 1854385 - When accessing files from downloads that cannot be opened, a snack bar with an error message should appear.
  fenix/app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt
Labels: 🛬 needs landing, approved

#3941 Bug 1857110 - Update Gradle to version 7.6.3
  android-components/gradle/wrapper/gradle-wrapper.jar
  android-components/gradle/wrapper/gradle-wrapper.properties
  android-components/gradlew
  android-components/gradlew.bat
  fenix/gradle/wrapper/gradle-wrapper.jar
  fenix/gradle/wrapper/gradle-wrapper.properties
  fenix/gradlew
  fenix/gradlew.bat
  focus-android/gradle/wrapper/gradle-wrapper.jar
  focus-android/gradle/wrapper/gradle-wrapper.properties
  focus-android/gradlew
  focus-android/gradlew.bat
Labels: 🛬 needs landing, approved

#3953 Bug 1796311 - Fix "Last updated" date in addon details view
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt
  android-components/components/feature/addons/src/test/resources/collection_with_empty_values.json
Labels: 🛬 needs landing, approved

#3849 Bug 1855620 - Set isChecked depending on mapSelectChoice
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/ChoiceAdapter.kt
Labels: 🛬 needs landing, approved

#3891 Bug 1849525 - Fix review checker service test issue with mockito
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/DefaultReviewQualityCheckServiceTest.kt
Labels: 🛬 needs landing, approved

#3886 Bug 1848527 - Part 2: Enable OutdatedDocumentation detekt rule in Focus
  focus-android/quality/detekt-baseline.xml
  focus-android/quality/detekt.yml
Labels: 🛬 needs landing, approved

#3948 Bug 1857019 - Update Fakespot SUMO links
  fenix/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#3950 Bug 1857168 - Hide empty metadata in the add-on details view
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/test/java/AddonTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegate.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegateTest.kt
Labels: 🛬 needs landing, approved

#3790 Bug 1821721 - Fixed the recently visited row width
  fenix/app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisitedViewHolder.kt
Labels: 🛬 needs landing, approved

#3957 Bug 1857283 - Swap blueline with oriole in flank-arm-robo-test configuration
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🛬 needs landing, approved

#3949 Bug 1810047 - Fixup WebExtensionPromptFeature
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/extension/WebExtensionPromptRequest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/WebExtensionActionTest.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
Labels: 🛬 needs landing, approved

#3955 Bug 1857232 - Linkify author of an add-on in the details view
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt
  android-components/components/feature/addons/src/main/res/values/strings.xml
  android-components/components/feature/addons/src/test/java/AddonTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonDetailsActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegate.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonDetailsFragment.kt
  fenix/app/src/main/res/layout/fragment_add_on_details.xml
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegateTest.kt
Labels: 🛬 needs landing, approved

#141 Bug 1812233 - ui-autocomplete: correct InputConnection behavior
  android-components/components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt
Labels: 🛬 needs landing, approved

#1474 Bug 1812875 - Do not allow closing tab during tabs selection
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
Labels: 🛬 needs landing, approved

#3946 Bug 1857147 - Refactor the Beta label composable for reusability
  fenix/app/src/main/java/org/mozilla/fenix/compose/BetaLabel.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt
Labels: 🛬 needs landing, approved

#3619 Bug 1843508 - Add review quality check feature telemetry events
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/NoAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckCards.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckSettingsCard.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
  fenix/app/tags.yaml
Labels: 🛬 needs landing, approved

#3970 Bug 1857117 - Update review quality check "Powered by" url
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt
Labels: 🛬 needs landing, approved

#3940 Bug 1856399 - Use distinct version code in Focus AAB
  focus-android/app/build.gradle
Labels: 🛬 needs landing (squash), approved

#3977 Bug 1857563 - Update Mockito to version 5.6.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3778 Bug 1823306 - add null check for bottomToolbarChangedAction
  android-components/components/feature/session/src/main/java/mozilla/components/feature/session/behavior/EngineViewBrowserToolbarBehavior.kt
  android-components/components/feature/session/src/test/java/mozilla/components/feature/session/behavior/EngineViewBrowserToolbarBehaviorTest.kt
Labels: 🛬 needs landing, approved

#3806 Bug 1849073 - Part 3: Remove trivial `showUnifiedSearchFeature` and `enableUnifiedSearchSettingsUI` checks
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/toolbar/SearchSelectorBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
  fenix/app/src/main/res/layout/fragment_home.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: 🛬 needs landing, approved

#3976 Bug 1857539 - Remove AMO request interceptor
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/AppRequestInterceptor.kt
  fenix/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/AppRequestInterceptorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementFragmentTest.kt
Labels: 🛬 needs landing, approved

#3952 Bug 1856357 - Allow first shopping CFR to be displayed again after 24 hours for non-opted in users
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/interactor/BrowserToolbarInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: 🛬 needs landing, approved

#3996 Bug 1817955 - Increase Tap Area of the Add new collection prompt edittext field.
  fenix/app/src/main/java/org/mozilla/fenix/collections/CollectionsDialog.kt
  fenix/app/src/main/res/values/dimens.xml
Labels: 🛬 needs landing, approved

#3947 Bug 1857139 - Add translation bottom sheet boilerplate
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_dropdown_arrow.xml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_translate_24.xml
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/interactor/BrowserToolbarInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarInteractorTest.kt
Labels: 🛬 needs landing, approved

#3911 Bug 1847088 - Show a notification in the Fenix add-on manager when the extensions process spawning is disabled
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/ExtensionsProcessMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ExtensionsProcessStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/ExtensionsProcessMiddlewareTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/reducer/ExtensionsProcessStateReducerTest.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt
  android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_header_section_item.xml
  android-components/components/feature/addons/src/main/res/values/strings.xml
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/ExtensionsProcessDisabledPromptObserver.kt
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledController.kt
  fenix/app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#4001 Revert "Bug 1849368 - Remove data path and data authorities requirement for open links in apps"
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
Labels: 🛬 needs landing, approved

#3719 Bug 1854126 - App link does not redirect if no host or authority is present
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing, approved

#3973 Bug 1851259 - Delete browsing data only if fragment attached
  fenix/app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
Labels: 🛬 needs landing, approved

#3971 Bug 1857442 - Recently closed TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/RecentlyClosedTabsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
Labels: 🛬 needs landing, approved

#4011 Bug 1858081 - Collections TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeCollectionTest.kt
Labels: 🛬 needs landing, approved

#3998 Bug 1857287 - Move isProductUrl to ContentState
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ShoppingProductStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/SessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ShoppingProductActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/UpdateProductUrlStateActionTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
Labels: 🛬 needs landing, approved

#4012 Bug 1858014 - Set review checker peek height to half screen height
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
Labels: 🛬 needs landing, approved

#3961 Bug 1856773 – add summary to manage account button
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/account_settings_preferences.xml
Labels: 🛬 needs landing, approved

#3960 Bug 1846801 – add telemetry for manage account button
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
Labels: 🛬 needs landing, approved

#4004 Bug 1857985 - Change review grade description text style to body 2
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewGrade.kt
Labels: 🛬 needs landing, approved

#4003 Bug 1857987 - Fix Adjusted rating card spacing
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
Labels: 🛬 needs landing, approved

#4005 Bug 1853687 - run Rust work on test thread so it can complete sequentially
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
Labels: 🛬 needs landing, approved

#3959 Bug 1840492 – allow manage account ride to release
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
Labels: 🛬 needs landing, approved

#4021 Bug 1858242 - Bump Google Cloud SDK to 450.0.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing, approved

#3937 Bug 1850674 - Add extra add-on metadata
  android-components/.buildconfig.yml
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/MockWebExtension.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  android-components/components/feature/addons/build.gradle
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/test/java/AddonManagerTest.kt
  android-components/components/feature/addons/src/test/java/AddonTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
Labels: 🛬 needs landing, approved

#3978 Bug 1857549 - login password matches site detected telemetry
  android-components/components/feature/autofill/src/main/java/mozilla/components/feature/autofill/facts/AutofillFacts.kt
  android-components/components/feature/autofill/src/main/java/mozilla/components/feature/autofill/ui/AbstractAutofillSearchActivity.kt
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
Labels: 🛬 needs landing, approved

#4017 Bug 1857984 - Reduce beta label padding
  fenix/app/src/main/java/org/mozilla/fenix/compose/BetaLabel.kt
Labels: 🛬 needs landing, approved

#4041 Revert "Bug 1853687 - run Rust work on test thread so it can complete…
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
Labels: 🛬 needs landing, approved

#4023 Bug 1857988 - Add divider to highlights card
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
Labels: 🛬 needs landing, approved

#4043 Bug 1858057 - Make WebExtensionPrompt available to the whole app.
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
Labels: 🛬 needs landing, approved

#4044 Bug 1858495 - Remove unused getFenixAddons function.
  fenix/app/src/main/java/org/mozilla/fenix/ext/AddonManager.kt
Labels: 🛬 needs landing, approved

#4046 Bug 1858498 - Do not show post-install dialog during updates
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
Labels: 🛬 needs landing, approved

#3836 Bug 1849073 - Part 4: Remove the Edit Custom Search Engine fragment
  fenix/app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/EditCustomSearchEngineFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
  fenix/app/src/main/res/menu/edit_custom_searchengine_menu.xml
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3851 Bug 1849073 - Part 6: Remove the old search preferences
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/search_preferences.xml
  fenix/app/src/main/res/xml/search_settings_preferences.xml
  fenix/app/src/test/java/org/mozilla/fenix/settings/search/SearchEngineFragmentTest.kt
Labels: 🛬 needs landing, approved

#4042 Bug 1857989 - Change footer text base color to text secondary
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckFooter.kt
Labels: 🛬 needs landing, approved

#4029 Bug 1858378 - Fix flaky review quality check navigation middleware unit test
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/GetReviewQualityCheckSumoUrl.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#4031 Bug 1858406 - Update strings for shopping feature
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3845 Bug 1849274 - Record history telemetry when Unified Search result tap
  android-components/components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarWrapper.kt
Labels: 🛬 needs landing, approved

#4032 Bug 1856944 - Wrap Review checker scaffold in surface
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt
Labels: 🛬 needs landing, approved

#4040 Bug 1858448 - Renew all telemetry to never expires
  focus-android/app/metrics.yaml
Labels: 🛬 needs landing, approved

#4047 Bug 1857434 - Update AC Shopping Recommendation fields to be NonNull
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/shopping/GeckoProductRecommendation.kt
Labels: 🛬 needs landing, approved

#4018 Bug 1855291 - Handle FxA exceptions in getManageAccountURL
  android-components/components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
Labels: 🛬 needs landing, approved

#4039 Bug 1858440 - Renew all telemetry to never expires
  fenix/app/metrics.yaml
Labels: 🛬 needs landing, approved

#4072 Bug 1857872 - Fix defaultSearchCodeBingUS test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: 🛬 needs landing, approved

#4034 Bug 1858438 - Tabs Tray TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeMediaNotificationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: 🛬 needs landing, approved

#4036 Bug 1858607 - Top sites TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PDFViewerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTopSitesRobot.kt
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
Labels: 🛬 needs landing, approved

#4062 Bug 1826318 - Fix verifyCreditCardsAutofillToggleTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing

#4049 Bug 1856496 - enable fx-suggest for nightly
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: 🛬 needs landing, approved

#3847 Bug 1855737 - New private homescreen mask icon
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_private_mode_24.xml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_private_mode_circle_fill_20.xml
  android-components/components/ui/icons/src/main/res/values/colors.xml
  android-components/components/ui/tabcounter/src/main/res/drawable/mozac_ui_tabcounter_badge.xml
  android-components/components/ui/tabcounter/src/main/res/layout/mozac_ui_tabcounter_layout.xml
  fenix/app/src/main/res/values-night/colors.xml
  fenix/app/src/main/res/values/colors.xml
Labels: 🛬 needs landing, approved

#4066 Bug 1858771 - New Help button telemetry in home menu
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenuView.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/HomeMenuViewTest.kt
Labels: 🛬 needs landing, approved

#4073 No bug - Update uses of `SuggestionQuery` in Firefox Suggest.
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
Labels: 🕵️‍♀️ needs review, do not land

#3907 Bug 1856432 - Change default onboarding strings
  fenix/app/onboarding.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingScreen.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4059 Bug 1858018 - Persist review checker reanalysis state
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingState.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingStateReducer.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/appstate/ShoppingActionTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeatureTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/DefaultReviewQualityCheckServiceTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4060 Bug 1855150 - Add bottom sheet displayed and closed event extras
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckBottomSheetStateFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/BottomSheetViewState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckBottomSheetStateFeatureTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
Labels: 🛬 needs landing (squash), approved

#3968 Bug 1807307 - Disable LeakCanary in ui-test-apk with gradle flag
  fenix/app/build.gradle
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/debug/java/org/mozilla/fenix/DebugFenixApplication.kt
  fenix/app/src/main/res/xml/preferences.xml
  taskcluster/ci/build-apk/kind.yml
Labels: 🛬 needs landing, approved

#3203 Bug 1834820 - Add RemoteSettings downloader class
  android-components/.buildconfig.yml
  android-components/components/feature/search/build.gradle
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/BaseSearchTelemetry.kt
  android-components/components/support/remotesettings/README.md
  android-components/components/support/remotesettings/build.gradle
  android-components/components/support/remotesettings/proguard-rules.pro
  android-components/components/support/remotesettings/src/main/AndroidManifest.xml
  android-components/components/support/remotesettings/src/main/java/mozilla/components/support/remotesettings/RemoteSettingsClient.kt
  android-components/components/support/remotesettings/src/test/java/mozilla/components/support/remotesettings/RemoteSettingsClientTest.kt
  android-components/components/support/remotesettings/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  android-components/components/support/remotesettings/src/test/resources/robolectric.properties
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/.buildconfig.yml
  focus-android/.buildconfig.yml
  taskcluster/ci/config.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#4109 Bug 1856432 - Change default onboarding strings
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4048 Bug 1857424 - Add shopping review analysis pageNotSupported field
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/shopping/GeckoProductAnalysis.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt
Labels: 🛬 needs landing, approved

#4020 Bug 1856438 - Reorg Search settings to match the new Cross Platform Suggest Design
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/search_settings_preferences.xml
  fenix/app/src/test/java/org/mozilla/fenix/settings/search/SearchEngineFragmentTest.kt
Labels: 🛬 needs landing, approved

#3922 Bug 1856731 - Moves showing reader mode from the content / background script to the Feature.
  android-components/components/feature/readerview/src/main/assets/extensions/readerview/readerview-background.js
  android-components/components/feature/readerview/src/main/assets/extensions/readerview/readerview-content.js
  android-components/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt
  android-components/components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing (squash), approved

#4033 Bug 1858422 - Upgrade zxing to latest version.
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4103 Bug 1856852 - Fix review checker not enough reviews card case
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingStateReducer.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4106 Bug 1857440 - Fix review checker tag icon flicker when pdp loads
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeatureTest.kt
Labels: 🛬 needs landing, approved

#3831 Bug 1855586 - Update VisitType enum from application-services
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Types.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/history/PagedHistoryProvider.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/history/PagedHistoryProviderTest.kt
Labels: 🛬 needs landing, approved

#4110 Bug 1859408 - Instrument the awesomebar to report visible suggestions.
  android-components/components/compose/awesomebar/build.gradle
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt
  android-components/components/compose/awesomebar/src/test/java/mozilla/components/compose/browser/awesomebar/internal/SuggestionsTest.kt
  android-components/components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
Labels: 🛬 needs landing, approved

#4115 Bug 1859494 - Rename a boolean variable in `AddonUdpater` and add some more comments
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
Labels: 🛬 needs landing, approved

#4123 Bug 1859644 - Don't show full keyword in FxSuggest Suggesions
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
Labels: 🛬 needs landing, approved

#4057 Bug 1857487 - Kill the app when backgrounded and extensions process s…
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/ExtensionsProcessDisabledPromptObserver.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledController.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledControllerTest.kt
Labels: 🛬 needs landing, approved

#4117 Bug 1856959 - Fix review checker unsupported product error case
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
Labels: 🛬 needs landing, approved

#3842 Bug 1849226: Record bookmark telemetry when Unified Search result tap
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarWrapper.kt
Labels: 🛬 needs landing, approved

#4121 Bug 1858974 - Adds Private browsing mode icon while browsing
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/toolbar/TabCounterToolbarButton.kt
  android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/toolbar/TabCounterToolbarButtonTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
Labels: 🛬 needs landing, approved

#4138 Bug 1838841 - Ship 120.0.0 of feature-webcompat
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1605611-maps.google.com-directions-time.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1799994-www.vivobarefoot.com-product-filters-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1829952-eventer.co.il-button-height.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1605611-maps.google.com-directions-time.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1859617-installtrigger-removal-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/ua_helpers.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/salesforce.js
Labels: 🛬 needs landing, approved

#3635 Bug 1853077 - Update Adjust to version 4.35.1
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
  focus-android/plugins/focusdependencies/src/main/java/FocusDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4055 Bug 1849073 - Part 5: Remove the Add Search Engine fragment
  fenix/app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/AddSearchEngineFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  fenix/app/src/main/res/layout/custom_search_engine.xml
  fenix/app/src/main/res/layout/custom_search_engine_radio_button.xml
  fenix/app/src/main/res/layout/fragment_add_search_engine.xml
  fenix/app/src/main/res/layout/fragment_save_search_engine.xml
  fenix/app/src/main/res/menu/add_custom_searchengine_menu.xml
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/dimens.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4124 Bug 1858997 - Ensures we remove the Popup when destroying the fragment
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, approved

#4148 Bug 1859488 - Updates mask in private_browsing_button.xml
  fenix/app/src/main/res/drawable/private_browsing_button.xml
Labels: 🛬 needs landing, approved

#4122 Bug 1858872 - Switch "windows" with "tabs" in private mode description
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/FeltPrivacyInfoCard.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4145 Bug 1858879 - Changed link text in FeltPrivacyInfoCard to default text color
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/FeltPrivacyInfoCard.kt
Labels: 🛬 needs landing, approved

#4157 Bug 1859338 - Fixes ability to use talkback on LinkText
  fenix/app/src/main/java/org/mozilla/fenix/compose/LinkText.kt
Labels: 🛬 needs landing, approved

#4142 Bug 1859839 - Update 'manage search shortcuts' string in Search settings
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchShortcutsFragment.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/search_settings_preferences.xml
Labels: 🛬 needs landing, approved

#4158 Bug 1859936 - Update Firebase Cloud Messaging to version 23.3.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4102 Bug 1859257 - Add to homescreen and error pages TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddToHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
Labels: 🛬 needs landing, approved

#4107 Bug 1859318 - Text selection TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TextSelectionTest.kt
Labels: 🛬 needs landing, approved

#4159 Bug 1859839 - Fix string removal of preferences_manage_search_shortcuts
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchShortcutsFragment.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/search_settings_preferences.xml
Labels: 🛬 needs landing, approved

#4154 Bug 1859909 - Update AndroidX Compose to version 1.5.4
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4132 Bug 1859564 - Context menus TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: 🛬 needs landing, approved

#4153 Bug 1858895 - Fix horizontal padding for FeltPrivacyInfoCard
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/FeltPrivacyInfoCard.kt
Labels: 🛬 needs landing, approved

#4173 Bug 1859488 - Update the private browsing button to use the correct icon
  fenix/app/src/main/res/drawable/ic_private_mode_circle_fill_48.xml
  fenix/app/src/main/res/drawable/private_browsing_button.xml
  fenix/app/src/main/res/layout/fragment_home.xml
Labels: 🛬 needs landing, approved

#4151 Bug 1859903 - Adds telemetry for the new quick erase action
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Labels: 🛬 needs landing, approved

#4135 Bug 1859775 - Permissions prompts & doorhangers TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
Labels: 🛬 needs landing, approved

#4163 Bug 1860052 - Custom tabs TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
Labels: 🛬 needs landing, approved

#2535 Bug 1812797 - Add referrerUrl to Request for download features
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchClient.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/fetch/GeckoViewFetchUnitTestCases.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/content/ShareInternetResourceState.kt
  android-components/components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Request.kt
  android-components/components/concept/fetch/src/test/java/mozilla/components/concept/fetch/RequestTest.kt
  android-components/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/temporary/TemporaryDownloadFeature.kt
Labels: 🛬 needs landing, approved

#4191 Bug 1860467 - Fix testSearchBarShowsSearchTermOnEdit UI test
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
Labels: 🛬 needs landing

#4133 Bug 1859593 - Use ProductAnalysis and ProductRecommendation as data classes
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/shopping/GeckoProductAnalysis.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/shopping/GeckoProductRecommendation.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/shopping/ProductAnalysis.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/shopping/ProductRecommendation.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/DefaultReviewQualityCheckServiceTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
Labels: 🛬 needs landing, approved

#4178 Bug 1860251 - Crash reporting TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
Labels: 🛬 needs landing, approved

#4179 Bug 1860262 - PWA TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: 🛬 needs landing, approved

#4177 Bug 1860243 - NoNetworkAccessStartupTests TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
Labels: 🛬 needs landing, approved

#4182 Bug 1860263 - Remove onActivityCreated from Focus fragments.
  focus-android/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
Labels: 🛬 needs landing, approved

#4165 Bug 1858152 - setting high priority rules for pull requests using mergi…
  .mergify.yml
Labels: 🛬 needs landing, approved

#4181 Bug 1860274 - Modify the SwitchWithLabel behaviour for clicking and accessibility.
  fenix/app/src/main/java/org/mozilla/fenix/compose/SwitchWithLabel.kt
Labels: 🛬 needs landing, approved

#4116 Bug 1859528 - Reader mode TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ReaderViewTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ReaderViewRobot.kt
Labels: 🛬 needs landing, approved

#4195 Bug 1860605 - Start the 121 development cycle
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4174 Bug 1860186 - Dont split languages in AAB
  fenix/app/build.gradle
Labels: 🛬 needs landing, approved

#4198 Bug 1860632 - Add unenrollment telemetry verification tests to integration test suite
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/GenericExperimentIntegrationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/tests/test_generic_scenarios.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: 🛬 needs landing, approved

#3975 Bug 1856957 - Translations UI Download Cycle Spinner.
  fenix/app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/DownloadIndicator.kt
  fenix/app/src/main/res/values/static_strings.xml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#4194 Bug 1857215 - Part 1:Integrate review checker recommendations
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/EnumMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/EnumMapperTest.kt
Labels: 🛬 needs landing, approved

#4120 Bug 1854501 - Add telemetry to count Fakespot exposures
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeatureTest.kt
Labels: 🛬 needs landing, approved
