Repository mozilla-mobile/firefox-android, pull requests merged in 2023-05, with the labels that each got.

#1792 Bug 1822192 - Add empty state UI for Normal and Private tab pages
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
Labels: 🛬 needs landing, approved

#1868 Bug 1829531 - Fix the status bar color when the download prompt appears.
  fenix/app/src/main/java/org/mozilla/fenix/downloads/StartDownloadDialog.kt
  fenix/app/src/test/java/org/mozilla/fenix/downloads/StartDownloadDialogTest.kt
Labels: 🛬 needs landing

#1843 Bug 1830602 - Update AndroidX Core to version 1.10.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1790 Bug 1820122 - Do not run gradle 'test' in external-gradle-dependencies-fenix
  taskcluster/android_taskgraph/transforms/external_gradle_dependencies.py
Labels: 🛬 needs landing

#1755 Bug 1826994 - Add functionality for the exit select mode button in the multi selection banner
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
Labels: 🛬 needs landing, approved

#1842 Bug 1830601 - Update Robolectric to version 4.10.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1871 Bug 1830902 - Add a licence to FenixNimbusMessagingController
  fenix/app/src/main/java/org/mozilla/fenix/messaging/FenixNimbusMessagingController.kt
Labels: 🛬 needs landing, approved

#1813 Bug 1823999 - Fix UNDO Snackbar for composified Tabs Tray
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFab.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/res/layout/component_tabstray3_fab.xml
Labels: 🛬 needs landing, approved

#1768 Bug 1826767 - Update app to use onboarding manifest cards and enum
  fenix/app/src/androidTest/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingTelemetryRecorder.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingPageType.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingScreen.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageState.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageUiData.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/JunoOnboardingPageTypeTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/OnboardingPageUiDataTest.kt
Labels: 🛬 needs landing, approved

#1838 Bug 1830598 - Update a few AndroidX dependencies to their latest point releases
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1753 Bug 1829605 - Remove (if any) trailing slash from local.properties geckoview path
  fenix/app/build.gradle
Labels: 🛬 needs landing

#1874 Bug 1830930 - Update AndroidX Annotation to version 1.6.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1880 Bug 1830849 - Add image resource field to Nimbus onboarding feature
  fenix/app/onboarding.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapper.kt
Labels: 🛬 needs landing, approved

#1881 Bug 1831083 - Refactor DefaultReaderModeController to improve testing.
  fenix/app/src/main/java/org/mozilla/fenix/browser/readermode/ReaderModeController.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/readermode/DefaultReaderModeControllerTest.kt
Labels: 🛬 needs landing, approved

#1882 Bug 1830080 Add more careful handling of preview-collection in maybeFetchExperiments
  fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  fenix/app/src/test/java/org/mozilla/fenix/nimbus/NimbusSystemTest.kt
Labels: 🛬 needs landing, approved

#1885 Bug 1805411 - Ship 114.0.0 of feature-webcompat
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1748455-reddit.com-gallery-image-width-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1789164-zdnet.com-cropped-section.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1800143-www.nintendo.co.jp-zoomed-in-image-scrolling-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1829949-tomshardware.com-scrollbar-width.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1829952-eventer.co.il-button-height.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1830747-babbel.com-page-height.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1830752-afisha.ru-slider-pointer-events.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1830761-91mobiles.com-content-height.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1830796-copyleaks.com-hide-unsupported.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1830810-interceramic.com-hide-unsupported.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1830813-page.onstove.com-hide-unsupported.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1739489-draftjs-beforeinput.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1830776-blueshieldca.com-unsupported.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1831007-nintendo-window-OnetrustActiveGroups.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/custom_functions.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#1795 Bug 1822887 - Refactor multi selection business logic from `NavigationInteractor` to `TabsTrayController`
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionMenuIntegration.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayInteractorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/browser/SelectionMenuIntegrationTest.kt
Labels: 🛬 needs landing, approved

#1883 Bug 1831082 - Update Sentry to version 6.18.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1884 Bug 1831023 - Update AndroidX Appcompat to version 1.6.1
  android-components/components/support/base/src/main/AndroidManifest.xml
  android-components/components/support/base/src/main/java/mozilla/components/support/base/android/NotificationsDelegate.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/src/main/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelDialogFragment.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing (squash), approved

#1875 Bug 1830988 - Renew telemetry probes expiring in v116
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/telemetry/TelemetryLifecycleObserver.kt
  fenix/app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/telemetry/TelemetryLifecycleObserverTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#1695 Bug 1821961 - Updated the collapse animation of the tabs tray FAB & scrim
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabSheetBehaviorManager.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabSheetBehaviorManagerTest.kt
Labels: 🛬 needs landing, approved

#1892 Bug 1831237 - Update AndroidX Compose to version 1.4.3
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1651 Bug 1823678 - Integrate Server Knobs into Fenix
  android-components/components/service/glean/src/main/java/mozilla/components/service/glean/Glean.kt
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing

#1760 Bug 1829669 - New open links in apps CFR UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing

#1904 Bug 1821993 - Disable failing scanButtonDenyPermissionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: 🛬 needs landing

#1901 Bug 1831316 - Publish AC to Maven during the ship phase
  taskcluster/ci/beetmover/kind.yml
  taskcluster/ci/release-notify-push/kind.yml
  taskcluster/ci/release-notify-ship/kind.yml
Labels: 🛬 needs landing

#1825 Bug 1822274 - Fix flaky verifySaveCreditCardFromFormTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing

#1893 Bug 1831239 - Update Kotlin to version 1.8.21 and AGP to version 7.4.2
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1828 Bug 1830011 - New Delete browsing data on quit tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/Matchers.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataOnQuitRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing

#1917 Bug 1831546 - Update AndroidX Browser to version 1.5.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#44 Bug 1812825 - Fix overlapping text in BrowserMenuImageTextCheckboxButton
  android-components/components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_text_checkbox_button.xml
Labels: 🛬 needs landing, approved

#1856 Bug 1823682 - add Server Knobs validation metric
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
Labels: 🛬 needs landing, approved

#1905 Bug 1812124 - Allow saving ReaderView as PDF
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/FetchDownloadManagerTest.kt
Labels: 🛬 needs landing

#1691 Bug 1822447 - Upgrade RecyclerView Library and remove tab tray thumbnail placeholder
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ComposeViewHolder.kt
  fenix/app/src/main/res/layout/tab_tray_grid_item.xml
  fenix/app/src/main/res/layout/tab_tray_item.xml
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing (squash), approved

#1829 Bug 1821993 - Fix SearchTest#scanButtonDenyPermissionTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing

#1920 Bug 1831628 - Swap out the COR-L29 Android device in flank-arm-legacy-api-tests and flank-arm-robo-test configurations
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🛬 needs landing

#1385 Bug 1796357 - Remove media meta data bitmap workaround
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/mediasession/GeckoMediaSessionDelegate.kt
Labels: 🛬 needs landing, approved

#1940 Bug 1831901 - Start the Nightly 115 development cycle
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#1946 Update GeckoView (Nightly) to 115.0.20230508173503
  android-components/plugins/dependencies/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#1807 Bug 1830282 - Replace Focus UrlUtils.java methods with URLStringUtils from AC.
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
  android-components/components/support/utils/src/main/java/mozilla/components/support/ktx/util/URLStringUtils.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/URLStringUtilsTest.kt
  focus-android/app/src/main/java/org/mozilla/focus/ext/String.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/search/ManualAddSearchEnginePreference.kt
  focus-android/app/src/main/java/org/mozilla/focus/session/IntentProcessor.kt
  focus-android/app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/shortcut/HomeScreen.java
  focus-android/app/src/main/java/org/mozilla/focus/shortcut/IconGenerator.kt
  focus-android/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/UrlUtils.java
  focus-android/app/src/test/java/org/mozilla/focus/telemetry/HistogramTest.kt
  focus-android/app/src/test/java/org/mozilla/focus/utils/UrlUtilsTest.java
Labels: 🛬 needs landing, approved

#1935 Bug 1821024 - Re-enable DownloadTest#openDownloadedFileTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing

#1919 Bug 1831555 - Refactor false assertions in UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionExceptionsRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: 🛬 needs landing

#1941 Bug 1831910 - Update AndroidX Activity to version 1.7.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing

#1962 Bug 1832087 - Add bug causing flakiness in cookie banner reduction UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt
Labels: 🛬 needs landing

#1944 Bug 1818278 - Update firefox-android documentations around Beta cuts
  docs/changelog.md
  docs/contribute/release_checklist.md
  fenix/docs/Creating-a-release-branch.md
Labels: 🛬 needs landing

#1949 Bug 1807138 – increase snackbar width for tablets
  android-components/components/lib/crash/docs/metrics.md
  android-components/components/service/nimbus/docs/metrics.md
  android-components/components/support/sync-telemetry/docs/metrics.md
  fenix/app/src/main/res/values-sw600dp/bools.xml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#1967 Bug 1827905 - Update manifestPlaceholders in variants instead of reinit
  fenix/app/build.gradle
Labels: 🛬 needs landing, approved

#1945 Bug 1822299 - Catch RejectedExecutionException in automated test
  android-components/components/feature/qr/src/main/java/mozilla/components/feature/qr/QrFragment.kt
Labels: 🛬 needs landing, approved

#1964 Bug 1829560 - Update profiler threads and features for Graphics & Media
  fenix/app/src/main/java/org/mozilla/fenix/perf/ProfilerUtils.kt
Labels: 🛬 needs landing, approved

#1978 Bug 1826591 - Catch and log exceptions when reporting crashes
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/ExceptionHandler.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#1870 Bug 1830881 - Change strings for submitted cookie banner site reports.
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerDetailsController.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsView.kt
  fenix/app/src/main/java/org/mozilla/fenix/trackingprotection/ProtectionsStore.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/CookieBannerHandlingDetailsViewTest.kt
Labels: 🛬 needs landing

#1710 Bug 1816555 - Add functionality for collections button in composed multi selection banner
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: 🛬 needs landing, approved

#1523 Bug 1822950 - Add Karakalpak(kaa) locale
  fenix/app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt
Labels: 🛬 needs landing, approved

#1757 Bug 1816556 - Add functionality for the share button in the multi selection banner
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: 🛬 needs landing, approved

#1979 Bug 1832416 - Update Material Components to version 1.9.0
  android-components/components/browser/session-storage/build.gradle
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#2008 Bug 1807276 - Fix firstRunScreenTest and youControlYourDataCardTest UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing

#1897 Bug 1816517 - Add functionality for the three-dot button in the tabs tray page indicator
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: 🛬 needs landing, approved

#1996 Bug 1832638 - Update Kotlin Serialization to version 1.5.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing

#1787 Bug 1830045 - New search bookmarks UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: 🛬 needs landing

#1992 Bug 1815402 - Fix flaky verifyReaderViewAppearanceUI UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: 🛬 needs landing

#1987 Bug 1830304 - Set browsing mode when redesigned onboarding is enabled
  fenix/app/src/main/java/org/mozilla/fenix/home/Mode.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/ModeTest.kt
Labels: 🛬 needs landing, approved

#1989 Bug 1829083 - Migrate to compose foundation pager
  fenix/app/build.gradle
  fenix/app/src/main/java/org/mozilla/fenix/compose/PagerIndicator.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingScreen.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing, approved

#2038 Bug 1807268 - disable failing dismissOnboardingUsingHelpTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
Labels: 🛬 needs landing

#2017 Bug 1830765 - Remove duplicate toolbar position metrics
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing, approved

#1878 Bug 1831009 - update RecyclerView with Compose implementations to new guidelines for 1.3.0
  fenix/app/src/main/java/org/mozilla/fenix/experiments/ResearchSurfaceDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/HomeNotificationPermissionDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/HomeOnboardingDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/WallpaperOnboardingDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/ProtectionsView.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing (squash)

#1906 Bug 1831068 - Add and incorporate the extra image resources for Nimbus experiments
  fenix/app/onboarding.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ext/Modifier.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingScreen.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageUiData.kt
  fenix/app/src/main/res/drawable-hdpi/onboarding_default_browser.webp
  fenix/app/src/main/res/drawable-hdpi/onboarding_notification.webp
  fenix/app/src/main/res/drawable-hdpi/onboarding_sync.webp
  fenix/app/src/main/res/drawable-xhdpi/onboarding_default_browser.webp
  fenix/app/src/main/res/drawable-xhdpi/onboarding_notification.webp
  fenix/app/src/main/res/drawable-xhdpi/onboarding_sync.webp
  fenix/app/src/main/res/drawable-xxhdpi/onboarding_default_browser.webp
  fenix/app/src/main/res/drawable-xxhdpi/onboarding_notification.webp
  fenix/app/src/main/res/drawable-xxhdpi/onboarding_sync.webp
  fenix/app/src/main/res/raw/keep.xml
  fenix/app/src/test/java/org/mozilla/fenix/compose/ext/ModifierTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/OnboardingPageUiDataTest.kt
Labels: 🛬 needs landing, approved

#2009 Bug 1794871 - Fix intermittent failure in AppLinkFeatureTest
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
Labels: 🛬 needs landing, approved

#1742 Bug 1759519 - Fix crash when parsing malformed Content-Length
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing, approved

#915 Bug 1810629 - Add an Android shortcut to go straight to the login and passwords page
  fenix/app/src/beta/res/xml/shortcuts.xml
  fenix/app/src/debug/res/xml/shortcuts.xml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/IntentProcessors.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/intent/OpenPasswordManagerIntentProcessor.kt
  fenix/app/src/main/java/org/mozilla/fenix/shortcut/PasswordManagerIntentProcessor.kt
  fenix/app/src/main/res/drawable-v26/ic_static_password_shortcut.xml
  fenix/app/src/main/res/drawable/ic_static_lock.xml
  fenix/app/src/main/res/drawable/ic_static_password_shortcut.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/shortcuts.xml
  fenix/app/src/nightly/res/xml/shortcuts.xml
  fenix/app/src/release/res/xml/shortcuts.xml
  fenix/app/src/test/java/org/mozilla/fenix/IntentReceiverActivityTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/intent/OpenPasswordManagerIntentProcessorTest.kt
Labels: 🛬 needs landing

#1226 Bug 1807131: Fix ripples for snackbar and alert dialogs
  fenix/app/src/main/res/drawable/ripple_button.xml
  fenix/app/src/main/res/drawable/ripple_button_dark.xml
  fenix/app/src/main/res/layout/fenix_snackbar.xml
  fenix/app/src/main/res/values/styles.xml
Labels: 🛬 needs landing, approved

#2044 Bug 1833199 - Ensure that changes to Fenix & Focus dependencies rebuild the gradle cache
  taskcluster/android_taskgraph/transforms/external_gradle_dependencies.py
Labels: 🛬 needs landing, approved

#2001 Bug 1832351 - Stop applink prompt if custom tab caller is the same as the external app
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing, approved

#1994 Bug 1832597 - Update some Fenix & Focus testing dependencies
  fenix/app/build.gradle
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#2043 Bug 1830083 - Make action_home local to JunoOnboardingFragment
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingFragment.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
Labels: 🛬 needs landing, approved

#2057 Bug 1833118 - Rename OnboardingPageState `image` to `imageRes` and update class desc @param to @property
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/NotificationPermissionDialogScreen.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageState.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/UpgradeOnboarding.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt
Labels: 🛬 needs landing, approved

#1976 Bug 1831898 - Fix install firefox banner not showing.
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/BrowsersTest.kt
Labels: 🛬 needs landing, approved

#1988 Bug 1830895 - Add observeAsComposableState compose extension
  android-components/components/lib/state/src/androidTest/java/mozilla/components/lib/state/ext/ComposeExtensionsKtTest.kt
  android-components/components/lib/state/src/main/java/mozilla/components/lib/state/ext/ComposeExtensions.kt
Labels: 🛬 needs landing, approved

#2052 Bug 1833292 - Update Google Accompanist to version 0.30.1
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing, approved

#2060 Bug 1833382 - Temporarily remove walleye for long queuing on Test Lab
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🛬 needs landing

#2011 Bug 1832828 - Improve mainMenuShareButtonTest UI test coverage
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MainMenuTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt
Labels: 🛬 needs landing, approved

#1867 Bug 1830112 - Display full text in compose button when large font
  fenix/app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
Labels: 🛬 needs landing, approved

#2019 Bug 1832892 – update delete histry dialog body text
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  fenix/app/src/main/res/layout/delete_history_time_range_dialog.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#2064 Bug 1833404 - Update Sentry to version 6.19.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1891 Bug 1831235 - Update Firebase Messaging to version 23.1.2
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing

#2047 Bug 1833255 - Set expectations for stale contributions in README
  docs/shared/android/CONTRIBUTING_code.md
Labels: 🛬 needs landing, approved

#2053 Bug 1826404 – fixed tabs list card spacing
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
Labels: 🛬 needs landing, approved

#1933 Bug 1832006 - [MozillaOnline] Add description of site permissions fragment
  fenix/app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt
  fenix/app/src/main/res/values-zh-rCN/mozonline_strings.xml
  fenix/app/src/main/res/values/mozonline_strings.xml
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/xml/site_permissions_preferences.xml
Labels: 🛬 needs landing, approved

#1532 Bug 1824177 - Set the correct label for email title for accessibility tools
  fenix/app/src/main/res/layout/fragment_address_editor.xml
Labels: 🛬 needs landing (squash), approved

#1991 Bug 1832069 Add Google Play install referrer
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/InstallReferrerMetricsService.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/CustomAttributeProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/metrics/InstallReferrerMetricsServiceTest.kt
  fenix/app/tags.yaml
Labels: 🛬 needs landing, approved

#2041 Bug 1833120 - Fix verifySearchBookmarksViewTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: 🛬 needs landing

#2065 Bug 1833452 - Fix app services autopublish when building Fenix/Focus
  fenix/app/build.gradle
  fenix/settings.gradle
  focus-android/app/build.gradle
  focus-android/settings.gradle
Labels: 🛬 needs landing, approved

#2079 Bug 1833627 - Add replacement API 27 device to UI test configurations
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🛬 needs landing

#2087 Revert "Bug 1833655 - Add a GitHub workflow to automate adding labels and assignees to pull requests"
  .github/workflows/pull-request-labeler.yml
Labels: 🕵️‍♀️ needs review

#2089 Bug 1809803 - Remove wallpaperV2 flag and related assets and code.
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/wallpapers/LegacyWallpaperDownloader.kt
  fenix/app/src/main/java/org/mozilla/fenix/wallpapers/LegacyWallpaperFileManager.kt
  fenix/app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  fenix/app/src/main/res/drawable-hdpi/amethyst.png
  fenix/app/src/main/res/drawable-hdpi/cerulean.png
  fenix/app/src/main/res/drawable-hdpi/sunrise.jpg
  fenix/app/src/main/res/drawable-land-hdpi/amethyst.png
  fenix/app/src/main/res/drawable-land-hdpi/cerulean.png
  fenix/app/src/main/res/drawable-land-hdpi/sunrise.jpg
  fenix/app/src/main/res/drawable-land-night-hdpi/amethyst.png
  fenix/app/src/main/res/drawable-land-night-hdpi/cerulean.png
  fenix/app/src/main/res/drawable-land-night-xhdpi/amethyst.png
  fenix/app/src/main/res/drawable-land-night-xhdpi/cerulean.png
  fenix/app/src/main/res/drawable-land-night-xxhdpi/amethyst.png
  fenix/app/src/main/res/drawable-land-night-xxhdpi/cerulean.png
  fenix/app/src/main/res/drawable-land-xhdpi/amethyst.png
  fenix/app/src/main/res/drawable-land-xhdpi/cerulean.png
  fenix/app/src/main/res/drawable-land-xhdpi/sunrise.jpg
  fenix/app/src/main/res/drawable-land-xxhdpi/amethyst.png
  fenix/app/src/main/res/drawable-land-xxhdpi/cerulean.png
  fenix/app/src/main/res/drawable-land-xxhdpi/sunrise.jpg
  fenix/app/src/main/res/drawable-night-hdpi/amethyst.png
  fenix/app/src/main/res/drawable-night-hdpi/cerulean.png
  fenix/app/src/main/res/drawable-port-night-xhdpi/amethyst.png
  fenix/app/src/main/res/drawable-port-night-xhdpi/cerulean.png
  fenix/app/src/main/res/drawable-port-night-xxhdpi/amethyst.png
  fenix/app/src/main/res/drawable-port-night-xxhdpi/cerulean.png
  fenix/app/src/main/res/drawable-port-xhdpi/amethyst.png
  fenix/app/src/main/res/drawable-port-xhdpi/cerulean.png
  fenix/app/src/main/res/drawable-port-xhdpi/sunrise.jpg
  fenix/app/src/main/res/drawable-port-xxhdpi/amethyst.png
  fenix/app/src/main/res/drawable-port-xxhdpi/cerulean.png
  fenix/app/src/main/res/drawable-port-xxhdpi/sunrise.jpg
  fenix/app/src/main/res/drawable-xhdpi/amethyst.png
  fenix/app/src/main/res/drawable-xxhdpi/amethyst.png
  fenix/app/src/test/java/org/mozilla/fenix/wallpapers/LegacyWallpaperFileManagerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: 🛬 needs landing

#2084 Bug 1833690 - Update telemetry renewal script for easier navigation
  fenix/tools/data_renewal_generate.py
  focus-android/tools/data_renewal_generate.py
  focus-android/tools/data_renewal_request.py
Labels: 🛬 needs landing, approved

#2100 Bug 1833851 — Remove deprecated context param in FeatureHolder callers
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
Labels: 🛬 needs landing

#2093 Bug 1833765 - Update LeakCanary to version 2.11
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#2107 Bug 1833851 — Remove context param from FeatureHolder in Focus
  focus-android/app/src/main/java/org/mozilla/focus/cfr/CfrMiddleware.kt
  focus-android/app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/Settings.kt
  focus-android/app/src/test/java/org/mozilla/focus/cfr/CfrMiddlewareTest.kt
Labels: 🛬 needs landing

#2105 Bug 1833874 - Disables failing connectionFailureErrorMessageTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
Labels: 🛬 needs landing

#2091 Bug 1833755 - Update AndroidX Media to version 1.6.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2102 Bug 1833860 - Increase frequency of performance tests to twice a day.
  .cron.yml
Labels: 🛬 needs landing (squash)

#2098 Bug 1833655 - Add a GitHub workflow to automate adding labels and assignees to pull requests
  .github/workflows/pull-request-labeler.yml
Labels: 🛬 needs landing, approved

#2086 Bug 1826670 - Hide the close button on grid items when in multiselection
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
Labels: 🛬 needs landing, approved

#2082 Bug 1829361 - Add missing license to FindInPageIntegrationTest
  focus-android/app/src/test/java/org/mozilla/focus/browser/integration/FindInPageIntegrationTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#2106 Bug 1833886 - Update guide to merging contributor PRs doc
  fenix/docs/Guide-to-merging-contributor-PRs.md
Labels: 🛬 needs landing

#2113 Bug 1833655 - Bump pull-request-labeler action to 1.0.4
  .github/workflows/pull-request-labeler.yml
Labels: 🛬 needs landing, approved

#1997 Bug 1831602 - Convert two UI tests to support composified Tabs Tray
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/button/FloatingActionButton.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFab.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTestTag.kt
Labels: 🛬 needs landing, approved

#2112 Bug 1833939 - Remove Protobuf compiler workaround for Apple processors
  fenix/app/build.gradle
Labels: 🛬 needs landing, approved

#298 Bug 1804274: Adds entrypoints to firefox accounts interactions
  android-components/components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt
  android-components/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt
  android-components/components/feature/accounts/src/test/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeatureTest.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Utils.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/State.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/UtilsKtTest.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/manager/StateKtTest.kt
  android-components/samples/firefox-accounts/src/main/java/org/mozilla/samples/fxa/MainActivity.kt
  android-components/samples/firefox-accounts/src/main/java/org/mozilla/samples/fxa/SampleFxAEntryPoint.kt
  android-components/samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/MainActivity.kt
  android-components/samples/sync-logins/src/main/java/org/mozilla/samples/sync/logins/SampleFxAEntryPoint.kt
  android-components/samples/sync/src/main/java/org/mozilla/samples/sync/MainActivity.kt
  android-components/samples/sync/src/main/java/org/mozilla/samples/sync/SampleFxAEntryPoint.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/GlobalDirections.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/accounts/FenixFxAEntryPoint.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenuView.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkView.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/HomeOnboardingDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/PairFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountProblemFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/autofill/AutofillSettingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/ext/SyncedTabsViewErrorType.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/HomeMenuViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingManualSignInViewHolderTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/logins/SyncPreferenceViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/NavigationInteractorTest.kt
Labels: 🛬 needs landing, approved

#2111 Bug 1833933 - Disable CBR UI tests for investigation
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt
Labels: 🛬 needs landing, approved

#2062 Bug 1831287 - Adjust private mode searchbar color
  fenix/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  fenix/app/src/main/res/values/colors.xml
Labels: 🛬 needs landing, approved

#2126 Bug 1830870 - Disable failing closeTabTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Labels: 🛬 needs landing, approved

#1965 Bug 1827716 - Remove adveritising of TWA support in AndroidManifest
  android-components/samples/browser/src/main/AndroidManifest.xml
  fenix/app/src/main/AndroidManifest.xml
  fenix/app/src/nightly/AndroidManifest.xml
Labels: 🛬 needs landing, approved

#2104 Bug 1814030 - Fix cookie banner reduction UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing, approved

#2080 Bug 1833638 - remove client ID duplication code
  fenix/app/.experimenter.yaml
  fenix/app/metrics.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/pings.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationLifecycleObserver.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPing.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPingTest.kt
Labels: 🛬 needs landing, approved

#2129 Bug 1833655 - Bump pull-request-labeler action to 1.0.5
  .github/workflows/pull-request-labeler.yml
Labels: 🛬 needs landing, approved

#2059 Bug 1833115 - Migrate to compose foundation insets
  focus-android/app/build.gradle
  focus-android/app/src/main/java/org/mozilla/focus/settings/BaseComposeFragment.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#2118 Bug 1832606 - Convert `closeAllTabsTest` and add test tags
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/DropdownMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTestTag.kt
Labels: 🛬 needs landing, approved

#1727 Bug 1829363- Update Home.md
  focus-android/docs/Home.md
Labels: 🛬 needs landing, changes required

#2133 Bug 1833655 - Bump pull-request-labeler action to 1.0.6
  .github/workflows/pull-request-labeler.yml
Labels: 🛬 needs landing, approved

#2152 Bug 1807283 - Disable failing verifyJumpBackInSectionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: 🛬 needs landing

#2132 Bug 1833697 - Refactor `TabsTrayStore` into `TabsTrayBanner`
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
Labels: 🛬 needs landing, approved

#2127 Bug 1830870 - Fix disabled tab closing UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#2177 Bug 1834516 - Change the string for the cookie banner reduction report site button.
  fenix/app/src/main/res/layout/component_cookie_banner_details_panel.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#2158 Bug 1834300 - Update Search Engine URLs for Daum, Gule sider and Vatera.hu.
  android-components/components/feature/search/src/main/assets/searchplugins/daum-kr.xml
  android-components/components/feature/search/src/main/assets/searchplugins/gulesider-mobile-NO.xml
  android-components/components/feature/search/src/main/assets/searchplugins/vatera.xml
Labels: 🛬 needs landing, approved

#2163 Bug 1832610 - Convert `verifyPrivateTabUndoSnackBarTest`
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
Labels: 🛬 needs landing, approved

#2172 Bug 1812075 - Re-enable useAppWhileTabIsCrashedTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
Labels: 🛬 needs landing, approved

#2153 Bug 1807283 - Fix for verifyJumpBackInSectionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: 🛬 needs landing, approved

#1814 Bug 1810197 - Improve DownloadUtils.changeExtension.
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
Labels: 🛬 needs landing, approved

#2175 Bug 1834432 - Remove multidex references from firefox-android
  android-components/build.gradle
  focus-android/app/build.gradle
Labels: 🛬 needs landing, approved

#2139 Bug 1812859 - Update tabpreview's tab count when starting swipe
  fenix/app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt
Labels: 🛬 needs landing, approved

#2186 Bug 1828698 - Refactor `DropdownMenu` into a use case Composable
  fenix/app/src/main/java/org/mozilla/fenix/compose/Menu.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/collections/Collection.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentlyVisited.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
Labels: 🛬 needs landing, approved

#2187 Bug 1832611 - Re-enable `closePrivateTabsNotificationTest` for Compose
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
Labels: 🛬 needs landing, approved

#2000 Bug 1832676: Fixes handle push breaking changes
  android-components/components/concept/sync/src/main/java/mozilla/components/concept/sync/AccountEvent.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Types.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaDeviceConstellationTest.kt
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
  android-components/samples/sync/src/main/java/org/mozilla/samples/sync/MainActivity.kt
Labels: 🛬 needs landing, approved

#2206 Bug 1833756 - Remove unnecessary `selectionMode` parameter from normal and private tab pages
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
Labels: 🛬 needs landing, approved

#2188 Bug 1832613 - Convert `verifyEmptyTabTray`
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#2130 Bug 1822448 – Prevent tabs tray from being animated multiple times on older android versions
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/res/values/styles.xml
Labels: 🛬 needs landing, approved

#2173 Bug 1833348 - [Bug][downloads] "Try again" should work after the connection is reestablished.
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing, approved

#2218 Bug 1834766 - Fix device notifications screen navigation crash
  fenix/app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  fenix/app/src/main/java/org/mozilla/fenix/ext/Context.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: 🛬 needs landing, approved

#2220 Bug 1818729 - Removed duplicate dependencies
  android-components/components/support/ktx/build.gradle
Labels: 🛬 needs landing, approved

#2203 Bug 1805651 - Update taskgraph to 5.1.1 and use index-path-regexes
  taskcluster/android_taskgraph/__init__.py
  taskcluster/android_taskgraph/morph.py
  taskcluster/ci/config.yml
  taskcluster/requirements.in
  taskcluster/requirements.txt
Labels: 🛬 needs landing, approved

#2227 Bug 1805651 - fix index-path-regexes
  taskcluster/ci/config.yml
Labels: 🛬 needs landing

#2223 Bug 1835050 - Disable recorded video for Robo tests
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🛬 needs landing, approved

#2216 Bug 1832615 - Convert `verifyOpenTabDetails`
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTestTag.kt
Labels: 🛬 needs landing, approved

#2202 Bug 1808279 - Fix intermittent SettingsSearchTest.blockSearchSuggestionsInPrivateModeOnboardingTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: 🛬 needs landing, approved

#2040 Bug 1833093 - Add a Nimbus experiment for pdf.js
  android-components/.buildconfig.yml
  android-components/components/browser/engine-gecko/build.gradle
  android-components/components/browser/engine-gecko/geckoview.fml.yaml
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#2225 Bug 1835072 - Renew telemetry probes expiring in v117
  fenix/app/metrics.yaml
Labels: 🛬 needs landing, approved

#2208 Bug 1834844 - Remove `onEnterMultiselectModeClick` parameter from `TabsTrayBanner`
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
Labels: 🛬 needs landing, approved

#2224 Bug 1834924 - Add documentation to the generated LocalesList.
  focus-android/app/build.gradle
Labels: 🛬 needs landing, approved

#2228 Bug 1826453 - Refactor tab page button click metrics
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabLayoutMediator.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutObserverTest.kt
Labels: 🛬 needs landing, approved
