Repository mozilla-mobile/firefox-android, pull requests merged in 2023-01, with the labels that each got.

#465 Bug 1806884: tweak release push notification message
  taskcluster/ci/release-notify-push/kind.yml
Labels: 🛬 needs landing

#457 Bug 1808033 - Add content description for Dismiss Button in CFRPopupContent
  android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopupContent.kt
Labels: 🛬 needs landing, approved

#437 Upstream checking for device manufacturer for One Plus devices.
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ManufacturerCodes.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/ManufacturerCodesTest.kt
Labels: 🛬 needs landing

#407 Bug 1806652 - Downgrade appcompat and material libraries.
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#355 Bug 1805840 - Fix layout for add to home screen with ETP warning.
  focus-android/app/src/main/res/layout/dialog_add_to_homescreen2.xml
Labels: 🛬 needs landing

#475 Bug 1803358 - Add telemetry to check if notifications are allowed for Focus
  focus-android/app/metrics.yaml
  focus-android/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
Labels: 🛬 needs landing

#450 For Bug 1806093 Make camera permission's page scrollable in landscape mode
  focus-android/app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionsFragmentCompose.kt
Labels: 🛬 needs landing

#322 Bug 1797568 - Expose delegates for observing cookie banner handling events
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/CookieBannerStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/SessionState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/CookieBannerActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  docs/changelog.md
Labels: 🛬 needs landing

#484 Upstream checking for device manufacturer for LG devices.
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ManufacturerCodes.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/ManufacturerCodesTest.kt
Labels: 🛬 needs landing

#485 Bug 1808510 - Remove colon from a filename to avoid git clone issues on Windows
  focus-android/docs/Development-Custom-GeckoView.md
Labels: 🛬 needs landing

#424 Bug 1806924 - Add the API to allow to persist cookie banner handling exceptions in private
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorage.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorageTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/cookiehandling/CookieBannersStorage.kt
  docs/changelog.md
Labels: 🛬 needs landing

#478 Bug 1808338 - Update Sentry to version 6.11.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#452 Bug 1802975 - Allow crash dumps to be shared using Talkback
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/CrashListAdapter.kt
  docs/changelog.md
Labels: 🛬 needs landing

#357 Bug 1802607: UI tests workaround for ETP not loading on first run
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
Labels: 🛬 needs landing

#494 Bug 1808596 - Update release checklist documentation for AC/Focus
  docs/contribute/release_checklist.md
Labels: 🛬 needs landing

#506 Bug 1801022 - Update AndroidX testing libraries to the latest releases
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/sync/TypesTest.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#502 Bug 1802604 - Fix flaky firstRunOnboardingTest UI test
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/OldFirstRunTest.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.kt
Labels: 🛬 needs landing

#181 For #25810 - Unified search 'search popup menu' should give hint to the user that there are more menu items available by scrolling
  android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/BrowserMenuController.kt
  android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/ext/PopupWindow.kt
  android-components/components/browser/menu2/src/test/java/mozilla/components/browser/menu2/BrowserMenuControllerTest.kt
  android-components/components/browser/menu2/src/test/java/mozilla/components/browser/menu2/ext/PopupWindowTest.kt
  android-components/components/concept/menu/src/main/java/mozilla/components/concept/menu/MenuController.kt
Labels: 🛬 needs landing

#488 Bug 1804996: Replace and remove DDG Type Tags
  android-components/components/feature/search/src/main/assets/searchplugins/ddg.xml
  android-components/components/feature/search/src/main/assets/searchplugins/duckduckgo.xml
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/Utils.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#518 Update GeckoView (Release) to 109.0.20230109161414
  android-components/plugins/dependencies/src/main/java/Gecko.kt
Labels: 🛬 needs landing

#480 Bug 1808371 - Add a Bugzilla link automatically in GitHub pull requests
  .github/workflows/bugzilla-linker.yml
Labels: 🛬 needs landing, approved

#496 Bug 1808364 - Check for the correct PR title and commit message format
  .github/workflows/bugzilla-format.yml
Labels: 🛬 needs landing

#525 Bug 1809619 - Fix expected results on downloadAndOpenPdfFileTest
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/StringsHelper.kt
Labels: 🛬 needs landing

#528 Bug 1808364 - Part 2: Bump bugzilla-format action to ignore commit messages that starts with "Merge"
  .github/workflows/bugzilla-format.yml
Labels: 🛬 needs landing

#486 Bug 1809609 - adds UI test page content assertion and retries
  focus-android/app/src/androidTest/assets/etpPages/adsTrackers.html
  focus-android/app/src/androidTest/assets/etpPages/analyticsTrackers.html
  focus-android/app/src/androidTest/assets/etpPages/otherTrackers.html
  focus-android/app/src/androidTest/assets/etpPages/socialTrackers.html
  focus-android/app/src/androidTest/assets/storage_check.html
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
Labels: 🛬 needs landing

#388 Bug 1797600 - Create cookie banner cfr
  focus-android/app/metrics.yaml
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/FeatureSettingsHelper.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  focus-android/app/src/main/java/org/mozilla/focus/cfr/CfrMiddleware.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebanner/CookieBannerFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebanner/CookieBannerOption.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerexception/CookieBannerExceptionDetailsPanel.kt
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerexception/CookieBannerExceptionMiddleware.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/state/AppAction.kt
  focus-android/app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  focus-android/app/src/main/java/org/mozilla/focus/state/AppState.kt
  focus-android/app/src/main/java/org/mozilla/focus/ui/theme/FocusTypography.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/ClickableSubstringLink.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/Settings.kt
  focus-android/app/src/main/res/values/preference_keys.xml
  focus-android/app/src/main/res/values/strings.xml
  focus-android/app/src/main/res/xml/cookie_banner_settings.xml
  focus-android/app/src/test/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegrationTest.kt
Labels: 🛬 needs landing

#532 Bug 1809859 - Let focus UI tests run when A-C dependencies and gradle…
  taskcluster/android_taskgraph/transforms/gradle_optimization.py
Labels: 🛬 needs landing (squash)

#535 Bug 1805407 - Ship v110.0.0 of the WebCompat System Addon.
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1743614-storytel.com-flex-min-width.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1768243-cloud.google.com-allow-table-scrolling.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics-and-tag-manager.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-ima.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/microsoftVirtualAssistant.js
Labels: 🛬 needs landing

#515 Bug 1808672 - adding local assets for cookie settings UI tests, improved coverage
  focus-android/app/src/androidTest/assets/cross-site-cookies.html
  focus-android/app/src/androidTest/assets/same-site-cookies.html
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SettingsPrivacyTest.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
Labels: 🛬 needs landing

#550 Start 111 development cycle
  android-components/plugins/dependencies/src/main/java/Gecko.kt
  docs/changelog.md
  version.txt
Labels: 🛬 needs landing

#540 Bug 1809972 - Cookie banner CFR: code should not try to replace localized text when it can pass a variable
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#554 Bug 1809921 - Address crash when visit internal sites like about config when cookie banner is ON
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorage.kt
Labels: 🛬 needs landing

#557 Bug 1809972 - Part 2: Use the correct moz:RemovedIn version for cookie banner CFR strings
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#558 Update implementation of dependency
  focus-android/app/build.gradle
Labels: 🛬 needs landing

#264 Bug 1800146 - Set tab's GeckoSession priority based on form data
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/SessionPrioritizationMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/SessionPrioritizationMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
Labels: 🛬 needs landing

#571 Bug 1811093 - Exclude dependabot and MickeyMoz from the bugzilla commit format check
  .github/workflows/bugzilla-format.yml
Labels: 🛬 needs landing

#578 Revert downloads changes for ui tests failures downstream.
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehavior.kt
  android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehaviorTest.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadDialogFragment.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/DownloadState.kt
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ui/DownloaderAppAdapter.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/ext/DownloadStateKtTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#579 Clean changelog following revert of downloads changes
  docs/changelog.md
Labels: 🛬 needs landing

#572 Bug 1809972 - Part 3: Re-add the removed localization string comments for the cookie banner CFR
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#580 Bug 1811280 - Add worker retry on Firebase infrastructure error
  taskcluster/ci/ui-test-focus/kind.yml
Labels: 🛬 needs landing

#588 Bug 1811490 - Add < at the start of each of the localization comment
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#537 Bug 1811480 - update nimbus-experiments job action versions
  .github/workflows/focus-update-nimbus-experiments.yml
Labels: 🛬 needs landing

#559 Bug 1810743 - Expose detect-only setting in AC
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#611 Bug 1810743 - Add cookieBannerHandlingDetectOnlyMode as part of the defaultSettings
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
Labels: 🛬 needs landing, approved

#527 Bug 1806798 - Better handle longer filenames in download confirmation dialog.
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragment.kt
  android-components/components/feature/downloads/src/main/res/layout/mozac_downloads_prompt.xml
Labels: 🛬 needs landing, approved

#577 Bug 1808678 - Focus should not crash if the app is sent to the background after the "Send usage data" toggle is enabled.
  focus-android/app/src/main/java/org/mozilla/focus/widget/TelemetrySwitchPreference.kt
Labels: 🛬 needs landing

#586 Bug 1811448 - Expose the GeckoView release channel in EngineVersion utils
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/utils/EngineVersion.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/utils/EngineVersionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#603 Bug 1811183 - Handle non-digit step values passed for time input
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#621 Bug 1812378 - Fix cookie_banner_exception_panel_description_state_off_for_site string
  focus-android/app/src/main/java/org/mozilla/focus/cookiebannerexception/CookieBannerExceptionDetailsPanel.kt
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#629 Revert "Bug 1796348 - Add post notification permission requirement for downloads."
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
Labels: 🛬 needs landing

#632 Bug 1810553 - Update Focus expiring telemetry
  focus-android/app/metrics.yaml
Labels: 🛬 needs landing, approved

#633 Bug 1797245 - Use the same branch names for the update nimbus experiments action
  .github/workflows/focus-update-nimbus-experiments.yml
Labels: 🛬 needs landing

#98 Bug 1798672 - Autosize reader mode controls text
  android-components/components/feature/readerview/src/main/res/layout/mozac_feature_readerview_view.xml
  docs/changelog.md
Labels: 🛬 needs landing

#617 Bug 1811801 - Use [bug ticket_number] format for previous changelog entries
  docs/changelog.md
Labels: 🛬 needs landing, approved

#639 Bug 1802214 - Remove redundant getAppLaunchCount.
  focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/Settings.kt
  focus-android/app/src/main/res/values/preference_keys.xml
  focus-android/quality/detekt-baseline.xml
Labels: 🛬 needs landing

#640 Bug 1813157 - Use the new l10n import action for the monorepo
  .github/workflows/import-l10n.yml
Labels: 🛬 needs landing

#662 Bug 1811937 - adjust clear icon size in browser toolbar
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_clear.xml
Labels: 🛬 needs landing, approved

#666 Bug 1814130 - Add prompt to "open in app" in normal tabs
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/SimpleRedirectDialogFragment.kt
  android-components/components/feature/app-links/src/main/res/values/strings.xml
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/SimpleRedirectDialogFragmentTest.kt
Labels: 🛬 needs landing, approved

#656 Bug 1812976 - Re-enabled camera permissions tests
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SitePermissionsTest.kt
Labels: 🛬 needs landing
