Repository mozilla-mobile/firefox-android, pull requests merged in 2023-09, with the labels that each got.

#3455 Bug 1851012 – aligned Search Engine Suggestion Provider behaviour with Desktop
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchEngineSuggestionProvider.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchEngineSuggestionProviderTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3334 Bug 1845098 - detect external-gradle-dependencies hangs and automatic…
  taskcluster/ci/external-gradle-dependencies/kind.yml
  taskcluster/scripts/toolchain/external-gradle-dependencies.sh
Labels: 🛬 needs landing, approved

#3366 Bug 1849848 - New search history in private browsing UI smoke test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeBookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHistoryTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: 🛬 needs landing, approved

#3464 Bug 1807268 - Disable failing deleteCachedFilesTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt
Labels: 🛬 needs landing, approved

#3447 Bug 1848860 - Do not prompt to save/update credit card unless all required fields are present
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
Labels: 🛬 needs landing, approved

#3335 Bug 1845098 - stop passing --parallel to gradle in external-gradle-de…
  taskcluster/scripts/toolchain/external-gradle-dependencies.sh
Labels: 🛬 needs landing, approved

#2995 Bug 1833493 - Update Tab List Item title and url text style
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
  fenix/app/src/main/res/layout/tab_tray_item.xml
Labels: 🛬 needs landing, approved

#3459 Bug 1819737 - Added extensions process crash handling
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionDelegate.kt
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
Labels: 🛬 needs landing, approved

#3022 Bug 1833693: refactor menu items list creation
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/ext/TabsTrayState.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayStateTest.kt
Labels: 🛬 needs landing, approved

#3230 Bug 1848349 - Sponsored shortcuts TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt
Labels: 🛬 needs landing, approved

#3358 Bug 1849576 - Navigation toolbar TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MockWebServer.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeNavigationToolbarTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextualHintsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MainMenuTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/automation/taskcluster/androidTest/flank-arm-beta.yml
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-start-test.yml
Labels: 🛬 needs landing, approved

#1319 Bug 1807126 - Increased gap between slider and scale value
  fenix/app/src/main/res/layout/layout_percentage_seek_bar.xml
Labels: 🛬 needs landing, approved

#3468 Bug 1851186 - Add new design system color tokens
  android-components/components/ui/colors/src/main/java/mozilla/components/ui/colors/PhotonColors.kt
  android-components/components/ui/colors/src/main/res/values/photon_colors.xml
  fenix/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  fenix/app/src/main/res/values-night/colors.xml
  fenix/app/src/main/res/values/colors.xml
Labels: 🛬 needs landing, approved

#2993 Bug 1839513 - Pass crash reporter to SessionStorage
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: 🛬 needs landing, approved

#3476 Bug 1851213 - Prefix Application Services dependency
  android-components/components/browser/storage-sync/build.gradle
  android-components/components/feature/fxsuggest/build.gradle
  android-components/components/feature/push/build.gradle
  android-components/components/service/firefox-accounts/build.gradle
  android-components/components/service/nimbus/build.gradle
  android-components/components/service/sync-autofill/build.gradle
  android-components/components/service/sync-logins/build.gradle
  android-components/components/support/rusterrors/build.gradle
  android-components/components/support/rusthttp/build.gradle
  android-components/components/support/rustlog/build.gradle
  android-components/components/support/test-appservices/build.gradle
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3368 Bug 1839967 - Updated the Firefox Browser imagery assets.
  fenix/app/src/beta/res/drawable-hdpi/ic_logo_wordmark_normal.png
  fenix/app/src/beta/res/drawable-hdpi/ic_logo_wordmark_private.png
  fenix/app/src/beta/res/drawable-mdpi/ic_logo_wordmark_normal.png
  fenix/app/src/beta/res/drawable-mdpi/ic_logo_wordmark_private.png
  fenix/app/src/beta/res/drawable-xhdpi/ic_logo_wordmark_normal.png
  fenix/app/src/beta/res/drawable-xhdpi/ic_logo_wordmark_private.png
  fenix/app/src/beta/res/drawable-xxhdpi/ic_logo_wordmark_normal.png
  fenix/app/src/beta/res/drawable-xxhdpi/ic_logo_wordmark_private.png
  fenix/app/src/beta/res/drawable-xxxhdpi/ic_logo_wordmark_normal.png
  fenix/app/src/beta/res/drawable-xxxhdpi/ic_logo_wordmark_private.png
  fenix/app/src/beta/res/drawable/ic_wordmark_text_normal.png
  fenix/app/src/beta/res/drawable/ic_wordmark_text_private.png
  fenix/app/src/nightly/res/drawable-hdpi/ic_logo_wordmark_normal.png
  fenix/app/src/nightly/res/drawable-hdpi/ic_logo_wordmark_private.png
  fenix/app/src/nightly/res/drawable-mdpi/ic_logo_wordmark_normal.png
  fenix/app/src/nightly/res/drawable-mdpi/ic_logo_wordmark_private.png
  fenix/app/src/nightly/res/drawable-xhdpi/ic_logo_wordmark_normal.png
  fenix/app/src/nightly/res/drawable-xhdpi/ic_logo_wordmark_private.png
  fenix/app/src/nightly/res/drawable-xxhdpi/ic_logo_wordmark_normal.png
  fenix/app/src/nightly/res/drawable-xxhdpi/ic_logo_wordmark_private.png
  fenix/app/src/nightly/res/drawable-xxxhdpi/ic_logo_wordmark_normal.png
  fenix/app/src/nightly/res/drawable-xxxhdpi/ic_logo_wordmark_private.png
  fenix/app/src/nightly/res/drawable/ic_wordmark_text_normal.png
  fenix/app/src/nightly/res/drawable/ic_wordmark_text_private.png
  fenix/app/src/release/res/drawable-hdpi/ic_logo_wordmark_normal.png
  fenix/app/src/release/res/drawable-hdpi/ic_logo_wordmark_private.png
  fenix/app/src/release/res/drawable-mdpi/ic_logo_wordmark_normal.png
  fenix/app/src/release/res/drawable-mdpi/ic_logo_wordmark_private.png
  fenix/app/src/release/res/drawable-xhdpi/ic_logo_wordmark_normal.png
  fenix/app/src/release/res/drawable-xhdpi/ic_logo_wordmark_private.png
  fenix/app/src/release/res/drawable-xxhdpi/ic_logo_wordmark_normal.png
  fenix/app/src/release/res/drawable-xxhdpi/ic_logo_wordmark_private.png
  fenix/app/src/release/res/drawable-xxxhdpi/ic_logo_wordmark_normal.png
  fenix/app/src/release/res/drawable-xxxhdpi/ic_logo_wordmark_private.png
  fenix/app/src/release/res/drawable/ic_wordmark_text_normal.png
  fenix/app/src/release/res/drawable/ic_wordmark_text_private.png
Labels: 🛬 needs landing, approved

#3497 Bug 1851543 - Cleanup old Onboarding UI test code
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddToHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DeepLinkTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusEventTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PocketTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#3265 Bug 1848605 - Implement similar functionality as loadIntoView for Compose Top Sites
  android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/Favicon.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
Labels: 🛬 needs landing, approved

#3518 Bug 1721904 - update thumbnail caching on app open
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  android-components/components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt
  android-components/components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/DefaultTabViewHolderTest.kt
  android-components/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/ThumbnailsMiddleware.kt
  android-components/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/storage/ThumbnailStorage.kt
  android-components/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/utils/ThumbnailDiskCache.kt
  android-components/components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/ThumbnailsMiddlewareTest.kt
  android-components/components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/loader/ThumbnailLoaderTest.kt
  android-components/components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/storage/ThumbnailStorageTest.kt
  android-components/components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/utils/ThumbnailDiskCacheTest.kt
  android-components/components/concept/base/src/main/java/mozilla/components/concept/base/images/ImageRequest.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/TabThumbnail.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ThumbnailImage.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/AbstractBrowserTabViewHolder.kt
Labels: 🛬 needs landing, approved

#3434 Bug 1850761 - Allow for local usage of experiment integration test suite
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/Pipfile
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/Pipfile.lock
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/conftest.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/pytest.ini
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/test_integration.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/variables.yaml
Labels: 🛬 needs landing, approved

#3432 Bug 1850493 - The tracking protection divider should be gone if all the views are gone.
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsSheetDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/ProtectionsView.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/ProtectionsViewTest.kt
Labels: 🛬 needs landing, approved

#3527 Bug 1851961 - Upgrade compose to version 1.5.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3512 Bug 1815395 - Disable failing audio-video permissions UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSitePermissionsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
Labels: 🛬 needs landing, approved

#3515 Bug 1851826 - Turn off Fenix mozillaonline builds
  taskcluster/ci/build-apk/kind.yml
  taskcluster/ci/signing-apk/kind.yml
Labels: 🛬 needs landing (squash), approved

#3534 Bug 1847141 - Remove hardcoding of RECEIVE_DOWNLOAD_BROADCAST_PERMISSION
  android-components/components/feature/downloads/src/main/AndroidManifest.xml
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  docs/changelog.md
  fenix/app/src/main/AndroidManifest.xml
  focus-android/app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing, approved

#3532 Bug 1852007 - Upgrade core to version 1.12.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3535 Bug 1852002 - Update AndroidX Lifecycle to version 2.6.2
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/build.gradle
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3233 Bug 1844319 - Add review quality check CFR
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferences.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferencesMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#3539 Bug 1852087 - Update AndroidX Paging to version 3.2.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3540 Bug 1852089 - Update AndroidX Annotation to version 1.7.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3542 Bug 1852090 - Update AndroidX Browser to version 1.6.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3519 Bug 1847575 - Create UI component for shopping analysis status
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckInfoCard.kt
Labels: 🛬 needs landing, approved

#3522 Bug 1851678 - Catch AutofillApiException exception when fetching autofill data and setting startup metrics
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing, approved

#3281 Bug 1845613 – restore hidden engines for unified search settings
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SearchReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/SearchActionTest.kt
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/SearchUseCases.kt
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/middleware/SearchMiddleware.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/SearchUseCasesTest.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/middleware/SearchMiddlewareTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing, approved

#2697 Bug 1841572 – removed extra spacing from the bookmark menu item
  android-components/components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_text_checkbox_button.xml
  android-components/components/browser/menu/src/main/res/values/dimens.xml
  android-components/components/browser/menu/src/main/res/values/style.xml
  fenix/app/src/main/res/values/dimens.xml
Labels: 🛬 needs landing, approved

#2962 Bug 1829018 - Remove and clean up `Settings.enableTaskContinuityEnhancements`
  fenix/app/src/main/java/org/mozilla/fenix/ext/AppState.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/ext/SyncedDeviceTabs.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabsIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/viewholders/SyncedTabsPageViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
  fenix/app/src/test/java/org/mozilla/fenix/sync/ext/SyncedDeviceTabsTest.kt
Labels: 🛬 needs landing, approved

#3467 Bug 1844960 - Bookmark suggestions should appear unconcerned with the search suggestions setting.
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt
  android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt
Labels: 🛬 needs landing, approved

#3528 Bug 1851006 - SearchEngineSuggestionProvider should always be added to the provider list.
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
Labels: 🛬 needs landing

#3431 Bug 1850730 - General settings TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsCustomizeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Labels: 🛬 needs landing, approved

#3556 Bug 1851419 - Disable searchHistoryNotRememberedInPrivateBrowsingTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: 🛬 needs landing, approved

#3549 Bug 1852097 - Update AndroidX Recyclerview to version 1.3.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3552 Bug 1852180 - Update Mockito to version 5.5.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3558 Bug 1825116 - fix a couple of typos
  docs/changelog.md
  taskcluster/android_taskgraph/loader/build_config.py
Labels: 🛬 needs landing, approved

#3561 Bug 1825116 - add missing MPL header to upstream_artifacts transform
  taskcluster/android_taskgraph/transforms/upstream_artifacts.py
Labels: 🛬 needs landing, approved

#3283 Bug 1847819 - Add new Homescreen description for Total Private Browsing mode
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/FeltPrivacyInfoCard.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3562 Bug 1851548 - Top sites are aligned to the left with Compose Top Sites enabled
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
Labels: 🛬 needs landing, approved

#3482 Bug 1843735 - Update title/artist/artwork in MediaMetadata
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/ext/SessionState.kt
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
  android-components/components/feature/media/src/test/java/mozilla/components/feature/media/ext/SessionStateKtTest.kt
  android-components/components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaSessionServiceDelegateTest.kt
Labels: 🛬 needs landing, approved

#3559 Bug 1825116 - add license info to animated_splash_screen.xml
  fenix/app/src/beta/res/drawable/animated_splash_screen.xml
  fenix/app/src/debug/res/drawable/animated_splash_screen.xml
  fenix/app/src/main/res/drawable/animated_splash_screen.xml
  fenix/app/src/nightly/res/drawable/animated_splash_screen.xml
  fenix/app/src/release/res/drawable/animated_splash_screen.xml
Labels: 🛬 needs landing, approved

#3584 Bug 1825116 - delete trailing whitespace from docs
  docs/changelog.md
  docs/rfcs/0009-remove-interactors-and-controllers.md
  fenix/docs/architecture-overview.md
Labels: 🛬 needs landing, approved

#3563 Revert "Bug 1845235 - Add "Private" label to Felt Privacy mode home screen
  fenix/app/src/main/res/drawable/ic_wordmark_text_felt_privacy.png
  fenix/app/src/main/res/layout/fragment_home.xml
  fenix/app/src/main/res/values/attrs.xml
  fenix/app/src/main/res/values/dimens.xml
  fenix/app/src/main/res/values/styles.xml
Labels: 🛬 needs landing, approved

#3555 Bug 1843536 - Fix tab reordering animation issues
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ReorderableGrid.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ReorderableList.kt
Labels: 🛬 needs landing, approved

#3530 Bug 1852533 - Main menu tests TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddToHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MainMenuTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PDFViewerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  fenix/automation/taskcluster/androidTest/flank-arm-beta.yml
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-start-test.yml
Labels: 🛬 needs landing, approved

#3473 Bug 1850933 - Override onProvideAssistContent in ExternalAppBrowserActivity
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
Labels: 🛬 needs landing, approved

#3525 Bug 1851950 - Update Firebase Cloud Messaging to version 23.2.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#3605 Bug 1852803 - Disable verifyCookieBannerReductionTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt
Labels: 🛬 needs landing, approved

#2987 Bug 1845292 - Remember scroll position in BookmarkView
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkView.kt
Labels: 🛬 needs landing, approved

#3390 Bug 1840090 - Add content strings for shopping experience
  fenix/app/src/main/java/org/mozilla/fenix/compose/String.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3604 Bug 1851691 - FeatureFlag and Debug Preferences for Translations
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
Labels: 🛬 needs landing, approved

#3286 Bug 1849031 - Remove SQLCipher migration calls
  android-components/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3599 Bug 1852623 - Fix list tab reordering animation when dragging first element
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ReorderableList.kt
Labels: 🛬 needs landing, approved

#3603 Bug 1852748 - Add quotes around each highlight snippet
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
Labels: 🛬 needs landing, approved

#3601 Bug 1841600 - Add review checker shopping icons
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_competitiveness_24.xml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_packaging_24.xml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_price_24.xml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_quality_24.xml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_shipping_24.xml
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_shopping_24.xml
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/res/drawable/ic_shopping_cart.xml
Labels: 🛬 needs landing, approved

#3261 Bug 1845020 - The hint for search suggestions in private mode should be disabled if search suggestions in normal browsing are disabled.
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
Labels: 🛬 needs landing

#3616 Bug 1846941 - Wait for media button to appear in tabMediaControlButtonTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#3296 Bug 1847024 - Create update analysis card component
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckInfoCard.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#3622 Bug 1852984 - Show the right theme for the extensions process crash dialog
  fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionProcessDisabledController.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionProcessDisabledControllerTest.kt
Labels: 🛬 needs landing, approved

#3586 Bug 1852305 - Add review grade info to all error states
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckSettingsCard.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityInfoCard.kt
Labels: 🛬 needs landing, approved

#3565 Bug 1852335 - Renamed WebExtensionPopupFeature and ExtensionProcessDi…
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/ExtensionProcessDisabledPopupObserver.kt
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionPopupObserver.kt
  android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionPopupObserverTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionProcessDisabledController.kt
Labels: 🛬 needs landing, approved

#2970 Bug 1845039 - Create new UI Tests for Compose Top Sites
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTopSitesRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesTestTag.kt
Labels: 🛬 needs landing, approved

#3631 Bug 1853070 - Remove deprecated AddNewPrivateTabUseCase
  android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt
  android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
  android-components/config/detekt-baseline.xml
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3529 Bug 1851974 - Add Oppo to the strict mode exclusion list
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ManufacturerCodes.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/ManufacturerCodesTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/perf/StrictModeManager.kt
Labels: 🛬 needs landing, approved

#3642 Bug 1853102 - Crash dialog "Continue with add-ons disabled" option is truncated on some devices.
  fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionProcessDisabledController.kt
  fenix/app/src/main/res/layout/crash_extension_dialog.xml
  fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionProcessDisabledControllerTest.kt
Labels: 🛬 needs landing, approved

#3627 Bug 1852925 - Update review grade colors
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewGrade.kt
Labels: 🛬 needs landing, approved

#3628 Bug 1852994 - Add review quality check byline
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckFooter.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3640 Bug 1851711 - Update highlights bottom fade and show more button visibility behaviour
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
Labels: 🛬 needs landing, approved

#3644 Bug 1853146 - Privacy settings TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHTTPSOnlyModeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivateBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSitePermissionsTest.kt
Labels: 🛬 needs landing, approved

#3658 Bug 1853270 - Add LoadUrlFlag flag to allow additional headers
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
Labels: 🛬 needs landing, approved

#3665 Bug 1845232 - Removes whitespace
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3667 Bug 1853421 - Fix shopping footer string
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckFooter.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3630 Bug 1853072 - Fix formatting and bugzilla references in changelog.md
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3608 Bug 1846306 - Do not throw IllegalStateException when unable to find a session for a given prompt request in onContentPermissionRequested
  android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt
  android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt
Labels: 🛬 needs landing, approved

#3557 Bug 1851419 - Fix searchHistoryNotRememberedInPrivateBrowsingTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: 🛬 needs landing, approved

#3641 Bug 1807275 - Verify only the intent sent in emailLinkPWATest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
Labels: 🛬 needs landing, approved

#3618 Bug 1850407 - Add nimbus flag for review checker product recommendations
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferences.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferencesMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckSettingsCard.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#3428 Bug 1795650 - Status bar and navigation bar colours should be the same, like toolbar colours.
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
Labels: 🛬 needs landing

#3621 Bug 1850165 - The useragent_locale crash annotation should be reported the same as on desktop.
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt
  android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/service/MozillaSocorroServiceTest.kt
Labels: 🛬 needs landing, approved

#3668 Bug 1853413 - Remove references to an old naming of the shopper footer as "byline"
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
Labels: 🛬 needs landing, approved

#3695 Bug 1853013 - Ship 118.3.0 of feature-webcompat
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/aboutConfigPrefs.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/aboutConfigPrefs.json
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/aboutConfigPrefsChild.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
Labels: 🛬 needs landing

#3663 Bug 1840090 - Update content description string for shopping experience
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3689 Bug 1853654 - Advanced settings TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Labels: 🛬 needs landing, approved

#3602 Bug 1851586 - UI tests: replace external apps links with workarounds
  fenix/app/src/androidTest/assets/pages/externalLinks.html
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing, approved

#3502 Bug 1851676 - Adds ability to initialize Sentry on startup
  android-components/components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
Labels: 🛬 needs landing, approved

#3625 Bug 1853045 - Add nimbus homescreen survey message integration test - Dismiss survey
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/SurveyExperimentIntegrationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/test_integration.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing (squash), approved

#3702 Bug 1853707 - Send Search Widget telemetry when primary button tapped
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingScreen.kt
Labels: 🛬 needs landing, approved

#3690 Bug 1853177 - Avoid multiple crash dialogs to be created and shown
  fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionProcessDisabledController.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionProcessDisabledControllerTest.kt
Labels: 🛬 needs landing, approved

#3696 Bug 1853309 - Expose Creating Shopping Analysis API
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3705 Bug 1850783 - Add button to open AMO from the fenix add-on manager
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterDelegate.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt
  android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_footer_section_item.xml
  android-components/components/feature/addons/src/main/res/values/strings.xml
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementView.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementViewTest.kt
Labels: 🛬 needs landing, approved

#3716 Bug 1852477 - Change the device's RAM threshold
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing, approved

#3704 Bug 1853967 - Capture telemetry for the amount of RAM a device has.
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: 🛬 needs landing, approved

#3650 Bug 1852802 - Prevents search suggestion prompt in private mode when felt privacy is enabled
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
Labels: 🛬 needs landing, approved

#3699 Bug 1853626 - Fix flaky verifyRenameTopSite UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTopSitesRobot.kt
Labels: 🛬 needs landing, approved

#3666 Bug 1848562 - Autocomplete for bookmarked website should appear when 'search browsing history' is disabled.
  fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: 🛬 needs landing, approved

#3715 Bug 1847569 - Add reanalysis loading card
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3722 Bug 1854150 - ci: use the taskgraph "decision" image instead of "deci…
  .taskcluster.yml
Labels: 🛬 needs landing, approved

#3714 Bug 1854065 - Use default prefix for implementations
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/NetworkChecker.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferences.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/DefaultReviewQualityCheckServiceTest.kt
Labels: 🛬 needs landing, approved

#3712 Bug 1840113 - Display review checker info cards
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
Labels: 🛬 needs landing, approved

#3662 Bug 1853382 - SettingsAboutTest TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAboutTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
Labels: 🛬 needs landing, approved

#3738 Bug 1854429 - Temporarily remove Pixel3 for low capacity
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#3741 Bug 1853065 - Fix TabsUseCasesTest merge conflict
  android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
Labels: 🛬 needs landing

#3623 Bug 1848842 - Increase APK regression alert's threshold to 1 MB
  fenix/plugins/apksize/src/main/java/ApkSizePlugin.kt
Labels: 🛬 needs landing, approved

#2594 Bug 1837526 - Call StartupTimeline in the Compose Top Sites
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/perf/StartupReportFullyDrawn.kt
  fenix/app/src/main/java/org/mozilla/fenix/perf/StartupTimeline.kt
Labels: 🛬 needs landing, approved

#3713 Bug 1853113 - Monitor Search Widget presence based on activation
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt
Labels: 🛬 needs landing, approved

#3747 Bug 1854570 - Restore Pixel 3 for legacy and robo UI tests
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Labels: 🛬 needs landing, approved

#3227 Bug 1848188 - Remove Nimbus flag for Juno Onboarding
  fenix/app/.experimenter.yaml
  fenix/app/onboarding.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: 🛬 needs landing, approved

#3755 Bug 1854700 - Only open history item if host activity is available
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
Labels: 🛬 needs landing, approved

#3708 Bug 1851268 - Show Firefox Suggest search suggestions in Fenix.
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestIngestionScheduler.kt
  fenix/.buildconfig.yml
  fenix/app/.experimenter.yaml
  fenix/app/build.gradle
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/FxSuggest.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/search_settings_preferences.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
  fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/search/SearchEngineFragmentTest.kt
Labels: 🛬 needs landing, approved

#3762 Bug 1854739 - Migrate pref_key_search_widget_installed
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: 🛬 needs landing, approved

#3758 Bug 1811976 - Hide Sync FAB in TabsTray when user not signed in
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/FloatingActionButtonBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFab.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/FloatingActionButtonBindingTest.kt
Labels: 🛬 needs landing, approved

#3767 Bug 1854739 - Catch crash when migrating pref_key_search_widget_installed
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: 🛬 needs landing, approved

#3752 Bug 1854631 - Refactor review checker info card
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckCards.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckInfoCard.kt
Labels: 🛬 needs landing, approved

#3737 Bug 1853311 - Add review checker reanalysis logic
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/Retry.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeNetworkChecker.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckPreferences.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/RetryKtTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#3751 Bug 1853639 - Downloads TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadFileTypesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: 🛬 needs landing, approved

#3749 Bug 1854606 - History TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHistoryTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  fenix/automation/taskcluster/androidTest/flank-arm-beta.yml
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-start-test.yml
Labels: 🛬 needs landing, approved

#3771 Bug 1854935 - Enable extensions process by default on Nightly and debug builds
  fenix/app/nimbus.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/extensions/ExtensionProcessTest.kt
Labels: 🛬 needs landing, approved

#3769 Bug 1847172 - Unconditionally enable the `mozAddonManager` web API on Fenix
  fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
Labels: 🛬 needs landing, approved

#3770 Bug 1854123 - Show the "find more add-ons" button unconditionally in Fenix
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementView.kt
Labels: 🛬 needs landing, approved

#3307 Bug 1848791 - Use min/maxTime for TimeStepPickerDialog
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/TimePickerDialogFragment.kt
Labels: 🛬 needs landing, approved

#3754 Revert "Bug 1843610 - Add telemetry for deferred deep link test"
  fenix/app/metrics.yaml
  fenix/app/src/main/AndroidManifest.xml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessor.kt
Labels: 🛬 needs landing, approved

#3777 Bug 1855029 - Start the 120 development cycle
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3756 Bug 1854709 - Add Store actions for remaining History interactor calls
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragmentStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/state/HistoryNavigationMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/state/HistoryNavigationMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#3744 Bug 1852928 - Update review quality check bottom sheet header
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#3717 Bug 1853301 - Refactor ReviewQualityCheckNavigationMiddleware to use TabsUseCases and SessionUseCases
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/NoAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckFooter.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityInfoCard.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#3693 Bug 1567912 - Add beetmover-bundle task
  taskcluster/android_taskgraph/manifests/apk_releases.yml
  taskcluster/android_taskgraph/transforms/beetmover_android_app.py
  taskcluster/ci/beetmover-android-app/kind.yml
Labels: 🛬 needs landing (squash), approved

#3726 Bug 1854173 - Add nimbus messaging integration test - Landscape UI
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/SurveyExperimentIntegrationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/conftest.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/test_integration.py
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing (squash), approved

#3776 Bug 1844557 - Disable the switch control when the add-on is blockedlisted.
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/webextension/WebExtensionTest.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/test/java/AddonManagerTest.kt
  android-components/components/feature/addons/src/test/java/AddonTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragmentTest.kt
Labels: 🛬 needs landing

#3804 Bug 1854712 - Update `information_fill` icon
  android-components/components/ui/icons/src/main/res/drawable/mozac_ic_information_fill_24.xml
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckInfoCard.kt
Labels: 🛬 needs landing, approved

#3796 Bug 1855224 - Update tippy top 200 icons list
  android-components/components/browser/icons/src/main/assets/mozac.browser.icons/icons-top200.json
  android-components/components/browser/icons/src/test/java/mozilla/components/browser/icons/BrowserIconsTest.kt
  android-components/components/browser/icons/src/test/java/mozilla/components/browser/icons/preparer/TippyTopIconPreparerTest.kt
Labels: 🛬 needs landing, approved

#3783 Bug 1854141 - Add AC tests for reanalyzeProduct and requestAnalysisStatus
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
Labels: 🛬 needs landing, approved

#3791 Bug 1855183 - Search settings menu TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
  fenix/automation/taskcluster/androidTest/flank-arm-beta.yml
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
  fenix/automation/taskcluster/androidTest/flank-arm-start-test.yml
Labels: 🛬 needs landing, approved

#3792 Bug 1855190 - Unified search bar TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Labels: 🛬 needs landing, approved

#3794 Bug 1855137 - Add review checker vendor ordering logic
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferencesMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckVendorsService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeNetworkChecker.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckVendorsService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/DefaultReviewQualityCheckVendorsServiceTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#3798 Bug 1847063 - Disable review checker in private mode
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ShoppingProductStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/reducer/ShoppingProductStateReducerTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#3801 Bug 1849073 - Part 2: Remove the History Search Dialog
  fenix/app/src/main/java/org/mozilla/fenix/BrowserDirection.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistorySearchController.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistorySearchDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistorySearchDialogInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/HistorySearchFragmentStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/awesomebar/AwesomeBarInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/awesomebar/AwesomeBarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/awesomebar/AwesomeBarWrapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/toolbar/ToolbarView.kt
  fenix/app/src/main/res/layout/fragment_history_search_dialog.xml
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/test/java/org/mozilla/fenix/library/history/HistoryControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/HistorySearchControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/HistorySearchDialogInteractorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/library/history/HistorySearchFragmentStoreTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/DefaultReviewQualityCheckServiceTest.kt
Labels: 🛬 needs landing, approved

#3739 Bug 1849368 - Remove data path and data authorities requirement for open links in apps
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
Labels: 🛬 needs landing, approved

#3823 Bug 1855524 - Update AndroidX Compose to version 1.5.2
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#820 Bug 1810044 1810045 - Delay reading clipboard and allow to paste non url
  fenix/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt
Labels: 🛬 needs landing, approved

#3832 Revert "Bug 1810044 1810045 - Delay reading clipboard and allow to paste non url"
  fenix/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt
Labels: 🛬 needs landing, approved

#3818 Bug 1855449 - Normal Browsing search TestRail matching
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: 🛬 needs landing, approved

#3825 Bug 1855516 - Call `disableExtensionProcessSpawning()` when the user clicks the "continue without add-ons" button
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionRuntime.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionProcessDisabledController.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionProcessDisabledControllerTest.kt
Labels: 🛬 needs landing, approved

#3774 Bug 1853743: Support any image format for the profile picture on FedCM Select Account Dialog
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/SelectAccountDialog.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/SelectProviderDialog.kt
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt
  android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
Labels: 🛬 needs landing, approved
