Repository mozilla-mobile/firefox-android, pull requests merged in 2023-06, with the labels that each got.

#2251 Bug 1835453 - Handling content-type with extra information correctly
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
Labels: 🛬 needs landing, approved

#2291 Bug 1836142 - Update Sentry to version 6.21.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#84 Bug 1836338 - Improve DownloadUtils.uniqueFileName readability.
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
Labels: 🛬 needs landing, approved

#2298 Bug 1836339 - Add a secret setting for the Compose Top Sites
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
Labels: 🛬 needs landing, approved

#2299 Bug 1836347 - Add default active and inactive colors for the PagerIndicator
  fenix/app/src/main/java/org/mozilla/fenix/compose/PagerIndicator.kt
Labels: 🛬 needs landing, approved

#2300 Bug 1836380 – adding strings to be used by new search settings screen in advance
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#2307 Bug 1807273 - Disable saveLoginsInPWATest UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
Labels: 🛬 needs landing, approved

#2272 Bug 1807275 - Fix and re-enable emailLinkPWATest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
Labels: 🛬 needs landing, approved

#2326 Bug 1836794 - Start the Nightly 116 development cycle
  docs/changelog.md
Labels: 🛬 needs landing, approved

#1600 Bug 1802010 - After adding a shortcut, show a confirmation message
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/BrowserMenuController.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  focus-android/app/src/main/res/values/strings.xml
  focus-android/app/src/test/java/org/mozilla/focus/menu/BrowserMenuControllerTest.kt
Labels: 🛬 needs landing, approved

#2332 Bug 1836887 - Remove telemetry probes expired in v116
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: 🛬 needs landing, approved

#2284 Bug 1820545 - Refactor isActiveUser method to remove test intermittency.
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/ReEngagementNotificationWorker.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/ReEngagementNotificationWorkerTest.kt
Labels: 🛬 needs landing, approved

#2306 Bug 1836447 - Make extension functions member functions of BookmarkNode
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/BookmarksStorage.kt
  android-components/components/concept/storage/src/test/java/mozilla/components/concept/storage/BookmarkNodeTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/ext/BookmarkNode.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/ext/BookmarkNodeTest.kt
Labels: 🛬 needs landing, approved

#2309 Bug 1836494 - Remove running condition for UI tests related to open links in apps
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Labels: 🛬 needs landing, approved

#2310 Bug 1836501 - Add doc on how to apply channel conditional for UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/docs/channels.md
Labels: 🛬 needs landing, approved

#2337 Bug 1672252 - Ignore case when appending Juno Onboarding privacy link
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
Labels: 🛬 needs landing, approved

#2312 Bug 1821724 - For Portrait mode, align the Pocket column with the column title
  fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLargePlaceholder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: 🛬 needs landing, approved

#2345 Bug 1837059 - Remove stray GMS reference for annotation
  fenix/app/src/main/java/org/mozilla/fenix/browser/readermode/ReaderModeController.kt
Labels: 🛬 needs landing, approved

#2349 Bug 1837077 - Update OnboardingRadioButton pref in background
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingRadioButton.kt
Labels: 🛬 needs landing, approved

#2358 Bug 1837208 - Add support for Adjust preinstall attribution tracking
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
Labels: 🛬 needs landing, approved

#2360 Bug 1837258 – explain placeholder inside a string comment
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#2314 Bug 1836022 - catch NS_ERROR_HOST_IS_IP_ADDRESS when querying cookie banners exception
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorage.kt
Labels: 🛬 needs landing, approved

#2159 Bug 1831107 - Allow bookmarks containing mobile subdomains to be searched when the corresponding search engine is selected
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProvider.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
  android-components/components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/UriKtTest.kt
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
Labels: 🛬 needs landing, approved

#2368 Bug 1837326 - Update Play In-App Reviews to version 2.0.1
  fenix/buildSrc/src/main/java/FenixDependencies.kt
Labels: 🛬 needs landing, approved

#2371 Revert "Bug 1821724 - For Portrait mode, align the Pocket column with the column title "
  fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLargePlaceholder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: 🛬 needs landing, approved

#2365 Bug 1837323 - Update AndroidX Fragment to version 1.6.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing, approved

#1436 Bug 1812732 - Empty collection can be created
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionBannerBinding.kt
Labels: 🛬 needs landing, approved

#2356 Bug 1837149 - New search history UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
Labels: 🛬 needs landing, approved

#2373 Bug 1828684 - Update font style for number of selected tabs text
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
Labels: 🛬 needs landing, approved

#2372 Bug 1837378 - New system notification settings UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SystemSettingsRobot.kt
Labels: 🛬 needs landing, approved

#2359 Bug 1837108 - Refactor Focus buildSrc/Config into a plugin using composite build
  android-components/plugins/config/build.gradle
  android-components/plugins/config/settings.gradle
  android-components/plugins/config/src/main/java/ConfigPlugin.kt
  focus-android/settings.gradle
Labels: 🛬 needs landing, approved

#2394 Bug 1816004 - Remove unused saveToPDF feature flags
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  fenix/app/src/main/res/layout/fragment_share.xml
Labels: 🛬 needs landing, approved

#2395 Bug 1816004 - Remove unused unifiedSearchFeature and notificationPrePermissionPromptEnabled feature flags
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: 🛬 needs landing, approved

#2420 Bug 1825071 - Refactor BrowserIconsTest to remove Robolectric.
  android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt
  fenix/app/src/test/java/org/mozilla/fenix/ext/BrowserIconsTest.kt
Labels: 🛬 needs landing, approved

#2391 Bug 1821724 - Align the Pocket column with the column title in portrait
  fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLargePlaceholder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: 🛬 needs landing, approved

#2423 Bug 1837656 - Added the "Challenge the Default" drawable resources
  fenix/app/src/main/res/drawable-night/onboarding_ctd_default_browser.xml
  fenix/app/src/main/res/drawable/onboarding_ctd_default_browser.xml
  fenix/app/src/main/res/drawable/onboarding_ctd_notification.xml
  fenix/app/src/main/res/drawable/onboarding_ctd_sync.xml
  fenix/app/src/main/res/raw/keep.xml
Labels: 🛬 needs landing, approved

#2425 Bug 1837653 - Enabled Unified Search for Beta
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#2350 Bug 1830768 - Add nimbus flag for toolbar position
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: 🛬 needs landing, approved

#2313 Bug 1835937 - Fix crash when changing autoplay site permission in private browsing
  fenix/app/src/main/java/org/mozilla/fenix/components/PermissionStorage.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/QuickSettingsController.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/PermissionStorageTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/DefaultQuickSettingsControllerTest.kt
Labels: 🛬 needs landing, approved

#2315 Bug 1836357 - Add a dialog for handling FedCM showProviderPrompt.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/identitycredential/Provider.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/BasicProvidersAdapter.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/SelectProviderDialogFragment.kt
  android-components/components/feature/prompts/src/main/res/layout/mozac_feature_prompts_choose_identity_provider_dialogs.xml
  android-components/components/feature/prompts/src/main/res/layout/mozac_feature_prompts_identity_crendential_provider_item.xml
  android-components/components/feature/prompts/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#2436 Bug 1837653 - Enabled Unified Search by default
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#2441 Bug 1838216 - mergify: require successful complete-push task for geckoview updates
  .mergify.yml
Labels: 🛬 needs landing, approved

#2431 Bug 1837525 - Load favicons directly from drawables for certain urls in the Compose Top Sites
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
Labels: 🛬 needs landing, approved

#2438 Bug 1836454 - Fix ComposeTabbedBrowsingTest flaky tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
Labels: 🛬 needs landing, approved

#2445 Bug 1838312 - Remove hardcoded compileSdkVersion, minSdkVersion and targetSdkVersion in Fenix and Focus
  fenix/app/build.gradle
  fenix/benchmark/build.gradle
  fenix/buildSrc/src/main/java/Config.kt
  focus-android/app/build.gradle
  focus-android/service-telemetry/build.gradle
Labels: 🛬 needs landing, approved

#2444 Bug 1837507 - Ensure the Compose Top Sites pager indicator aligns with the existing design
  fenix/app/src/main/java/org/mozilla/fenix/compose/PagerIndicator.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
Labels: 🛬 needs landing, approved

#2443 Bug 1838231 - gate nightly pushapk on startup-test
  taskcluster/android_taskgraph/transforms/push_apk.py
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/startup-test/kind.yml
Labels: 🛬 needs landing, approved

#2390 Bug 1823367 - When closing Fenix in private mode, the ETP setting should have the default value.
  fenix/app/src/main/java/org/mozilla/fenix/session/VisibilityLifecycleCallback.kt
Labels: 🛬 needs landing, approved

#2454 Bug 1838391 - Address crash UninitializedPropertyAccessException in AddonsManagementFragment.
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
Labels: 🛬 needs landing, approved

#2461 Bug 1837425 - Fix synced tabs FAB button text
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFab.kt
Labels: 🛬 needs landing, approved

#2446 Bug 1838321 - Address NullPointerException when trying to setAllowedInPrivateBrowsing.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🛬 needs landing, approved

#2456 Bug 1838358 - Create a startup UI test task for Focus
  taskcluster/android_taskgraph/transforms/push_apk.py
  taskcluster/ci/startup-test/kind.yml
Labels: 🛬 needs landing, approved

#2378 Bug 1836778 - Add Support for Printing in GeckoEngineSession
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/EngineDelegateMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/EngineStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  android-components/components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#2483 Bug 1838662 - cleanup push-apk.py in firefox-android
  taskcluster/android_taskgraph/transforms/push_apk.py
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#862 Bug 1813086 - Added minimum height and width property to URL icon and adjusted view accordingly.
  fenix/app/src/main/res/layout/library_site_item.xml
  fenix/app/src/main/res/values/dimens.xml
Labels: 🛬 needs landing (squash), approved

#2317 Bug 1829213 - Update Save To PDF Telemetry and checkForPdfViewer Option
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/EngineStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  fenix/app/src/test/java/org/mozilla/fenix/share/SaveToPDFMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
Labels: 🛬 needs landing, approved

#2463 Bug 1838512 - Move Browsers Cache utility into Android Components
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/BrowsersCache.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/BrowsersCacheTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MozillaProductDetector.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/CustomAttributeProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/DefaultBrowserPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: 🛬 needs landing, approved

#2487 Bug 1837864 – fix search settings opening visual glitch
  fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
Labels: 🛬 needs landing, approved

#2491 Bug 1838512 - Fix detekt issue from moving Browsers Cache utility into Android Components
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/BrowsersCache.kt
  fenix/detekt-baseline.xml
Labels: 🛬 needs landing, approved

#2117 Bug 1834870: Use sync telemetry from application services
  android-components/.buildconfig.yml
  android-components/CODEOWNERS
  android-components/components/browser/storage-sync/README.md
  android-components/components/browser/storage-sync/build.gradle
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/Connection.kt
  android-components/components/service/firefox-accounts/build.gradle
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
  android-components/components/service/sync-logins/build.gradle
  android-components/components/support/sync-telemetry/README.md
  android-components/components/support/sync-telemetry/build.gradle
  android-components/components/support/sync-telemetry/docs/metrics.md
  android-components/components/support/sync-telemetry/metrics.yaml
  android-components/components/support/sync-telemetry/pings.yaml
  android-components/components/support/sync-telemetry/src/main/AndroidManifest.xml
  android-components/components/support/sync-telemetry/src/main/java/mozilla/components/support/sync/telemetry/BaseGleanSyncPing.kt
  android-components/components/support/sync-telemetry/src/main/java/mozilla/components/support/sync/telemetry/SyncTelemetry.kt
  android-components/components/support/sync-telemetry/src/test/java/mozilla/components/support/sync/telemetry/SyncTelemetryTest.kt
  android-components/components/support/sync-telemetry/src/test/resources/robolectric.properties
  android-components/config/detekt-baseline.xml
  fenix/.buildconfig.yml
  focus-android/.buildconfig.yml
  taskcluster/ci/config.yml
  taskcluster/scripts/toolchain/external-gradle-dependencies.sh
Labels: 🛬 needs landing, approved

#2455 Bug 1837599 - Allow history visits containing mobile subdomains to be displayed in the awesome bar
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProvider.kt
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProvider.kt
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProviderTest.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryMetadataSuggestionProviderTest.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProviderTest.kt
  android-components/components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/UriKtTest.kt
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
Labels: 🛬 needs landing, approved

#2508 Bug 1830768 - Add nimbus flag for toolbar position
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: 🛬 needs landing, approved

#2502 Bug 1815276 - Disable Pocket sponsored stories check
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#2500 Bug 1838613 - Migrate NotificationManagerCompat ext to AC
  android-components/components/support/base/src/main/java/mozilla/components/support/base/ext/NotificationManagerCompat.kt
  android-components/components/support/base/src/test/java/mozilla/components/support/base/ext/NotificationManagerCompatTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/CustomAttributeProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/JunoOnboardingFragment.kt
Labels: 🛬 needs landing, approved

#2161 Bug 1803103 - Update app theme in running state when device theme changes
  focus-android/app/src/main/java/org/mozilla/focus/FocusApplication.kt
Labels: 🛬 needs landing, approved

#2530 Bug 1838859 - Remove no op utility for exhaustive when
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/viewholders/BookmarkNodeViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/history/viewholders/HistoryListItemViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/viewholders/AccountDeviceViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/MenuIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/SelectionMenuIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Do.kt
Labels: 🛬 needs landing, approved

#2346 Bug 1837060 - Remove unused search engine definitions.
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-br.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-mx.xml
  android-components/components/feature/search/src/main/assets/searchplugins/duckduckgo.xml
  android-components/components/feature/search/src/main/assets/searchplugins/google-2018.xml
  android-components/components/feature/search/src/main/assets/searchplugins/google.xml
  android-components/components/feature/search/src/main/assets/searchplugins/twitter-ja.xml
  android-components/components/feature/search/src/main/assets/searchplugins/twitter.xml
Labels: 🛬 needs landing, approved

#2534 Bug 1837521 - Load image url bitmaps in the Compose Top Sites
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
Labels: 🛬 needs landing, approved

#2505 Bug 1838717 - Enable alerting for APK file size.
  fenix/buildSrc/src/main/java/org/mozilla/fenix/gradle/tasks/ApkSizeTask.kt
Labels: 🛬 needs landing (squash), approved

#2462 Bug 1835665 - Unify FocusDependencies with AC's DependenciesPlugin
  focus-android/app/build.gradle
  focus-android/build.gradle
  focus-android/plugins/focusdependencies/src/main/java/FocusDependenciesPlugin.kt
  focus-android/service-telemetry/build.gradle
Labels: 🛬 needs landing, approved

#2460 Bug 1838120 - Unify Fenix buildSrc/Config with the ConfigPlugin
  android-components/plugins/config/src/main/java/ConfigPlugin.kt
  fenix/app/build.gradle
  fenix/buildSrc/src/main/java/Config.kt
  fenix/buildSrc/src/main/java/org/mozilla/fenix/gradle/ext/Runtime.kt
  fenix/settings.gradle
Labels: 🛬 needs landing, approved

#2471 Bug 1838569 – added a nimbus flag for splash screen duration
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#2507 Bug 1837984: Adjust the spacing between the normal, private and sync …
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
Labels: 🛬 needs landing, approved

#2559 Bug 1839578 - Allow ktlintFormat task to modify access java.lang class fields.
  android-components/build.gradle
Labels: 🛬 needs landing, approved

#2563 Bug 1802817 - Replace deprecated main with mainClass.
  android-components/build.gradle
Labels: 🛬 needs landing, approved

#2428 Bug 1828516 - Hide Whats New button
  focus-android/app/metrics.yaml
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/MozillaSupportPagesTest.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsRobot.kt
  focus-android/app/src/main/java/org/mozilla/focus/settings/SettingsFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
  focus-android/app/src/main/java/org/mozilla/focus/whatsnew/WhatsNew.kt
  focus-android/app/src/main/java/org/mozilla/focus/whatsnew/WhatsNewStorage.kt
  focus-android/app/src/main/java/org/mozilla/focus/whatsnew/WhatsNewVersion.kt
  focus-android/app/src/main/res/menu/menu_settings_main.xml
  focus-android/app/src/main/res/values/strings.xml
  focus-android/app/src/test/java/org/mozilla/focus/whatsnew/WhatsNewStorageTest.kt
  focus-android/app/src/test/java/org/mozilla/focus/whatsnew/WhatsNewTest.kt
  focus-android/app/src/test/java/org/mozilla/focus/whatsnew/WhatsNewVersionTest.kt
Labels: 🛬 needs landing, approved

#2484 Bug 1825124 - Change the way we show the post-install popup once an extension has been installed.
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/extension/WebExtensionPromptRequest.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragmentTest.kt
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt
  android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
Labels: 🛬 needs landing, approved

#2485 Bug 1838657 - PlacesApiException.UnexpectedPlacesException should no …
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesStorageTest.kt
Labels: 🛬 needs landing, approved

#2565 Bug 1839578 - Allow ktlintFormat task to modify access java.lang class fields.
  fenix/build.gradle
  focus-android/build.gradle
Labels: 🛬 needs landing, approved

#2562 Bug 1808879 - Fix for the addons install prompt in UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
Labels: 🛬 needs landing, approved

#2564 Bug 1833457 - Suggested logins bar is hidden after the tab that conta…
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/LoginPicker.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/login/LoginPickerTest.kt
Labels: 🛬 needs landing, approved

#2533 Bug 1838862 - Remove unused BackHandler
  android-components/components/support/base/src/main/java/mozilla/components/support/base/feature/BackHandler.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#2560 Bug 1839610 - bump taskgraph to 5.4.0
  taskcluster/requirements.txt
Labels: 🛬 needs landing, approved

#2566 Bug 1810630 - add 'manage account' to the sync menu.
  android-components/components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/main/res/xml/account_settings_preferences.xml
Labels: 🛬 needs landing (squash), approved

#2550 Bug 1836166 - add telemetry for Mozilla Sync sign in
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: 🛬 needs landing, approved

#2375 Bug 1836167 - New telemetry in bookmarks for growth retention measurement
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
Labels: 🛬 needs landing, approved

#2574 Bug 1837107 - Unify FenixDependencies with AC's DependenciesPlugin
  fenix/app/build.gradle
  fenix/benchmark/build.gradle
  fenix/build.gradle
  fenix/mozilla-detekt-rules/build.gradle
  fenix/mozilla-lint-rules/build.gradle
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2427 Bug 1836165 - New growth telemetry for private tab open count
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing, approved

#2596 Bug 1836364 - Correctly handle the confirm action on SelectAccount prompt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
Labels: 🛬 needs landing, approved

#2599 Bug 1840151 - Remove telemetry probes expiring in v118
  focus-android/app/metrics.yaml
  focus-android/app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
Labels: 🛬 needs landing, approved

#2584 Bug 1839651 - Remove the "downloading" add-on popup.
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
  fenix/app/src/main/res/drawable/mozac_ic_extensions_black.xml
  fenix/app/src/main/res/layout/fragment_add_ons_management.xml
  fenix/app/src/main/res/layout/overlay_add_on_progress.xml
Labels: 🛬 needs landing, approved

#1513 Bug 1821210 - Added content description on Back button to say `Navigate up button`
  android-components/components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  android-components/components/browser/menu/src/main/java/mozilla/components/browser/menu/item/BackPressMenuItem.kt
  android-components/components/browser/menu/src/main/res/values/strings.xml
  android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/item/ParentBrowserMenuItemTest.kt
Labels: 🛬 needs landing, approved

#2547 Bug 1839358 - Allow open tabs containing mobile subdomains to be displayed as suggestions in the awesome bar
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
Labels: 🛬 needs landing, approved

#2597 Bug 1840109 - Renew telemetry probes expiring in v118
  fenix/app/metrics.yaml
Labels: 🛬 needs landing, approved

#1466 Bug 1825425 - Add RFC 0009 to remove interactors and controllers
  docs/rfcs/0009-remove-interactors-and-controllers.md
Labels: 🛬 needs landing, approved

#2556 Bug 1839522 – added splash screen compat implementation, tied extra duration to the experiment
  fenix/app/build.gradle
  fenix/app/src/main/AndroidManifest.xml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/drawable-v23/splash_screen.xml
  fenix/app/src/main/res/drawable-v24/splash_screen.xml
  fenix/app/src/main/res/values-night/styles.xml
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/styles.xml
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2625 Bug 1840483 - 'manage account' is only available on Nightly/Debug builds
  fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
Labels: 🛬 needs landing, approved

#2618 Bug 1840091 - Add shopping experience feature flag
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#2580 Bug 1840316 - New text selection and quick actions url bar UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TextSelectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: 🛬 needs landing, approved

#2634 Bug 1840634 - Refactor test to remove usage of mockkStatic.
  fenix/app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
Labels: 🛬 needs landing, approved

#2458 Bug 1837509 - Compose Top Sites should work with wallpapers
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesViewHolder.kt
Labels: 🛬 needs landing, approved

#2509 Bug 1833960 - Use Browsers Cache utility in App Links
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/BrowsersTest.kt
Labels: 🛬 needs landing, approved

#2555 Bug 1836164 - New growth telemetry for credential management
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
Labels: 🛬 needs landing, approved

#2641 Bug 1807289 - Disable failing customTabDownloadTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
Labels: 🛬 needs landing, approved

#2632 Bug 1840578 - Add shopping experience entry point
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt
  fenix/app/src/main/res/drawable/ic_shopping_cart.xml
  fenix/app/src/main/res/drawable/ic_shopping_cart_selected.xml
  fenix/app/src/main/res/values/static_strings.xml
Labels: 🛬 needs landing, approved

#2578 Bug 1838140 - Update composed tabs tray media button ripple effect to match the xml version
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/MediaImage.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
Labels: 🛬 needs landing, approved

#2629 Bug 1840581 - Add condition before switching to private browsing
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#2598 Bug 1837417 - Remember synced tabs collapsed/expanded state in composed tabs tray
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
Labels: 🛬 needs landing, approved

#2636 Bug 1840676 - Update Robolectric to version 4.10.3
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2631 Bug 1837437 - update compose tabs tray size depending on orientation
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Labels: 🛬 needs landing, approved

#2642 Bug 1840791 - Remove unused GleanTestRule and FenixRobolectricTestRunner
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutObserverTest.kt
Labels: 🛬 needs landing, approved

#2637 Bug 1840677 - Update Sentry to version 6.24.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2620 Bug 1840341 - Add memory telemetry for experiment
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
Labels: 🛬 needs landing, approved

#2624 Bug 1836780 - Add UI For Printing Page Content
  docs/changelog.md
  fenix/app/metrics.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/PrintItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFInteractor.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareController.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/share/ShareInteractor.kt
  fenix/app/src/main/res/drawable/ic_print.xml
  fenix/app/src/main/res/layout/fragment_share.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/share/ShareInteractorTest.kt
Labels: 🛬 needs landing, approved

#2582 Bug 1836360 - Add a dialog for handling FedCM showPolicyPrompt.
  android-components/.buildconfig.yml
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  android-components/components/feature/prompts/build.gradle
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptContainer.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/PromptDialogFragment.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/PrivacyPolicyDialogFragment.kt
  android-components/components/feature/prompts/src/main/res/values/strings.xml
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptContainerTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonPopupBaseFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing, approved

#2615 Bug 1840308 – added condition to finish first time splash screen faster if the marekting and experiment data is fetch first
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/NimbusBuilder.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing, approved

#2643 Bug 1840816 - New open link in external app context menu UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Labels: 🛬 needs landing, approved

#2593 Bug 1840061 - Adds PDF viewer - Open in app button UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PDFViewerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing, approved

#2481 Bug 1837504 - Display undo snackbar when compose top site is removed
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
Labels: 🛬 needs landing, approved

#2633 Bug 1838935 - Inactive tabs not selectable in multi-select mode
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
Labels: 🛬 needs landing, approved

#2622 Bug 1840382 - Add experimentation flag to enable passing a channel ID to use for search
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/middleware/SearchMiddleware.kt
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/storage/BundledSearchEnginesStorage.kt
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchEngineReader.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/storage/BundledSearchEnginesStorageTest.kt
  android-components/components/feature/search/src/test/java/mozilla/components/feature/search/storage/ParseSearchPluginsTest.kt
  fenix/app/.experimenter.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: 🛬 needs landing, approved

#2657 Bug 1815421 - Clear button should be active only when username input is not empty.
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
Labels: 🛬 needs landing

#2660 Bug 1836521 - Ship v116.0.0 of the WebCompat System Addon.
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/about-compat/aboutCompat.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1830752-afisha.ru-slider-pointer-events.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1836177-clalit.co.il-hide-number-input-spinners.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1819678-cnki.net-undisable-search-field.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/tsn-ca.js
Labels: 🛬 needs landing, approved

#2656 Bug 1841032 - Cannot un-focus the keyboard once selected in the OG onboarding without pressing back.
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: 🛬 needs landing, approved

#2645 Bug 1840837 - Update Bookmarks and History search tests with Unified …
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: 🛬 needs landing, approved
