Repository mozilla-mobile/firefox-android, pull requests merged in 2023-02, with the labels that each got.

#664 Bug 1810781 - After the app is re-opened Focus should display the last closed page.
  focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Labels: 🛬 needs landing

#683 Show snackbar when entering fullscreen mode
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt
  focus-android/app/src/main/res/values/strings.xml
  focus-android/app/src/test/java/org/mozilla/focus/browser/integration/FullScreenIntegrationTest.kt
Labels: 🛬 needs landing

#679 Bug 1813582 - Added checks for TelemetryWrapper.startSession() and TelemetryWrapper.stopSession() not to be called multiple times.
  focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  focus-android/app/src/main/java/org/mozilla/focus/widget/TelemetrySwitchPreference.kt
Labels: 🛬 needs landing

#693 Bug 1814338 - Use v3 of sync-string-actions
  .github/workflows/ac-sync-strings.yml
  .github/workflows/focus-sync-strings.yml
Labels: 🛬 needs landing

#696 Bug 1814338 - Fix commit message in uplift strings workflow, only copy localized files
  .github/workflows/ac-sync-strings.yml
  .github/workflows/focus-sync-strings.yml
Labels: 🛬 needs landing

#703 Bug 1812517 - Update error pages for https and expired certificate. Modified the texts and added a link.
  focus-android/app/src/main/assets/error_style.css
  focus-android/app/src/main/java/org/mozilla/focus/engine/AppContentInterceptor.kt
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#653 Bug 1811531 - Add 'site' query parameter to Pocket sponsored stories request
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketStoriesConfig.kt
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketStoriesService.kt
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/SpocsUseCases.kt
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/api/SpocsEndpoint.kt
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointRaw.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketStoriesConfigTest.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketStoriesServiceTest.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/SpocsUseCasesTest.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointRawTest.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#690 Bug 1811531 - Add 'country' and 'city' query parameter to Pocket sponsored stories request
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketStoriesConfig.kt
  android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointRaw.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketStoriesConfigTest.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/SpocsUseCasesTest.kt
  android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointRawTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#718 Revert "Bug 1802214 - Remove redundant getAppLaunchCount."
  focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/Settings.kt
  focus-android/app/src/main/res/values/preference_keys.xml
  focus-android/quality/detekt-baseline.xml
Labels: 🛬 needs landing, approved

#386 Bug 27998 – Add settings to BrowserMenu to overlap anchor view completely
  android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/BrowserMenuController.kt
  android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/ext/MenuPositioningData.kt
  android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/ext/PopupWindow.kt
  android-components/components/browser/menu2/src/main/res/values/dimens.xml
  android-components/components/browser/menu2/src/test/java/mozilla/components/browser/menu2/ext/PopupWindowTest.kt
  android-components/components/concept/menu/src/main/java/mozilla/components/concept/menu/MenuStyle.kt
Labels: 🛬 needs landing

#725 Bug 1792926 - After downloading, the download name was fixed. Check if the string is empty.
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
Labels: 🛬 needs landing

#729 Bug 1815551 - Update Sentry to version 6.13.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  focus-android/buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#716 Bug 1813416 - Clear FLAG_KEEP_SCREEN_ON when playing media is finished.
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt
  android-components/components/feature/media/src/test/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing

#727 Bug 1815195 - Avoid a redundant file extension when saving a real pdf file
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
Labels: 🛬 needs landing

#453 Bug 1807920 - Make newPrivateTabSearch usecase open only private new tabs
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/SearchUseCases.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: 🛬 needs landing, approved

#738 Bug 1805408 - Ship v111.0.0 of the WebCompat System Addon.
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1605611-maps.google.com-directions-time.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784195-nutmeg.morrisons.com-overflow.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1784351-movistar.com.ar-overflow-overlay-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1605611-maps.google.com-directions-time.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1769762-tiktok.com-plugins-shim.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/custom_functions.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/instagram.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/spotify-embed.js
Labels: 🛬 needs landing

#741 Bug 1816058 - Fix error pages strings for https and expired certificate.
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#719 Bug 1804785 - Consume AC via gradle build with relative path in Fenix
  android-components/build.gradle
  fenix/LICENSE
  fenix/app/build.gradle
  fenix/app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
  fenix/app/src/main/res/values/static_strings.xml
  fenix/build.gradle
  fenix/buildSrc/src/main/java/Config.kt
  fenix/buildSrc/src/main/java/Dependencies.kt
  fenix/gradle.properties
  fenix/settings.gradle
  fenix/version.txt
  focus-android/build.gradle
  focus-android/gradle.properties
Labels: 🛬 needs landing

#771 Bug 1816629 - ci: bump max-run-time for lint tasks from 10 to 20 minutes
  taskcluster/ci/lint/kind.yml
Labels: 🛬 needs landing

#780 Bug 1814338 - Update l10n sync workflow for Fenix to match other products
  .github/workflows/fenix-sync-strings.yml
Labels: 🛬 needs landing

#792 Bug 1816186 - Use detect-only just when we can show the re-engagement dialog
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/CookieBannersFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialogUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: 🛬 needs landing, approved

#791 Bug 1816683 - Fix AC version not displayed in verifyAboutFirefoxPreview UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
Labels: 🛬 needs landing

#805 Bug 1816787 - Update treeherder.platform for fenix signing-apk tasks
  taskcluster/android_taskgraph/transforms/signing_apk.py
  taskcluster/ci/signing-apk/kind.yml
Labels: 🛬 needs landing

#804 Bug 1815504 - Convert existing legacy-arm Task to soft dependency
  .cron.yml
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing

#811 Bug 1816778 - Adds GV channel condition to PDF reader UI test
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt
  focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: 🛬 needs landing, approved

#817 Bug 1816892 - Update the Private Browsing Mode CFR text
  fenix/app/src/main/res/layout/pbm_shortcut_popup.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#796 Bug 1809919 - Implement ActivityContextDelegate in AC
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/activity/GeckoViewActivityContextDelegate.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/activity/GeckoViewActivityContextDelegateTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehaviorTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineViewTest.kt
  android-components/components/feature/session/src/test/java/mozilla/components/feature/session/SwipeRefreshFeatureTest.kt
  android-components/components/support/test-fakes/src/main/java/mozilla/components/support/test/fakes/engine/FakeEngineView.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing

#798 Bug 1808358 - Use OnboardingPage component in NotificationPermissionDialogScreen
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/NotificationPermissionDialogScreen.kt
Labels: 🛬 needs landing, approved

#802 Bug 1816196 - Do not fetch messaging during storage initialization
  fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt
  fenix/app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
Labels: 🛬 needs landing

#799 Bug 1815968 - Add secret setting to Tabs Tray to Compose
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
Labels: 🛬 needs landing, approved

#816 Bug 1816908 - The search via the widget's microphone should open a w tab containing the search term.
  focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Labels: 🛬 needs landing

#832 Bug 1816967 - Simplify and generalize slack notify for ui-test-apk kind
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing

#841 Bug 1810531 - Re-enable Fenix UI test: saveAndOpenPdfTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing

#743 Bug 1816184 - Add message for declarativeNetRequestFeedback permission
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/main/res/values/strings.xml
  android-components/components/feature/addons/src/test/java/AddonTest.kt
Labels: 🛬 needs landing

#844 Bug 1817229 - update github workflows to fenix-beta-version v4.2.3
  .github/workflows/ac-sync-strings.yml
  .github/workflows/fenix-sync-strings.yml
  .github/workflows/focus-sync-strings.yml
Labels: 🛬 needs landing

#846 Bug 1817052 - Build Android nightlies 6 hours after Desktop's
  .cron.yml
Labels: 🛬 needs landing

#827 Bug 1817003 - Remove low capacity ARM device on FTL
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#110 Bug 1811751 - fix estimated reading time disappear, related to android-repository PR 11951.
  android-components/components/feature/readerview/src/main/assets/extensions/readerview/readerview.js
Labels: 🛬 needs landing

#790 Bug 1813877 - Announce page title with talkback when swiping on navbar
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/res/layout/fragment_browser.xml
Labels: 🛬 needs landing, approved

#865 Bug 1807369 - Improve accessibility for 'Learn more' hyperlink from the Pocket homepage header
  fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#823 Bug 1816724 - Show previous ETP message in onboarding if TCP is not enabled
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolderTest.kt
Labels: 🛬 needs landing, approved

#868 Bug 1817439 - l10n workflows: use github-actions[bot] as authorfor uplift (sync) workflows
  .github/workflows/ac-sync-strings.yml
  .github/workflows/fenix-sync-strings.yml
  .github/workflows/focus-sync-strings.yml
Labels: 🛬 needs landing

#890 Bug 1807531 - Honor private_browsing_mode value from external intents
  fenix/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
  fenix/app/src/test/java/org/mozilla/fenix/IntentReceiverActivityTest.kt
Labels: 🛬 needs landing

#869 Bug 1807289 - Fix collections related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing

#903 Bug 1817726 - Add Recents url sharing
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: 🛬 needs landing

#870 Bug 1816867 - Ensure Pocket topics selections are properly shown
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/Chip.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Labels: 🛬 needs landing

#918 Bug 1815634 - Set weight and fill to text to display collection expand / collapse chevron for any length of title
  fenix/app/src/main/java/org/mozilla/fenix/compose/list/ExpandableListHeader.kt
Labels: 🛬 needs landing

#902 Add FLAG_SECURE to SearchDialogFragment
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogFragmentTest.kt
Labels: 🛬 needs landing, approved

#904 Bug 1812468 - Consider increasing the `Standard` and `Strict` options in `Privacy protection by default` on tablets
  fenix/app/src/main/res/layout/onboarding_tracking_protection.xml
Labels: 🛬 needs landing

#932 Bug 1817432 - Always setup notification workers even if marketing channel has not been created
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: 🛬 needs landing, approved

#936 Bug 1815185 - Remove fixed height from `RecentSyncedTab`
  fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
Labels: 🛬 needs landing

#818 Bug 1816932 - Add Maps to app links common sub domains
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Labels: 🛬 needs landing, approved

#874 Bug 1813753 - Skip the half-expanded state when collapsing the Tabs Tray
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabSheetBehaviorManager.kt
Labels: 🛬 needs landing, approved

#924 Bug 1816433 Reduce maybeFetchExperiments interval to zero for the preview collection
  fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
Labels: 🛬 needs landing, approved

#938 Bug 1815939 - Clean up AC autopublish code in Fenix and Focus
  fenix/README.md
  fenix/app/build.gradle
  fenix/settings.gradle
  focus-android/README.md
  focus-android/app/build.gradle
  focus-android/settings.gradle
Labels: 🛬 needs landing

#954 Bug 1818251 - Rename Fenix Dependencies.kt to FenixDependencies.kt
  fenix/buildSrc/src/main/java/FenixDependencies.kt
  taskcluster/ci/external-gradle-dependencies/kind.yml
Labels: 🛬 needs landing

#803 Bug 1816754 - Remove A-C Glean Gradle plugin wrapper
  android-components/.buildconfig.yml
  android-components/CODEOWNERS
  android-components/components/tooling/glean-gradle-plugin/README.md
  android-components/components/tooling/glean-gradle-plugin/build.gradle
  android-components/components/tooling/glean-gradle-plugin/src/main/java/mozilla/components/tooling/glean-gradle-plugin/GleanGradlePlugin.kt
  android-components/components/tooling/glean-gradle-plugin/src/main/resources/META-INF/gradle-plugins/mozilla.components.tooling.glean-gradle-plugin.properties
  android-components/publish.gradle
  docs/changelog.md
  taskcluster/ci/config.yml
Labels: 🛬 needs landing, approved

#934 Bug 1817522 – Add dark theme support for seach button background
  fenix/app/src/main/res/layout/search_selector.xml
Labels: 🛬 needs landing

#757 Bug 1816516 – improve menu positioning tests
  android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/BrowserMenuController.kt
  android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/ext/BrowserMenuPositioning.kt
  android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/ext/PopupWindow.kt
  android-components/components/browser/menu2/src/test/java/mozilla/components/browser/menu2/BrowserMenuControllerTest.kt
  android-components/components/browser/menu2/src/test/java/mozilla/components/browser/menu2/ext/BrowserMenuPositioningTest.kt
  android-components/components/browser/menu2/src/test/java/mozilla/components/browser/menu2/ext/PopupWindowTest.kt
Labels: 🛬 needs landing

#965 Bug 1812447 - Search Logins by Username
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/LoginsFragmentStore.kt
Labels: 🛬 needs landing

#964 Bug 1818510 - Remove all unused strings marked moz:removedIn <= 109
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#946 Bug 1816906 - Remove filter-incomplete-translations and clean up obsolete localization files
  .gitignore
  android-components/l10n-uplift.py
  fenix/automation/taskcluster/l10n/filter-release-translations.py
  fenix/automation/taskcluster/l10n/locales.py
  fenix/l10n-release.toml
  fenix/l10n-uplift.py
  focus-android/.android2po
  focus-android/.gitignore
  focus-android/docs/Localization.md
  focus-android/tools/l10n/filter-release-translations.py
  taskcluster/android_taskgraph/transforms/build_apk.py
  taskcluster/ci/build-apk/kind.yml
Labels: 🛬 needs landing

#947 Bug 1818058 - Enable TCP by default for all releases
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/nimbus.fml.yaml
Labels: 🛬 needs landing

#970 Bug 1818572 - Document versioning for Fenix and Focus
  docs/shared/versioning.md
Labels: 🛬 needs landing (squash)

#935 Bug 1818059 - Update to application services version 97.0.0.
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
  fenix/app/src/test/java/org/mozilla/fenix/experiments/NimbusSetupKtTest.kt
  focus-android/app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
  focus-android/app/src/test/java/org/mozilla/focus/experiments/NimbusSetupTest.kt
Labels: 🛬 needs landing

#957 Bug 1815941 - Unify Fenix and Focus .gitignore to the root .gitignore
  .gitignore
  fenix/.gitignore
  focus-android/.gitignore
Labels: 🛬 needs landing

#973 Bug 1818277 - Update the pull request template for the monorepo
  .github/pull_request_template.md
Labels: 🛬 needs landing

#845 Bug 1809269 - Add bypass load URI delegate in load flags
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt
Labels: 🛬 needs landing, approved

#974 Bug 1817944 - Add nightly official flag to both apps
  taskcluster/ci/build-apk/kind.yml
Labels: 🛬 needs landing

#969 Bug 1818015 - Use custom tab to show privacy notice during onboarding
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt
  fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Labels: 🛬 needs landing, approved

#977 Bug 1795439 - Remove crash-sentry-legacy component
  android-components/.buildconfig.yml
  android-components/components/lib/crash-sentry-legacy/build.gradle
  android-components/components/lib/crash-sentry-legacy/proguard-rules.pro
  android-components/components/lib/crash-sentry-legacy/src/main/AndroidManifest.xml
  android-components/components/lib/crash-sentry-legacy/src/main/java/mozilla/components/lib/crash/sentry/legacy/SentryService.kt
  android-components/components/lib/crash-sentry-legacy/src/test/java/mozilla/components/lib/crash/sentry/legacy/SentryServiceTest.kt
  android-components/components/lib/crash-sentry-legacy/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  android-components/components/lib/crash-sentry-legacy/src/test/resources/robolectric.properties
  docs/changelog.md
  taskcluster/test/params/main-repo-ship-beta.yml
  taskcluster/test/params/main-repo-ship-release.yml
Labels: 🛬 needs landing, approved

#966 Bug 1818462 - Refactor AbstractFirebasePushService to remove test dependencies.
  android-components/components/lib/push-firebase/build.gradle
  android-components/components/lib/push-firebase/src/main/java/mozilla/components/lib/push/firebase/AbstractFirebasePushService.kt
  android-components/components/lib/push-firebase/src/test/java/mozilla/components/lib/push/firebase/AbstractFirebasePushServiceTest.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing

#851 Bug 1817250 - Add/Enable Robo Test on Firebase Test Lab
  fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
  fenix/automation/taskcluster/androidTest/robo-test.sh
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing

#575 Bug 1811175 - Implement fallback protocol for sponsored tiles
  android-components/components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Response.kt
  android-components/components/service/contile/src/main/java/mozilla/components/service/contile/ContileTopSitesProvider.kt
  android-components/components/service/contile/src/test/java/mozilla/components/service/contile/ContileTopSitesProviderTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: 🛬 needs landing, approved

#1004 Bug 1817611 - Revert using live region for talkback on navbar swipe
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/res/layout/fragment_browser.xml
Labels: 🛬 needs landing, approved

#909 Bug 1812196 - Sets height of `Learn more about Sync` in Logins and passwords- Saved logins
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/view/SavedLoginsListView.kt
Labels: 🛬 needs landing (squash)

#951 Bug 1818196 - Part 2: New credit cards autofill related UI tests
  fenix/app/src/androidTest/assets/pages/creditCardForm.html
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Labels: 🛬 needs landing

#972 Bug 1814385 - Change remaining project:mobile:fenix scopes to firefox-android
  taskcluster/android_taskgraph/transforms/beetmover_fenix.py
  taskcluster/ci/beetmover-fenix/kind.yml
Labels: 🛬 needs landing, approved

#1011 Bug 1819094 - Set track-apk-size for fenix-debug/nightly/beta/release builds
  taskcluster/ci/build-apk/kind.yml
Labels: 🛬 needs landing

#1013 Bug 1814987 - Wrap `TabsTray` Composable with existing `TabSheetBehaviorManager`
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabSheetBehaviorManager.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/res/layout/component_tabstray3.xml
Labels: 🛬 needs landing, approved

#1015 Bug 1819225 - fix comparator issue with update-experiments output
  .github/workflows/fenix-update-nimbus-experiments.yml
  .github/workflows/focus-update-nimbus-experiments.yml
Labels: 🛬 needs landing

#988 Bug 1817516 - Add/Update Amazon suggestion URLs in supported locales
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-au.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-ca.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-co-uk.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-de.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-es.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-fr.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-in.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-it.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-jp.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-nl.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazon-se.xml
  android-components/components/feature/search/src/main/assets/searchplugins/amazondotcom.xml
Labels: 🛬 needs landing, approved

#1012 Bug 1819111 - Add EBay suggestion URLs in supported locales
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-at.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-au.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-befr.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-ca.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-ch.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-co-uk.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-de.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-es.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-fr.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-ie.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-it.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay-nl.xml
  android-components/components/feature/search/src/main/assets/searchplugins/ebay.xml
Labels: 🛬 needs landing, approved

#1036 Bug 1819094 - Fix ApkSizeTask to work for new variant names
  fenix/buildSrc/src/main/java/org/mozilla/fenix/gradle/tasks/ApkSizeTask.kt
Labels: 🛬 needs landing

#1027 Bug 1818703 - Re-enable youControlYourDataCardTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing
