Repository mozilla-mobile/firefox-android, pull requests merged in 2023-12, with the labels that each got.

#4494 Bug 1862536 - Add a Nimbus variable for Firefox Suggest providers.
  android-components/.buildconfig.yml
  android-components/components/feature/fxsuggest/build.gradle
  android-components/components/feature/fxsuggest/fxsuggest.fml.yaml
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#4615 Bug 1866241 - Expose Shopping status progress field in AC
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/shopping/ProductAnalysisStatus.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
Labels: 🛬 needs landing, approved

#4660 Bug 1864753 - Fix for removing debug APK size alerts
  fenix/plugins/apksize/src/main/java/ApkSizePlugin.kt
Labels: 🛬 needs landing, approved

#4625 Bug 1826883 - Remove juno prefix from onboarding
  fenix/app/metrics.yaml
  fenix/app/onboarding.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/onboarding/view/OnboardingMapperTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingTelemetryRecorder.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/WidgetPinnedReceiver.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingScreen.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/OnboardingMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Labels: 🛬 needs landing, approved

#4674 Bug 1867881 - Update Mockito to version 5.8.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4492 Bug 1864956 - Make Fenix a PDF reader
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  fenix/app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing, approved

#4697 Bug 1868197 - Remove onInstallationFailed callback from AddonFilePicker.
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonFilePicker.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: 🛬 needs landing, approved

#4654 Bug 1866801 - Disable the CBH unsupported site submission.
  fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/ProtectionsView.kt
Labels: 🛬 needs landing, approved

#4698 Bug 1865488: Adds server parameter to push subscription
  fenix/app/src/main/java/org/mozilla/fenix/push/WebPushEngineIntegration.kt
Labels: 🛬 needs landing, approved

#4522 Bug 1862096 – add toolbar related telemetry
  android-components/components/lib/crash/docs/metrics.md
  android-components/components/service/nimbus/docs/metrics.md
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenuView.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: 🛬 needs landing, approved

#4705 Bug 1868315 - Update MessageNotificationWorker to use 'CoroutineWorker' instead of 'Worker'
  fenix/app/src/main/java/org/mozilla/fenix/messaging/MessageNotificationWorker.kt
Labels: 🛬 needs landing, approved

#4695 Bug 1868172 - Add support for `UnsupportedAddonType` error code
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionException.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoWebExtensionExceptionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonFilePicker.kt
  fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
Labels: 🛬 needs landing, approved

#4672 Bug 1867879 - Update AndroidX Benchmark to version 1.2.2
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4708 Bug 1867498 - Add report add-on button in detail view
  android-components/components/feature/addons/src/main/res/values/strings.xml
  fenix/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt
  fenix/app/src/main/res/layout/fragment_installed_add_on_details.xml
  fenix/app/src/test/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragmentTest.kt
Labels: 🛬 needs landing, approved

#4713 Bug 1868434 - Update Firebase Cloud Messaging to version 23.3.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4520 Bug 1864070 - Add secret setting to enable the debug drawer
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/data/DebugSettingsDataStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
Labels: 🛬 needs landing, approved

#4707 Bug 1868323 - Use localised quotes for review checker highlights
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
Labels: 🛬 needs landing, approved

#4728 Bug 1862911 - Disable restartDownloadFromAppNotificationAfterConnectionIsInterruptedTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#4727 Bug 1868533 - Refactor doNotSaveOptionWillNotUpdateALoginTest UI test to match manual test steps
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
Labels: 🛬 needs landing, approved

#4658 Bug 1867539 - Add UI Test Tooling Activation
  fenix/automation/taskcluster/androidTest/lib/testrail_conn.py
  fenix/automation/taskcluster/androidTest/testrail.py
  fenix/automation/taskcluster/androidTest/ui-test.sh
  focus-android/automation/taskcluster/androidTest/lib/testrail_conn.py
  focus-android/automation/taskcluster/androidTest/testrail.py
  focus-android/automation/taskcluster/androidTest/ui-test.sh
  taskcluster/ci/ui-test-apk/kind.yml
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing, approved

#4692 Bug 1867901 — Add string-alias to features in nimbus feature manifests
  android-components/components/service/nimbus/messaging.fml.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/onboarding.fml.yaml
Labels: 🛬 needs landing, approved

#4671 Bug 1858947 - Expose Shopping API reportBackInStock to AC
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#4715 Bug 1866653 - Ensure the tab grid has a minimum of two columns
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
Labels: 🛬 needs landing, approved

#4738 Bug 1868646 — Refactor nimbus.fml.yaml messaging into separate files
  fenix/app/messaging-evergreen-messages.fml.yaml
  fenix/app/messaging-fenix.fml.yaml
  fenix/app/nimbus.fml.yaml
Labels: 🛬 needs landing, approved

#4733 Bug 1868793 - Add missing step to installAddonFromMainMenuTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#4754 Bug 1868858 - Fix test failure SettingsAddonsTest.noCrashWithAddonInstalledTest
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
Labels: 🛬 needs landing, approved

#4729 Bug 1868557 - Add missing steps to deleteCookiesAndSiteDataTest UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt
Labels: 🛬 needs landing, approved

#4752 Bug 1868378 - Indicate the installation method when installing an add-on.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/InstallationMethod.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionRuntime.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonFilePicker.kt
  android-components/components/feature/addons/src/test/java/AddonManagerTest.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonFilePickerTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
Labels: 🛬 needs landing, approved

#4770 Bug 1869049 - stop periodic ingestion when FxSuggest disabled
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing, urgent

#4755 Bug 1868886: Fix Nightly Font Telemetry
  fenix/app/src/androidTest/java/org/mozilla/fenix/components/FontParserTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/fonts/FontEnumerationWorker.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/fonts/FontParser.kt
Labels: 🛬 needs landing, approved

#4749 Bug 1868778 - Make sure the correct process type for extensions process crashes is send in "crash" pings
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt
  android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/service/GleanCrashReporterServiceTest.kt
Labels: 🛬 needs landing, approved

#4734 Bug 1868105 - Translations UI Refactor ListItem to support Radio Button use case.
  fenix/app/src/main/java/org/mozilla/fenix/compose/list/ListItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/automatic/AutomaticTranslationOptionsPreference.kt
Labels: 🛬 needs landing, approved

#4765 Bug 1868323 - Use typographical quotes
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4723 Bug 1867246 - Add placeholder image for product recommendations
  fenix/app/src/main/java/org/mozilla/fenix/compose/Image.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ImagesPlaceholder.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
Labels: 🛬 needs landing, approved

#4751 Bug 1868792 - Add zip file mime type to Fenix the FilePicker.
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonFilePicker.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonFilePickerTest.kt
Labels: 🛬 needs landing, approved

#4612 Bug 1864071 - Add debug drawer fab to an app-wide Composable overlay
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTopSitesRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt
  fenix/app/src/main/res/layout/activity_home.xml
Labels: 🛬 needs landing, approved

#4721 Bug 1866115 - Consume progress from analysis_status and update Review…
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4547 Bug 1855980 - Translations UI Download Model Settings Screen.
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguageItemPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguagesPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguagesPreferenceFragment.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4792 Bug 1869254 - Fix translations strings.
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4793 Bug 1807295 - Re-enable verifyShowSearchSuggestionsToggleTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: 🛬 needs landing, approved

#4767 Bug 1854566 - Fix verifyCreditCardRedirectionsToAutofillSectionAfterInterruptionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
Labels: 🛬 needs landing, approved

#4807 Bug 1869518 - Remove verifyShowSearchSuggestionsToggleTest running on legacy UI task
  fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
Labels: 🛬 needs landing, approved, urgent

#3795 Bug 1854641 - The downloads should stop when the user closes the private tabs.
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing, approved

#4809 Bug 1869534: Use VerticalSwipeRefreshLayout from AndroidComponents
  android-components/samples/browser/src/main/res/layout/fragment_browser.xml
  docs/changelog.md
Labels: 🛬 needs landing, approved

#4796 Bug 1868993 - Addons local file installation's cacheDir is not cleaned.
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonFilePicker.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonFilePickerTest.kt
Labels: 🛬 needs landing, approved

#4812 Bug 1868940 - Cannot install an add-on a from local file on Android <10.
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
Labels: 🛬 needs landing, approved

#4077 Bug 1858789 - vastly more efficient counting of bookmarks for the hom…
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesBookmarksStorage.kt
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/BookmarksStorage.kt
  android-components/components/concept/storage/src/test/java/mozilla/components/concept/storage/BookmarkNodeTest.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkItemMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/DesktopFolders.kt
Labels: 🛬 needs landing, approved

#4813 Bug 1866128 - Add new debug fab icon
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt
  fenix/app/src/main/res/drawable/ic_debug_transparent_fire_24.xml
Labels: 🛬 needs landing, approved

#4804 Bug 1869568 - Use new large test file in downloads related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing, approved

#4808 Bug 1866113 - Add determinate analysis progress ui for review checker
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/NoAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProgressIndicator.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckInfoCard.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4820 Bug 1813521 - Disable failing pauseResumeCancelDownloadTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing, approved

#4817 Bug 1807289 - Enable verifyDownloadInACustomTabTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
Labels: 🛬 needs landing, approved

#4608 Bug 1866799 - Don't crash on FxA `NoExistingAuthFlow` exceptions
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Exceptions.kt
Labels: 🛬 needs landing, approved

#4756 Bug 1858948 - Add shopping NotAvailable product state
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/EnumMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/EnumMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#4825 Bug 1866113 - Unchange changed string
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4790 Bug 1857553 - [a11y] Mark up the Review Checker highlights as lists.
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
Labels: 🛬 needs landing, approved

#4795 Bug 1869134 - Don't crash on SyncScopedKeyMissingInServerResponse
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Exceptions.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
Labels: 🛬 needs landing, approved

#4828 Bug 1869867 - Update experimentation test suite to support smoke tests that don't use the message feature
  fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/conftest.py
Labels: 🛬 needs landing (squash), approved

#4819 Bug 1815395 - Re-enable audio and video permissions tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSitePermissionsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SitePermissionsRobot.kt
Labels: 🛬 needs landing, approved

#4811 Bug 1869567 - Ignore intermittent shopping analysis status tests
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4838 Bug 1866113 - Update analysis in progress string comment
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4834 Bug 1869852 - Update AndroidX Annotation to version 1.7.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4827 Bug 1854860 - Update mockk to version 1.13.8
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4668 Bug 1867801 - Don't use "auth" in our FxA recovery check breadcrumbs
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
Labels: 🛬 needs landing, approved

#4829 Bug 1868453 - Wrap the debug setting data store with an interface
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/data/DebugSettingsDataStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/data/DebugSettingsRepository.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/debugsettings/DefaultDebugSettingsRepositoryTest.kt
Labels: 🛬 needs landing, approved

#4841 Bug 1866927 - Adds ability to enable email tracker blocking protection in private mode
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
Labels: 🛬 needs landing, approved

#4837 Bug 1852234 - Fix verifyCustomTabETPSheetAndToggleTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
Labels: 🛬 needs landing, approved

#4853 Bug 1830005 - Re-enable addPrivateBrowsingShortcutFromHomeScreenCFRTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Labels: 🛬 needs landing, approved

#4880 Bug 1870677 - Fix failing task ui-test-apk-focus-arm-beta
  focus-android/automation/taskcluster/androidTest/ui-test.sh
Labels: 🛬 needs landing, urgent

#4878 Bug 1870647 - Start the Nightly 123 development cycle
  android-components/components/feature/addons/src/main/res/values/strings.xml
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4844 Bug 1869225 - Catch `SuggestApiException`s.
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestIngestionWorker.kt
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestStorage.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestIngestionWorkerTest.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestStorageTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/FxSuggest.kt
Labels: 🛬 needs landing, approved

#4724 Bug 1867606 - Make message param logging api non nullable
  android-components/components/support/base/src/main/java/mozilla/components/support/base/log/Log.kt
  android-components/components/support/base/src/main/java/mozilla/components/support/base/log/logger/Logger.kt
  android-components/components/support/base/src/main/java/mozilla/components/support/base/log/sink/AndroidLogSink.kt
  android-components/components/support/base/src/main/java/mozilla/components/support/base/log/sink/LogSink.kt
  android-components/components/support/base/src/test/java/mozilla/components/support/base/log/sink/AndroidLogSinkTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/FenixLogSink.kt
  fenix/app/src/test/java/org/mozilla/fenix/FenixLogSinkTest.kt
Labels: 🛬 needs landing, approved

#4871 Bug 1807268 - Fix tab counter shortcut menu related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: 🛬 needs landing, approved

#4875 Bug 1807268 - Fix urlBarQuickActionsTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing, approved

#4855 Bug 1814032 - Re-enable verifyMultipleAddressesSelectionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
Labels: 🛬 needs landing, approved

#4805 Bug 1864645 - Focus: Do not send legacy ID in other built-in pings
  focus-android/app/metrics.yaml
Labels: 🛬 needs landing, approved

#4884 Bug 1858948 - Update ProductNotAvailable test to use initial state
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#4858 Bug 1862288 - Runtime Functions for Never Translating a Site
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationsRuntime.kt
Labels: 🛬 needs landing, approved

#4892 Bug 1870668 - Remove the `mozac_feature_addons_authors` string
  android-components/samples/browser/src/main/res/layout/activity_add_on_details.xml
Labels: 🛬 needs landing, approved

#4699 Bug 1867698 – add a basic nav bar composable
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/NavigationBar.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/NavigationBarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#4899 Bug 1870918 - Translations UI String Updates
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4898 Bug 1870829 - Add review checker enabled attribute for custom targeting
  fenix/app/src/main/java/org/mozilla/fenix/messaging/CustomAttributeProvider.kt
Labels: 🛬 needs landing, approved

#4893 Bug 1807268 - Fix turnOffHttpsOnlyModeTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHTTPSOnlyModeTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Labels: 🛬 needs landing, approved

#4902 Bug 1870923: Removes wipe from SyncableLoginsStorage
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/LoginsStorage.kt
  android-components/components/service/sync-logins/README.md
  android-components/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt
Labels: 🛬 needs landing, approved

#4859 Bug 1864709 - Add tab tools and tab counter UI
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/tabs/TabTools.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#4901 Bug 1567912 - Switch pushed Focus Nightly to AAB builds
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/push-bundle/kind.yml
Labels: 🛬 needs landing, approved

#4894 Bug 1870798 - Use fakes in log tests
  android-components/components/support/base/src/test/java/mozilla/components/support/base/log/LogTest.kt
  android-components/components/support/base/src/test/java/mozilla/components/support/base/log/fake/FakeLogSink.kt
  android-components/components/support/base/src/test/java/mozilla/components/support/base/log/logger/LoggerTest.kt
Labels: 🛬 needs landing, approved

#4921 Bug 1807268 - Re-enable openSponsoredShortcutsSettingsOptionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
Labels: 🛬 needs landing, approved

#4923 Bug 1871363 - Remove duplicate review checker resources
  fenix/app/src/main/res/drawable-night/shopping_no_analysis.webp
  fenix/app/src/main/res/drawable-night/shopping_onboarding.webp
  fenix/app/src/main/res/drawable/shopping_no_analysis.webp
  fenix/app/src/main/res/drawable/shopping_onboarding.webp
Labels: 🛬 needs landing, approved

#4639 Bug 1856955 - Translations UI Download Model Settings Screen Popups.
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettings.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/automatic/AutomaticTranslationOptionsPreferenceFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/automatic/AutomaticTranslationPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DeleteLanguageFileDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguageFileDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguagesFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguagesPreferenceFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/LanguageDialogPreferenceFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/nevertranslatesite/NeverTranslateSiteDialogPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/nevertranslatesite/NeverTranslateSiteDialogPreferenceFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/nevertranslatesite/NeverTranslateSitePreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/nevertranslatesite/NeverTranslateSitePreferenceFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguagesFeatureTest.kt
Labels: 🛬 needs landing, approved

#3308 Bug 1831803 - Use getter to access CustomTabSessionState
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#4963 Bug 1872137 - Extract test mode log sink logic
  android-components/components/support/base/src/main/java/mozilla/components/support/base/log/Log.kt
  android-components/components/support/base/src/main/java/mozilla/components/support/base/log/sink/TestModeLogSink.kt
Labels: 🛬 needs landing, approved
