Repository mozilla-mobile/firefox-android, pull requests merged in 2024-03, with the labels that each got.

#5828 Bug 1882914 - Add `iconOnColorDisabled` color token
  fenix/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
Labels: 🛬 needs landing, approved

#5820 Bug 1882740 - Add logs to SettingsSubMenuTabsRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuTabsRobot.kt
Labels: 🛬 needs landing, approved

#5822 Bug 1882768 - Add logs to SettingsTurnOnSyncRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsTurnOnSyncRobot.kt
Labels: 🛬 needs landing, approved

#5821 Bug 1882778 - Remove redundant experiment string
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4965 Bug 1872184 - Rate limit auth recovery checks
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/GlobalAccountManager.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/manager/GlobalAccountManagerTest.kt
Labels: 🛬 needs landing, approved

#5546 Bug 1879649 - Set the data path for the Suggest component
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestStorage.kt
Labels: 🛬 needs landing, approved

#5624 Bug 1876820 - Add translation fetch downloaded languages action
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsBrowserState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationOperation.kt
Labels: 🛬 needs landing, approved

#5854 Bug 1883197 - Fix androidx.navigation:navigation-ui version number
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5789 Bug 1862289 - Translations UI Integration Low Data Translate
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguageFileDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/LanguageDialogPreferenceFragment.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/translations/TranslationsDialogBindingTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/translations/TranslationsDialogMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/translations/TranslationsDialogReducerTest.kt
Labels: 🛬 needs landing, approved

#5834 Bug 1883005 - Add logs to SyncSignInRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncSignInRobot.kt
Labels: 🛬 needs landing, approved

#5835 Bug 1883014 - Add logs to SystemSettingsRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SystemSettingsRobot.kt
Labels: 🛬 needs landing, approved

#5867 Bug 1883319 - Focus: tag englishSystemLocaleTest as smoke UI test
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SettingsGeneralTest.kt
Labels: 🛬 needs landing, approved

#5836 Bug 1883021 - Add logs to ThreeDotMenuBookmarksRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuBookmarksRobot.kt
Labels: 🛬 needs landing, approved

#5687 Bug 1856986 - Translations UI Integration Preference Logic - Page Settings
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationOptionsDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettings.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSwitchItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogStore.kt
  fenix/app/src/test/java/org/mozilla/fenix/translations/TranslationsDialogMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#5833 Bug 1882987 - Add logs to SiteSecurityRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SiteSecurityRobot.kt
Labels: 🛬 needs landing, approved

#5879 Bug 1883412 - Fxa state machine fixes
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/AppServicesStateMachineChecker.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
Labels: 🛬 needs landing, approved

#5815 Bug 1882671 - Update buildconfig.yml helper doc
  taskcluster/scripts/lint/is_buildconfig_yml_up_to_date.py
Labels: 🛬 needs landing, approved

#5826 Bug 1882542 - Eagerly Calculate an Initial Translation Download Size
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#5880 Bug 1883487 - Remove unused generateEncryptionKey function
  android-components/components/lib/dataprotect/src/main/java/mozilla/components/lib/dataprotect/KeyUtils.kt
  android-components/components/lib/dataprotect/src/test/java/mozilla/components/lib/dataprotect/KeyUtilsKtTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#5869 Bug 1883331 - Add logs to SitePermissionsRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SitePermissionsRobot.kt
Labels: 🛬 needs landing, approved

#5875 Bug 1883363 - Add logs to SettingsSubMenuSearchRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt
Labels: 🛬 needs landing, approved

#5832 Bug 1882976 - Add logs to ShareOverlayRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt
Labels: 🛬 needs landing, approved

#5865 Bug 1879868 - Translations Automatically Popup bottom sheet on Offer Translation
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/TranslationsBinding.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/TranslationsBindingTest.kt
Labels: 🛬 needs landing, approved

#5825 Bug 1881831 - Translations Integration - Add "Offer to translate when possible" Connection
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettingsFragment.kt
Labels: 🛬 needs landing, approved

#5739 Bug 1880544 — Add action params to MessageData
  android-components/components/service/nimbus/messaging.fml.yaml
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingController.kt
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingControllerTest.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingHomescreenTest.kt
Labels: 🛬 needs landing, approved

#5901 Bug 1883703 - Direct contributors to Bugzilla for issue tracking
  .github/ISSUE_TEMPLATE/config.yml
Labels: 🕵️‍♀️ needs review

#5873 Bug 1877277 - Translations add Check for isTranslationsEngineSupported
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/TranslationsBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
Labels: 🛬 needs landing, approved

#5572 Bug 1813913 - Added support for Custom Tabs setColorScheme & setColorSchemeParams API
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabConfig.kt
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabConfigHelper.kt
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabConfigHelperTest.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabWindowFeatureTest.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  android-components/components/feature/pwa/src/main/java/mozilla/components/feature/pwa/ext/WebAppManifest.kt
  android-components/components/feature/pwa/src/test/java/mozilla/components/feature/pwa/ext/WebAppManifestKtTest.kt
  android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Window.kt
  android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/WindowTest.kt
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ColorUtils.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/ColorUtilsTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/FennecWebAppIntentProcessor.kt
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  focus-android/app/src/main/java/org/mozilla/focus/browser/integration/NavigationButtonsIntegration.kt
  focus-android/app/src/main/java/org/mozilla/focus/telemetry/TelemetryMiddleware.kt
Labels: 🛬 needs landing, approved

#5766 Bug 1875668 - Bypass cache when intercepting URL requests
  fenix/app/src/main/java/org/mozilla/fenix/components/UrlRequestInterceptor.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/UrlRequestInterceptorTest.kt
Labels: 🛬 needs landing, approved

#5887 Bug 1881803 - update webcompat-reporter to version 2.1.0
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/background.js
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/aboutConfigPrefs.js
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/aboutConfigPrefs.json
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/browserInfo.js
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/browserInfo.json
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/tabExtras.js
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/experimentalAPIs/tabExtras.json
  android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json
Labels: 🛬 needs landing, approved

#5914 Bug 1883700 - Add monorepo migration announcement link to Readme
  README.md
Labels: 🛬 needs landing, approved

#5897 Bug 1873457 - throw exception when an unsupported Activity is used in Activity ext
  fenix/app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  fenix/app/src/test/java/org/mozilla/fenix/ext/ActivityTest.kt
Labels: 🛬 needs landing, approved

#5790 Bug 1882106 - Show undo snackbar when tab is closed via tab strip
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/tabstrip/TabStrip.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  fenix/app/src/main/java/org/mozilla/fenix/ext/Context.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/appstate/TabStripActionTest.kt
Labels: 🛬 needs landing, approved

#5891 Bug 1883870 - Improve test logs in bookmarks and downloads storage deletion in UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt
Labels: 🛬 needs landing, approved

#5378 Bug 1874522 - Repalce coil-kt with AndroidSVG
  android-components/components/browser/icons/build.gradle
  android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/SvgIconDecoder.kt
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5899 Bug 1883651 - stop merging pull requests on main from 2024-03-15
  .mergify.yml
Labels: 🛬 needs landing, approved

#5916 Bug 1883418 - Translate icon is should be visible on Private Browsing Mode
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
Labels: 🛬 needs landing, approved

#5919 Bug 1883420 - Global Automatic translation text should not be cut off
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/automatic/AutomaticTranslationOptionsPreference.kt
Labels: 🛬 needs landing, approved

#5906 Bug 1882572 - Instrumenting Translations Nimbus Feature Release
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationOptionsDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettings.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt
Labels: 🛬 needs landing, approved

#5545 Bug 1868261 - Add hiding on scroll behaviour to navbar
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/BottomToolbarContainerView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/NavbarIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/NavigationBar.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/NavbarIntegrationTest.kt
Labels: 🛬 needs landing, approved

#5923 Bug 1883128 - Fix Logic Issue In Setting Page LanguageSettings
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/state/LanguageSettingTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/LanguageSetting.kt
Labels: 🛬 needs landing, approved

#5913 Bug 1883753 - Remove menu from custom tab bar
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
Labels: 🛬 needs landing, approved

#5893 Bug 1837569 - Fix verifyStateFieldUpdatesInAccordanceWithCountryFieldTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Labels: 🛬 needs landing, approved

#5892 Bug 1833097 - Fix verifyAddAddressViewTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Labels: 🛬 needs landing, approved

#5895 Bug 1883621 - Add fade edge to long titles in tab strip
  fenix/app/src/main/java/org/mozilla/fenix/browser/tabstrip/TabStrip.kt
Labels: 🛬 needs landing, approved

#5938 Bug 1884154 - Remove openInApp Button Reference from UI Tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PDFViewerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
Labels: 🛬 needs landing, approved, urgent

#5926 Bug 1884034 - Add IllegalArgumentException for SvgIconDecoder
  android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/SvgIconDecoder.kt
Labels: 🛬 needs landing, approved, urgent

#5920 Bug 1839160 - Prevent opening a menu twice.
  android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/BrowserMenuController.kt
Labels: 🛬 needs landing, approved

#5840 Bug 1883084 - Update Sentry to version 7.5.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5841 Bug 1883083 - Update Mockito to version 5.11.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5922 Bug 1883984 - Update AndroidX Browser to version 1.8.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5872 Bug 1883054 - Request partial access to photos and videos for Android 14+
  android-components/components/feature/prompts/src/main/AndroidManifest.xml
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/MimeType.kt
Labels: 🛬 needs landing, approved

#5886 Bug 1879373 - Add nav bar to tab preview during swipe-switching
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/BottomToolbarContainerView.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, approved

#5866 Bug 1846707 - Fix closeAllTabsTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#5949 Bug 1884329 - Add logs to TabDrawerRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#5948 Bug 1884300 - Add NullPointerException for SvgIconDecoder
  android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/SvgIconDecoder.kt
Labels: 🛬 needs landing, approved

#5894 Bug 1862295 - Translations UI Integration Integrate Error States
  fenix/app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleViewHolders.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/LocaleUtils.kt
  fenix/app/src/test/java/org/mozilla/fenix/translations/TranslationsDialogReducerTest.kt
Labels: 🛬 needs landing, approved

#5954 Bug 1883465 - Bottom Sheet in landscape should span the full screen
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
Labels: 🛬 needs landing, approved

#5941 Bug 1879332 - ensure synced tabs includes the inactive property
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt
  android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/RemoteTabsStorageTest.kt
  android-components/components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt
  android-components/components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/helper/SyncedTabsProvider.kt
  android-components/components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorageTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/TabSorter.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
  fenix/app/src/test/java/org/mozilla/fenix/sync/ext/SyncedDeviceTabsTest.kt
Labels: 🛬 needs landing, approved

#5881 Bug 1879648 - Disable menu toolbar when nav bar is enabled
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenu.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenuTest.kt
Labels: 🛬 needs landing, approved

#5846 Bug 1879377 - Hide nav bar when the toolbar becomes focused
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/BottomToolbarContainerView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/NavbarIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/appstate/AppStoreReducerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/NavbarIntegrationTest.kt
Labels: 🛬 needs landing, approved

#5942 Bug 1883968 - Translations Interaction Telemetry
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationOptionsDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettings.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: 🛬 needs landing, approved

#5978 Bug 1884187 - Fix Fenix night mode bug after opening a custom tab
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/CustomTabsIntegration.kt
Labels: 🛬 needs landing, approved

#5598 Bug 1876024 - Request screenshot thumbnail when onSwipeStarted
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/ToolbarGestureHandler.kt
Labels: 🛬 needs landing, approved

#5963 Bug 1884487 – simplify NavbarIntegration by removing viewLifecycleOwner
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/NavbarIntegration.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/NavbarIntegrationTest.kt
Labels: 🛬 needs landing, approved

#5903 Bug 1870938 - Add display/edit toolbar separator and update url bar background
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
  android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_edittoolbar.xml
  android-components/components/browser/toolbar/src/main/res/values/dimens.xml
  android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  android-components/components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
  fenix/app/src/main/res/drawable/search_old_url_background.xml
  fenix/app/src/main/res/values-night/colors.xml
  fenix/app/src/main/res/values/attrs.xml
  fenix/app/src/main/res/values/colors.xml
  fenix/app/src/main/res/values/styles.xml
  fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Labels: 🛬 needs landing, approved

#5958 Bug 1884434 - Log breadcrumbs for FxA state transitions
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
  android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
Labels: 🛬 needs landing, approved

#5982 Bug 1884459 - Prevent Offers to Translate after a Translation Occurs
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
Labels: 🛬 needs landing, approved

#5984 Bug 1884666 - Only add Google additional header in search, preferences and webhp urls
  fenix/app/src/main/java/org/mozilla/fenix/components/UrlRequestInterceptor.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/UrlRequestInterceptorTest.kt
Labels: 🛬 needs landing, approved, urgent

#5959 Bug 1884390 - Adjust Unsupported Error in Translations
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/LocaleUtils.kt
  fenix/app/src/test/java/org/mozilla/fenix/translations/TranslationsDialogReducerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/utils/LocaleUtilsTest.kt
Labels: 🛬 needs landing, approved

#5979 Bug 1884653 - Add logs to AccountSettingsRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/AccountSettingsRobot.kt
Labels: 🛬 needs landing, approved

#5993 Bug 1884918 - Add logs to MatcherHelper
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt
Labels: 🛬 needs landing, approved

#5888 Bug 1878827 - Add nav buttons click handling
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/BottomToolbarContainerView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/NavigationBar.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/LongPressIconButton.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, approved

#5989 Bug 1884822 - Suggest: Limit returned suggestion to 1
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
Labels: 🛬 needs landing, approved

#6002 Bug 1885108 - Add logs to TestHelper
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
Labels: 🛬 needs landing, approved

#6004 Bug 1885123 - Add logs to DataGenerationHelper
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/DataGenerationHelper.kt
Labels: 🛬 needs landing, approved

#6001 Revert "Bug 1867717 - Add DownloadsFeature to AddonPopupBaseFragment."
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonInternalSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonPopupBaseFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/WebExtensionActionPopupFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/DownloadDialogUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/DownloadUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/DownloadStyling.kt
  fenix/app/src/main/res/layout/fragment_add_on_internal_settings.xml
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonPopupBaseFragmentTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/BaseBrowserFragmentTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/DownloadDialogUtilsTest.kt
Labels: 🛬 needs landing, approved

#6009 Bug 1885160 - Add logs to AppAndSystemHelper
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/PwaRobot.kt
Labels: 🛬 needs landing, approved

#6012 Bug 1876363 - Ship v125.0.0 of the WebCompat System Addon
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1654877-preev.com-moz-appearance-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1848716-elal.com-unsupported-banner.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1877346-offerup.com-infinite-scroll-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1884842-foodora.cz-height-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/js/bug1631811-datastudio.google.com-indexedDB.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/private-browsing-web-api-fixes.js
Labels: 🛬 needs landing

#5997 Bug 1879372 - Add enabled/disabled nav button states
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/NavigationBar.kt
Labels: 🛬 needs landing, approved

#5353 Bug 1877307 - RFC: Introduce a Store for UI components
  docs/contributing.md
  docs/rfcs/0012-introduce-ui-store.md
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#6014 Bug 1877307 - Fix broken link and title
  docs/contributing.md
Labels: 🛬 needs landing

#5988 Bug 1879370 - Add a ClippingBehavior supporting multiple toolbars
  fenix/.buildconfig.yml
  fenix/app/build.gradle
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/DownloadUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/RedesignToolbarFeature.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/BottomToolbarContainerView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/EngineViewClippingBehavior.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/NavigationBar.kt
  fenix/app/src/main/java/org/mozilla/fenix/downloads/DynamicDownloadDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/dimens.xml
  fenix/app/src/test/java/org/mozilla/fenix/browser/BaseBrowserFragmentTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/EngineViewClippingBehaviorTest.kt
Labels: 🛬 needs landing, approved

#6006 Bug 1885141 - Add logs to MockBrowserDataHelper
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/Assert.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/IdlingResourceHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MockBrowserDataHelper.kt
Labels: 🛬 needs landing, approved

#6003 Bug 1884891 - Display only private in tab strip when switched to private tab
  fenix/app/src/main/java/org/mozilla/fenix/browser/tabstrip/TabStripState.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/tabstrip/TabStripStateTest.kt
Labels: 🛬 needs landing, approved

#6017 Bug 1819872 - Disable failing copyLinkAddressTest UI test
  focus-android/app/src/androidTest/java/org/mozilla/focus/activity/ContextMenusTest.kt
Labels: 🛬 needs landing, approved

#6018 Bug 1885288 - Add logs to FeatureSettingsHelperDelegate
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt
Labels: 🛬 needs landing, approved

#6019 Bug 1885300 - Add logs to HomeActivityTestRule
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
Labels: 🛬 needs landing, approved

#6021 Bug 1885314 - Add more logs to RetryTestRule
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/RetryTestRule.kt
Labels: 🛬 needs landing, approved

#5737 Bug 1880520 - [Onboarding] Enable "Add Search Widget" card
  fenix/app/onboarding.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
Labels: 🛬 needs landing, approved

#6024 Bug 1885399 - Fix clipping behaviour
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing, approved

#5793 Bug 1882404 - Expose granted permissions on AC.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/MockWebExtension.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
  android-components/components/feature/addons/src/test/java/AddonTest.kt
Labels: 🛬 needs landing, approved

#4416 Bug 1858895 - Fix rotation size change for FeltPrivacyInfoCard.
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/FeltPrivacyInfoCard.kt
Labels: 🛬 needs landing, approved

#5898 Bug 1883651 - turn off cron and workflows on `main`
  .cron.yml
  .github/workflows/ac-sync-strings.yml
  .github/workflows/fenix-sync-strings.yml
  .github/workflows/fenix-update-nimbus-experiments.yml
  .github/workflows/focus-sync-strings.yml
  .github/workflows/focus-update-nimbus-experiments.yml
  .github/workflows/import-l10n.yml
Labels: 🛬 needs landing, approved

#6036 Bug 1885946 - Fix Fenix/Focus beta test run calls in ui-tests-apk configuration
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#6038 Bug 1883651 - turn off ac-update-geckoview on main
  .github/workflows/ac-update-geckoview.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#6045 Bug 1886730 - catch NLP during RemoteSetting getRecords() failure
  android-components/components/support/remotesettings/src/main/java/mozilla/components/support/remotesettings/RemoteSettingsClient.kt
Labels: 🛬 needs landing

#6046 Bug 1886730 - catch NLP during RemoteSetting getRecords() failure
  android-components/components/support/remotesettings/src/main/java/mozilla/components/support/remotesettings/RemoteSettingsClient.kt
Labels: 🛬 needs landing
