Repository mozilla-mobile/firefox-android, pull requests merged in 2024-01, with the labels that each got.

#4977 Bug 1856955 - Part 2: Remove unnecessary font weight in DownloadLanguageFileDialog title
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguageFileDialog.kt
Labels: 🛬 needs landing, approved

#4927 Bug 1864710 - Add UI for creating tabs
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/tabs/TabTools.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4860 Bug 1862263 - Translations Error Support
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/translate/GeckoTranslationUtils.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationError.kt
Labels: 🛬 needs landing, approved

#4798 Bug 1864072 - Create initial drawer UI
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawer.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt
  fenix/app/src/main/res/layout/activity_home.xml
Labels: 🛬 needs landing, approved

#4940 Bug 1871548 - Add telemetry for Open PDF in Fenix
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/SafeIntent.kt
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
Labels: 🛬 needs landing, approved

#4590 Bug 1868371 - Add more test data to Fx suggest related UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/DataGenerationHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/FirefoxSuggestTest.kt
Labels: 🛬 needs landing, approved

#4877 Bug 1870648 - Removed redundant MS_PRECISION variable from ExternalAppBrowserFragment
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
Labels: 🛬 needs landing, approved

#4936 Bug 1807268 - Re-enable openSponsorsAndYourPrivacyOptionTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt
Labels: 🛬 needs landing, approved

#5003 Bug 1872777 - Update LeakCanary to version 2.13
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4939 Bug 1858370 - use clearDataFromBaseDomain for clearData
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
Labels: 🛬 needs landing, approved

#4930 Bug 1836167 - Fix Bookmark Open telemetry
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
Labels: 🛬 needs landing, approved

#4928 Bug 1806838 - Update extension icon when invalidate is called.
  android-components/components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItem.kt
  android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItemTest.kt
Labels: 🛬 needs landing, approved

#4842 Bug 1864073 - Stand up debug drawer Store and State
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerState.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt
  fenix/app/src/test/java/org/mozilla/fenix/debugsettings/DebugDrawerStoreTest.kt
Labels: 🛬 needs landing, approved

#5010 Bump Application Services Release to 122.0.1
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
Labels: 🛬 needs landing

#4924 Bug 1868989 - Translations UI Add Translate Page Browser Menu Button.
  fenix/app/metrics.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MainMenuTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: 🛬 needs landing, approved

#4973 Bug 1868120 - RC recommendation impression once per product aid combination
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingState.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingStateReducer.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryService.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/appstate/ShoppingActionTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckTelemetryService.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Labels: 🛬 needs landing, approved

#5009 Bug 1872170 - Fix Pull to Refresh triggered after an upward overscroll on a page
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
Labels: 🛬 needs landing, approved

#4926 Bug 1864890 - fix home button margin on display toolbar
  android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
Labels: 🛬 needs landing, approved

#5025 Bug 1867597 - Enable extensions process unconditionally
  fenix/app/nimbus.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/extensions/ExtensionProcessTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
Labels: 🛬 needs landing, approved

#4931 Bug 1864711 - Plumb logic into TabTools to create tabs
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/tabs/TabTools.kt
Labels: 🛬 needs landing, approved

#4840 Bug 1821706 - Allow Android OS to decide when to show the keyboard for edit toolbar
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
Labels: 🛬 needs landing, approved

#5028 Bug 1872703 - Named Translation Errors
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/translate/GeckoTranslationUtils.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationError.kt
Labels: 🛬 needs landing, approved

#5018 Bug 1872964 - Add FCM testing documentation
  .gitignore
  fenix/docs/Firebase-Cloud-Messaging-for-WebPush.md
Labels: 🛬 needs landing, approved

#5007 Bug 1807295 - Fix verifyShowSearchSuggestionsToggleTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: 🛬 needs landing, approved

#4906 Bug 1868260 – Sync navbar position with toolbar
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BottomToolbarContainerView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/NavigationBar.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, approved

#5044 Bug 1873277 - Update acronym dictionary
  fenix/docs/Acronym-dictionary.md
Labels: 🛬 needs landing, approved

#5046 Bug 1873280 - Update Firebase Cloud Messaging to version 23.4.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4914 Bug 1871156 - Report impressions and clicks for Firefox Suggestions in the `events` ping.
  android-components/components/feature/fxsuggest/README.md
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/facts/FxSuggestFacts.kt
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/facts/FxSuggestFactsMiddleware.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestFactsMiddlewareTest.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestFactsTest.kt
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
Labels: 🛬 needs landing, approved

#5023 Bug 1873200 - New cookie banner blocker UI smoke tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerBlockerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: 🛬 needs landing, approved

#4937 Bug 1844750 - Improve fallback for homepage images thumbnails
  fenix/app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarks.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
Labels: 🛬 needs landing, approved

#5047 Bug 1873281 - Update Sentry to version 7.1.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4725 Bug 1862190: Expose and integrate the generated strong password in the authentication flow
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  android-components/components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/dataset/LoginDatasetBuilder.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/concept/PasswordPromptView.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/StrongPasswordPromptViewListener.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/SuggestStrongPasswordBar.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/SuggestStrongPasswordDelegate.kt
  android-components/components/feature/prompts/src/main/res/layout/mozac_feature_suggest_strong_password_view.xml
  android-components/components/feature/prompts/src/main/res/values/strings.xml
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/login/LoginPickerTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/login/StrongPasswordPromptViewListenerTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/login/SuggestStrongPasswordBarTest.kt
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/layout/fragment_browser.xml
  fenix/app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing, approved

#5012 Bug 1864074 - Create debug drawer landing page UI
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawer.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawerHome.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawerMenuItem.kt
Labels: 🛬 needs landing, approved

#5011 Bug 1872885 - Move debug drawer store management from `DebugOverlay` to `FenixOverlay`
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerState.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DrawerStatus.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/FenixOverlay.kt
  fenix/app/src/test/java/org/mozilla/fenix/debugsettings/DebugDrawerStoreTest.kt
Labels: 🛬 needs landing, approved

#5019 Bug 1869664 - Add more toolbar telemetry
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
  android-components/components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
Labels: 🛬 needs landing, approved

#4974 Bug 1856990 - Translations UI Error States.
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#4803 Bug 1813794: Save search results when navigating back from saved logins list
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/controller/LoginsListController.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
  fenix/app/src/main/res/menu/login_list.xml
  fenix/app/src/test/java/org/mozilla/fenix/settings/logins/LoginsListControllerTest.kt
Labels: 🛬 needs landing, approved

#5065 Bug 1873375 - Should open shared search terms in private mode if 'Open links in a private tab' is set.
  fenix/app/src/main/java/org/mozilla/fenix/components/IntentProcessors.kt
Labels: 🛬 needs landing, approved

#5080 Bug 1859192 - Always intercept app links if scheme is not supported by engine
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Labels: 🛬 needs landing, approved

#5030 Bug 1864075 - Create navigation middleware for the debug drawer
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/navigation/DebugDrawerDestination.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/navigation/DebugDrawerRoute.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerNavigationMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerStore.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/debugsettings/DebugDrawerNavigationMiddlewareTest.kt
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#4835 Bug 1872753- handle RemoteSettings serialization to disk with kotlinx
  android-components/components/support/remotesettings/build.gradle
  android-components/components/support/remotesettings/src/main/java/mozilla/components/support/remotesettings/RemoteSettingsClient.kt
  android-components/components/support/remotesettings/src/test/java/mozilla/components/support/remotesettings/RemoteSettingsClientTest.kt
Labels: 🛬 needs landing, approved

#4824 Bug 1867431 - Remove the app flavour from the "What's new in Firefox" string
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/about/AboutFragment.kt
Labels: 🛬 needs landing, approved

#4874 Bug 1857850 - [a11y] Improve experience when accessing links in text
  fenix/app/src/main/java/org/mozilla/fenix/compose/LinkText.kt
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#2829 Bug 1843057 - On Android 14, close private tabs when notification is dismissed.
  android-components/components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/notification/AbstractPrivateNotificationService.kt
  fenix/app/src/main/java/org/mozilla/fenix/session/PrivateNotificationService.kt
  fenix/app/src/main/res/values/strings.xml
  focus-android/app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5094 Bug 1864078 - Create debug drawer navigation UI
  fenix/app/build.gradle
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawer.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/FenixOverlay.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5106 Bug 1874027 - Fix getSponsoredFxSuggestPlaceHolder
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/DataGenerationHelper.kt
Labels: 🛬 needs landing, approved

#5087 Bug 1858874 - Fix goToSettingsFromOpenLinksInAppCFRTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Labels: 🛬 needs landing

#5117 Bug 1874124 - Add foregroundServiceType for DownloadService and FOREGROUND_SERVICE_DATA_SYNC permission.
  android-components/components/feature/downloads/README.md
  android-components/components/feature/downloads/src/main/AndroidManifest.xml
  android-components/samples/browser/src/main/AndroidManifest.xml
  fenix/app/src/main/AndroidManifest.xml
  focus-android/app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing, approved

#5118 Bug 1855691 - Converted qr_cam_focus.png to WebP
  android-components/components/feature/qr/src/main/res/drawable-hdpi/qr_cam_focus.png
  android-components/components/feature/qr/src/main/res/drawable-hdpi/qr_cam_focus.webp
  android-components/components/feature/qr/src/main/res/drawable-ldpi/qr_cam_focus.png
  android-components/components/feature/qr/src/main/res/drawable-ldpi/qr_cam_focus.webp
  android-components/components/feature/qr/src/main/res/drawable-mdpi/qr_cam_focus.png
  android-components/components/feature/qr/src/main/res/drawable-mdpi/qr_cam_focus.webp
  android-components/components/feature/qr/src/main/res/drawable-xhdpi/qr_cam_focus.png
  android-components/components/feature/qr/src/main/res/drawable-xhdpi/qr_cam_focus.webp
  android-components/components/feature/qr/src/main/res/drawable-xxhdpi/qr_cam_focus.png
  android-components/components/feature/qr/src/main/res/drawable-xxhdpi/qr_cam_focus.webp
  android-components/components/feature/qr/src/main/res/drawable-xxxhdpi/qr_cam_focus.png
  android-components/components/feature/qr/src/main/res/drawable-xxxhdpi/qr_cam_focus.webp
Labels: 🛬 needs landing, approved

#5078 Bug 1873511 - New `supportedLanguages` and `translationError` on TranslationsState, with `TranslateExceptionAction` Refactor
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationOperation.kt
Labels: 🛬 needs landing, approved

#5112 Bug 1874076 - Update AndroidX Lifecycle to version 2.7.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2909 Bug 1829156 - Target SDK 34 in Focus.
  focus-android/app/build.gradle
Labels: 🛬 needs landing, approved

#5131 Bug 1862190: Add detailed description for dialog message
  android-components/components/feature/prompts/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5136 Bug 1854936 - Update notification reminder delay to 5 min instead of 5 sec
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/middleware/RecordingDevicesMiddleware.kt
Labels: 🛬 needs landing, approved

#5140 Bug 1838843 - Ship v123.0.0 of the WebCompat System Addon.
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1570328-developer-apple.com-transform-scale.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1800000-www.honda.co.uk-choose-dealer-button-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1868345-tvmovie.de-scroll-fix.css
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
  android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/blogger.js
Labels: 🛬 needs landing, approved

#5146 Bug 1862190: Format string to remove double space
  android-components/components/feature/media/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#5051 Bug 1873302 - Update StoreThreadFactory exception message
  android-components/components/lib/state/src/main/java/mozilla/components/lib/state/internal/StoreThreadFactory.kt
Labels: 🛬 needs landing, approved

#5147 Bug 1866133 - Add additional headers for Google search
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/request/RequestInterceptor.kt
  fenix/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Services.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/UrlRequestInterceptor.kt
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/UrlRequestInterceptorTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
Labels: 🛬 needs landing, approved

#5074 Bug 1868358 - [a11y] "More to consider" is read as a heading
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
Labels: 🛬 needs landing, approved

#5143 Bug 1861616 - Prevent Custom Tabs from stopping background media
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: 🛬 needs landing, approved

#5097 Bug 1828927 - Fix apply wallpaper anr
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
Labels: 🛬 needs landing, approved

#5132 Bug 1874374 - Fix wallpaper settings home navigation issue
  fenix/app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettingsFragment.kt
Labels: 🛬 needs landing, approved

#5042 Bug 1871142 - Translations UI Language Dropdowns.
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
Labels: 🛬 needs landing, approved

#5167 Bug 1828927 - Remove accidental debug logs
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, approved

#5138 Bug 1874124 - Add foregroundServiceType for Crash Services and FOREGROUND_SERVICE_SPECIAL_USE permission.
  android-components/components/lib/crash/src/main/AndroidManifest.xml
Labels: 🛬 needs landing, approved

#5049 Bug 1872971 - Move CODEOWNERS file to correct location
  CODEOWNERS
  android-components/CODEOWNERS
Labels: 🛬 needs landing, approved

#5166 Bug 1874675 - Replaced usages of runBlocking in MessageNotificationWorker
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  fenix/app/build.gradle
  fenix/app/src/main/java/org/mozilla/fenix/messaging/MessageNotificationWorker.kt
Labels: 🛬 needs landing, approved

#5149 Bug 1567912 - Switch pushed Focus Beta/Release to AAB builds
  taskcluster/ci/mark-as-shipped/kind.yml
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/push-bundle/kind.yml
  taskcluster/ci/release-notify-push/kind.yml
  taskcluster/ci/release-notify-ship/kind.yml
  taskcluster/ci/version-bump/kind.yml
Labels: 🛬 needs landing (squash), approved

#4732 Bug 1865306 - Decouple HomeActivity and ExternalAppBrowserActivity RFC
  docs/rfcs/0011-decouple-home-activity-and-external-app-browser-activity.md
Labels: 🛬 needs landing, approved

#5120 Bug 1874146 - Add package to attributionIntent on LoginDatasetBuilder.
  android-components/components/feature/autofill/src/main/java/mozilla/components/feature/autofill/response/dataset/LoginDatasetBuilder.kt
Labels: 🛬 needs landing, approved

#5173 Bug 1874148 - AddMODE_BACKGROUND_ACTIVITY_START_ALLOWED to sendNonFatalCrashIntent on CrashReporter.
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
Labels: 🛬 needs landing, approved

#5104 Bug 1868262 - Add menu button to nav toolbar
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BottomToolbarContainerView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/NavigationBar.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🛬 needs landing, work in progress

#5022 Bug 1872996 - Detekt should not warn of LongParameterList for Compose functions
  android-components/README.md
  android-components/config/detekt-baseline.xml
  android-components/config/detekt.yml
  fenix/config/detekt.yml
  fenix/detekt-baseline.xml
  focus-android/quality/detekt-baseline.xml
  focus-android/quality/detekt.yml
Labels: 🛬 needs landing, approved

#5175 Bug 1874733 - Add exported flag to broadcast receiver for notification dismissal.
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/middleware/RecordingDevicesMiddleware.kt
Labels: 🛬 needs landing, approved

#5184 Bug 1874880 - Update Mockito to version 5.9.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5144 Bug 1874446 - Update Sentry to version 7.2.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5141 Bug 1812843 - Increased the width for a CustomTabsToolbarFeature action button
  android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
Labels: 🛬 needs landing, approved

#5193 Bug 1842154 - Disable notificationCanBeDismissedIfDownloadIsInterrupt…
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Labels: 🛬 needs landing, approved

#5169 Bug 1868291 - Fix Pocket tests by always restarting app on home
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/RetryTestRule.kt
Labels: 🛬 needs landing, approved

#5192 Bug 1843057 - Remove previous string comment.
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5122 Bug 1864076 - Integrate Navigation Middleware into the Debug Drawer
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/navigation/DebugDrawerDestination.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/navigation/DebugDrawerRoute.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerNavigationMiddleware.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawer.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawerHome.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawerMenuItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/FenixOverlay.kt
  fenix/app/src/test/java/org/mozilla/fenix/debugsettings/DebugDrawerNavigationMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#5148 Bug 1855979 - Basic Translation Beginning
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsController.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsInteractor.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/translations/TranslationsControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/translations/TranslationsInteractorTest.kt
Labels: 🛬 needs landing, approved

#5196 Bug 1873858 - fix external-gradle-dependencies gradle project dir for focus
  taskcluster/android_taskgraph/transforms/external_gradle_dependencies.py
Labels: 🛬 needs landing, approved

#5185 Bug 1874148 - Add activityOptions to send in CrashReporter.
  android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt
Labels: 🛬 needs landing, approved

#4872 Bug 1870613 - Extracted the HomeActivity`getBreadcrumbMessage`, `getIntentSource` and `getIntentSessionId` as generic Activity functions
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  fenix/app/src/test/java/org/mozilla/fenix/HomeActivityTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivityTest.kt
Labels: 🛬 needs landing, approved

#4854 Bug 1870232 - Delegate the Activity's getNavDirections() functionality
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/ext/Activity.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/test/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivityTest.kt
Labels: 🛬 needs landing, approved

#5116 Bug 1874885 - Fix reset to default locale when a test crashes
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeNavigationToolbarTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Labels: 🛬 needs landing, approved

#5178 Bug 1874768 - Hide default browser onboarding card if user already set us as default browser
  fenix/app/onboarding.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/onboarding/view/OnboardingMapperTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingMapper.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageState.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageUiData.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingScreen.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/OnboardingMapperTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/OnboardingPageUiDataTest.kt
Labels: 🛬 needs landing, approved

#5188 Bug 1828667 - Remove conditioned profiles from taskcluster
  taskcluster/ci/browsertime/kind.yml
Labels: 🛬 needs landing, approved

#5172 Bug 1872704 - Fix HomeActivity leak by ExtensionsProcessDisabledController
  android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/ExtensionsProcessDisabledPromptObserver.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledBackgroundController.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledForegroundController.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledBackgroundControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledForegroundControllerTest.kt
Labels: 🛬 needs landing, approved

#5209 Bug 1875360 - Update archived "Good First Issue" search with Bugzilla search in Fenix README.md
  fenix/README.md
Labels: 🛬 needs landing (squash), approved

#5202 Bug 1875111 - Remove stateAlwaysHidden from manifest for MainActivity.
  focus-android/app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing, approved

#5216 Bug 1874831 - Disable failing Sponsored FF Suggest UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/FirefoxSuggestTest.kt
Labels: 🛬 needs landing, approved

#5123 Bug 1871098 - Integrate TabTools into the Debug Drawer
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/navigation/DebugDrawerRoute.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/FenixOverlay.kt
Labels: 🛬 needs landing, approved

#5225 Bug 1862738 - Put credential management strings before translation
  android-components/components/feature/prompts/src/main/res/values/strings.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5221 Bug 1875497 - fix kind-dependencies for ui-test-apk
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing, approved

#5171 Bug 1871408 - Translations UI Add Messages Under On Toggles
  fenix/app/src/main/java/org/mozilla/fenix/compose/SwitchWithLabel.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationOptionsDialog.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettings.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSwitchItem.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5206 Bug 1867539 - reformat testrail.py with black
  fenix/automation/taskcluster/androidTest/lib/testrail_conn.py
  fenix/automation/taskcluster/androidTest/testrail.py
  focus-android/automation/taskcluster/androidTest/lib/testrail_conn.py
  focus-android/automation/taskcluster/androidTest/testrail.py
Labels: 🛬 needs landing, approved

#5240 Bug 1867539 - fix exception formatting in testrail script
  fenix/automation/taskcluster/androidTest/testrail.py
  focus-android/automation/taskcluster/androidTest/testrail.py
Labels: 🛬 needs landing, approved

#5241 Set version to 124.0a1
  version.txt
Labels: approved

#5170 Bug 1807078 - use min for thumbail size of TabPreview
  fenix/app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt
Labels: 🛬 needs landing, approved

#5222 Bug 1875515 - record Nimbus is_ready event
  docs/changelog.md
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
Labels: 🛬 needs landing, approved

#5245 Bug 1875869 - Start the Nightly 124 development cycle
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5135 Bug 1874388 - Remove unused notification pre prompt
  fenix/app/metrics.yaml
  fenix/app/nimbus.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/HomeNotificationPermissionDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/NotificationPermissionDialogScreen.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/navigation/nav_graph.xml
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5075 Bug 1807073 - Prevent pull-to-refresh after scrolling down
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
  android-components/components/ui/widgets/src/main/java/mozilla/components/ui/widgets/VerticalSwipeRefreshLayout.kt
Labels: 🛬 needs landing, approved

#5250 Bug 1875923 - Update max_line_length in editorconfig to match detekt
  android-components/.editorconfig
  fenix/.editorconfig
  focus-android/.editorconfig
Labels: 🛬 needs landing, approved

#5249 Bug 1875382: add ending punctuation
  android-components/components/feature/media/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5223 Bug 1875514 - Only send installation ping when we receive adjust metrics
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/FirstSessionPing.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt
Labels: 🛬 needs landing, approved

#5215 Bug 1838580 - [a11y] Increase tap area for search engine icon
  fenix/app/src/main/java/org/mozilla/fenix/ext/View.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/toolbar/SearchSelectorBinding.kt
Labels: 🛬 needs landing, approved

#5195 Bug 1818183 - Fix top site not showing up in top sites UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTopSitesRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#5265 Bug 1850006 - Update changelog.
  docs/changelog.md
Labels: 🛬 needs landing, approved

#5239 Bug 1832147 - Keep the profiler presets in sync with their desktop counterparts
  fenix/app/src/main/java/org/mozilla/fenix/perf/ProfilerUtils.kt
Labels: 🛬 needs landing, approved

#5278 Bug 1875891 - Adding MalformedInputException to catch list of handlePlacesExceptions.
  android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt
Labels: 🛬 needs landing, approved

#4610 Bug 1866851 - Fix finalizeDevice result check
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
Labels: 🛬 needs landing, approved

#5204 Bug 1875294 - Record breadbcrumbs before crashing with UnsatsisfiedLinkError
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing, approved

#5280 Bug 1875087 - Do no intercept content urls in applinks
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Labels: 🛬 needs landing, approved

#5029 Bug 1860472 - Periodically clean the Uploads cacheDir.
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt
  android-components/components/feature/prompts/src/androidTest/java/mozilla/components/feature/prompts/file/OnDeviceFilePickerTest.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FileUploadsDirCleaner.kt
  android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FileUploadsDirCleanerMiddleware.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FilePickerTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FileUploadsDirCleanerMiddlewareTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FileUploadsDirCleanerTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonPopupBaseFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
  focus-android/app/src/main/java/org/mozilla/focus/Components.kt
  focus-android/app/src/main/java/org/mozilla/focus/FocusApplication.kt
  focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing, approved

#5261 Bug 1876122 - Enable the debug drawer in Beta and Release
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
Labels: 🛬 needs landing, approved

#5259 Bug 1876026 - Add more test logs to AddToHomeScreenRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/AddToHomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#5260 Bug 1876036 - Add more test logs to BookmarksRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: 🛬 needs landing, approved

#5236 Bug 1861744 - Don't display pending to delete bookmarks when refresh
  fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragment.kt
Labels: 🛬 needs landing, approved

#5292 Bug 1875382: add ending punctuation & change strings ids
  android-components/components/feature/media/src/main/java/mozilla/components/feature/media/middleware/RecordingDevicesMiddleware.kt
  android-components/components/feature/media/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5279 Bug 1876332 - Refactoring out Translations Controller and Interactor
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsController.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsInteractor.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/translations/TranslationsControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/translations/TranslationsInteractorTest.kt
Labels: 🛬 needs landing, approved

#5296 Bug 1874124 - Add foregroundServiceType for sample app CrashService and FOREGROUND_SERVICE_SPECIAL_USE permission
  android-components/samples/crash/src/main/AndroidManifest.xml
Labels: 🛬 needs landing, approved

#5092 Bug 1870347 - Improve content description for permissions in installed add-ons page
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonPermissionsAdapter.kt
  android-components/components/feature/addons/src/main/res/values/strings.xml
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsPermissionsAdapterTest.kt
Labels: 🛬 needs landing, approved

#5108 Bug 1859052 - Use fallback URL if user cancelled launching in external app
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Labels: 🛬 needs landing, approved

#5291 Bug 1876481 - Updated `HomeActivity` variables & funcs with the necessary visibility modifiers to enforce constraints.
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: 🛬 needs landing, approved

#5224 Bug 1874441 - Connecting Dropdowns to Translate Button
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/state/TranslationEngineStateTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationEngineState.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5302 Bug 1876567 - Fix Middleware Issue with Processing Translations States
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/EngineDelegateMiddleware.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/EngineDelegateMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#5293 Bug 1876510 - Add more test logs to BrowserRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing, approved

#5289 Bug 1854333 - Fix dismissOpenLinksInAppCFRTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Labels: 🛬 needs landing, approved

#5282 Bug 1876397 - Update Mockito to version 5.10.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5320 Bug 1876751 - Remove redundant preferences from SettingsFragment
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
  fenix/app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing, approved

#5114 Bug 1871093 - Review checker change info card button color
  fenix/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
Labels: 🛬 needs landing, approved

#5321 Bug 1876752 - Reordered preferences in `SettingsFragment` to match the UI layout
  fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
Labels: 🛬 needs landing, approved

#4493 Bug 1864692 - Create new startup-test Robo Test Task for Fenix/Focus w/opt-enabled Nightly
  fenix/automation/taskcluster/androidTest/flank-arm-start-test-robo.yml
  focus-android/automation/taskcluster/androidTest/flank-arm-start-test-robo.yml
  focus-android/automation/taskcluster/androidTest/robo-test.sh
  taskcluster/ci/startup-test/kind.yml
Labels: 🛬 needs landing, approved

#5314 Revert "Bug 1812843 - Increased the width for a CustomTabsToolbarFeature action button"
  android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
Labels: 🛬 needs landing, approved

#5305 Bug 1876610 - Minor Translations UI Adjustments
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/automatic/AutomaticTranslationPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/nevertranslatesite/NeverTranslateSitePreference.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5048 Bug 1870335 - Merge content descriptions in the Add-ons details screen.
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegate.kt
  fenix/app/src/main/res/layout/fragment_add_on_details.xml
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegateTest.kt
Labels: 🛬 needs landing, approved

#5304 Bug 1873983 - Translations Secret Settings Option in Nightly
  fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Labels: 🛬 needs landing, approved

#4845 Bug 1867717 - Add DownloadsFeature to AddonPopupBaseFragment
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonInternalSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonPopupBaseFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/WebExtensionActionPopupFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/DownloadDialogUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/DownloadUtils.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/DownloadStyling.kt
  fenix/app/src/main/res/layout/fragment_add_on_internal_settings.xml
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonPopupBaseFragmentTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/BaseBrowserFragmentTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/DownloadDialogUtilsTest.kt
Labels: 🛬 needs landing, approved

#5306 Bug 1864760 - Added actions to Toolbar and MenuButton to hide and show the menu button.
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
  android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/MenuButton.kt
  android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt
  android-components/components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt
  android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt
  android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#5355 Revert "Bug 1875923 - Update max_line_length in editorconfig to match detekt"
  android-components/.editorconfig
  fenix/.editorconfig
  focus-android/.editorconfig
Labels: 🛬 needs landing, approved, urgent

#5349 Bug 1877039 - Do not attempt to trigger external app if new request was too soon
  android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt
  android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Labels: 🛬 needs landing, approved

#5300 Bug 1852224 - Prevent background media from being stopped when existing application from an external link.
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/perf/StartupPathProvider.kt
  fenix/app/src/test/java/org/mozilla/fenix/perf/StartupPathProviderTest.kt
Labels: 🛬 needs landing, approved

#5313 Bug 1876700 - Add more test logs to CollectionRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
Labels: 🛬 needs landing, approved

#5315 Bug 1876720 - Add more test logs to ComposeTabDrawerRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#5325 Bug 1876844 - Translations LanguageSetting Helper
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/state/LanguageSettingTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/LanguageSetting.kt
Labels: 🛬 needs landing, approved

#4753 Bug 1864760 - Hide toolbar actions in BaseBrowserFragment toolbar
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultToolbarIntegrationTest.kt
Labels: approved

#5045 Bug 1870351 - Improve touch targets Add-ons details screen.
  fenix/app/src/main/res/layout/fragment_add_on_details.xml
Labels: 🛬 needs landing, approved
