Repository mozilla-mobile/firefox-android, pull requests merged in 2024-02, with the labels that each got.

#5388 Bug 1870347 - Update the comment for the content description of the addon permission item.
  android-components/components/feature/addons/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5371 Bug 1877440 - Use only TestHelper snack bar verification function in UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeCollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#5402 Bug 1877938 - Remove redundant assertion functions from BookmarksRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeBookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: 🛬 needs landing, approved

#5411 Bug 1682027 - Disable failing facebook android test.
  taskcluster/ci/browsertime/kind.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#5410 Bump Application Services Release to 123.0.1
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
Labels: 🛬 needs landing

#5408 Bug 1833666 - Update original RFC guidelines with stakeholders
  docs/rfcs/0001-rfc-process.md
Labels: 🛬 needs landing, approved

#5323 Bug 1868539 - Add method of changing remote server url
  android-components/components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/SerpTelemetryRepository.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
  fenix/app/src/main/res/values/preference_keys.xml
  fenix/app/src/main/res/values/static_strings.xml
  fenix/app/src/main/res/xml/secret_settings_preferences.xml
  focus-android/app/src/main/java/org/mozilla/focus/settings/advanced/SecretSettingsFragment.kt
  focus-android/app/src/main/java/org/mozilla/focus/settings/advanced/SharedPreferenceUpdater.kt
  focus-android/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
  focus-android/app/src/main/java/org/mozilla/focus/utils/Settings.kt
  focus-android/app/src/main/res/values/preference_keys.xml
  focus-android/app/src/main/res/values/static_strings.xml
  focus-android/app/src/main/res/xml/secret_settings.xml
Labels: 🛬 needs landing, approved

#5368 Bug 1813875 - Prevent the inherited theming implementation being applied to Custom Tabs views
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing, approved

#5390 Bug 1877847 - Remove Suggest error reporting
  android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestStorage.kt
  android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestStorageTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/FxSuggest.kt
Labels: 🛬 needs landing, approved

#5427 Bug 1870050 - Properly define buildConfigField SUPPORTED_LOCALE_ARRAY
  fenix/app/build.gradle
Labels: 🛬 needs landing

#5423 Bug 1840969 - Add title for homepage default browser info card
  fenix/app/messaging-evergreen-messages.fml.yaml
  fenix/app/src/main/java/org/mozilla/fenix/compose/MessageCard.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5387 Bug 1809798 - Loads the right wallpaper when changing orientation
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
  fenix/app/src/test/java/org/mozilla/fenix/wallpapers/WallpapersUseCasesTest.kt
Labels: 🛬 needs landing, approved

#5434 Bug 1878409 - Update Gradle to version 8.6
  android-components/gradle/wrapper/gradle-wrapper.properties
  android-components/gradlew.bat
  fenix/gradle/wrapper/gradle-wrapper.properties
  fenix/gradlew.bat
  focus-android/gradle/wrapper/gradle-wrapper.properties
  focus-android/gradlew.bat
Labels: 🛬 needs landing, approved

#5431 Bug 1878091 - Translations Engine State and Translation Status Sync
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
Labels: 🛬 needs landing, approved

#5455 Bug 1807080 - Fix PTR dark theme colors
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Labels: 🛬 needs landing, approved

#5386 Bug 1877712 - Update Mock Translations Languages
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/automatic/AutomaticTranslationPreference.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/preferences/downloadlanguages/DownloadLanguagesPreference.kt
Labels: 🛬 needs landing, approved

#5409 Bug 1877588 - TranslationsMiddleware Dispatcher Scope Issue
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
Labels: 🛬 needs landing, approved

#5443 Bug 1874522 - Catch OOM, set desired size and disable coil-kt cache in SVG decoder
  android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/SvgIconDecoder.kt
  android-components/components/support/images/src/main/java/mozilla/components/support/images/decoder/AndroidImageDecoder.kt
Labels: 🛬 needs landing, approved

#5397 Bug 1877885 - Update Detekt to version 1.23.5
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5406 Bug 1812843 - Maintain aspect ratio when resizing a bitmap for the 'add' button in CustomTabsToolbarFeature
  android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
  android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ext/Bitmap.kt
  android-components/components/support/utils/src/test/java/mozilla/components/support/utils/ext/BitmapTest.kt
Labels: 🛬 needs landing, approved

#5430 Bug 1877123 - Fix number localization in `TabCounter` and `TabTools`
  fenix/app/src/main/java/org/mozilla/fenix/compose/TabCounter.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ext/Int.kt
  fenix/app/src/main/java/org/mozilla/fenix/debugsettings/tabs/TabTools.kt
  fenix/app/src/test/java/org/mozilla/fenix/compose/ext/IntTest.kt
Labels: 🛬 needs landing, approved

#5462 Bug 1567912 - Add signing-bundle as a dependency for notify-promote
  taskcluster/ci/release-notify-promote/kind.yml
Labels: 🛬 needs landing, approved

#5187 Bug 1874943 - Add a tab counter UI element
  fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BottomToolbarContainerView.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/NavigationBar.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Labels: 🕵️‍♀️ needs review

#5284 Bug 1861459 - Update AppState.mode based on selected tab changes
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TabListActionTest.kt
  android-components/components/feature/session/src/main/java/mozilla/components/feature/session/middleware/LastAccessMiddleware.kt
  android-components/components/feature/session/src/test/java/mozilla/components/feature/session/middleware/LastAccessMiddlewareTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/bindings/BrowserStoreBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt
  fenix/app/src/test/java/org/mozilla/fenix/bindings/BrowserStoreBindingTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/appstate/AppStoreReducerTest.kt
Labels: 🛬 needs landing, approved

#5403 Bug 1877939 - Remove redundant assertion functions from EnhancedTrackingProtectionRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
Labels: 🛬 needs landing, approved

#5404 Bug 1877945 - Remove redundant assertion functions from FindInPageRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/FindInPageRobot.kt
Labels: 🛬 needs landing, approved

#5444 Bug 1878524 - Return immediately when tab found
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
Labels: 🛬 needs landing, approved

#5461 Bug 1876806 - Do not remove downloaded files in private tabs after deleting browsing data
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
Labels: 🛬 needs landing, approved

#5473 Bug 1870312 - Avoid overlap between add-on item and install button
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt
  android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
Labels: 🛬 needs landing, approved

#5389 Bug 1877205 - Translations Fetch Supported Languages Refactor
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationOperation.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
Labels: 🛬 needs landing, approved

#5463 Bug 1876823 - Add action to fetch list of sites that should not be tr…
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationError.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationOperation.kt
Labels: 🛬 needs landing, approved

#5474 Bug 1878866 - Add missing pairs of logs to AddToHomeScreenRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/AddToHomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#5476 Bug 1878878 - Add missing pairs of logs to BookmarksRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Labels: 🛬 needs landing, approved

#5492 Bug 1879027 - Add missing pairs of logs to CollectionRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
Labels: 🛬 needs landing, approved

#5493 Bug 1879072 - Add test logs to HomeScreenRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#5299 Bug 1878868 - Create TestSetup helper: Test classes A-C
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerBlockerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
Labels: 🛬 needs landing, approved

#5483 Bug 1848139 - Remove unnecessary glean-gradle-plugin step from crash and nimbus builds
  android-components/components/lib/crash/README.md
  android-components/components/lib/crash/build.gradle
  android-components/components/lib/crash/docs/metrics.md
  android-components/components/service/nimbus/build.gradle
  android-components/components/service/nimbus/docs/metrics.md
Labels: 🛬 needs landing, approved

#5484 Bug 1860778 - Remove increased fab shadow while it's pressed
  fenix/app/src/main/java/org/mozilla/fenix/compose/button/FloatingActionButton.kt
Labels: 🛬 needs landing, approved

#5497 Revert "Bug 1878868 - Create TestSetup helper: Test classes A-C"
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerBlockerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
Labels: 🛬 needs landing, approved, urgent

#5432 Bug 1832357 - Fallback to loading new window requests in custom tab
  android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabWindowFeature.kt
  android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabWindowFeatureTest.kt
  android-components/samples/browser/src/main/java/org/mozilla/samples/browser/ExternalAppBrowserFragment.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
Labels: 🛬 needs landing, approved

#5400 Bug 1877889 - Update Sentry to version 7.3.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5511 Bug 1870326 - Do not allow the add-on name to be focused (browser action)
  android-components/components/browser/menu/src/main/res/layout/mozac_browser_menu_web_extension.xml
Labels: 🛬 needs landing, approved

#5514 Bug 1870345 - Mark headings as such in the list of add-ons
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
Labels: 🛬 needs landing, approved

#5512 Bug 1870329 - Add add-on name to the content description of each install button
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml
  android-components/components/feature/addons/src/main/res/values/strings.xml
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
Labels: 🛬 needs landing, approved

#5526 Bug 1878365 - Translations AC Page Settings Bug
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#5491 Bug 1874662 - Fix flaky closeAllTabsTest UI tests
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Labels: 🛬 needs landing, approved

#5516 Bug 1879288 - Add missing pairs of logs to BrowserRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Labels: 🛬 needs landing, approved

#5518 Bug 1870362 - Add underline to each link in the add-on details view
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegate.kt
  fenix/app/src/test/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegateTest.kt
Labels: 🛬 needs landing, approved

#5517 Bug 1878868 - Create TestSetup helper: Test classes A-C (fix for legacy APIs)
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerBlockerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
Labels: 🛬 needs landing, approved

#5520 Bug 1879308 - Add missing pairs of logs to ComposeTabDrawerRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Labels: 🛬 needs landing, approved

#5500 Bug 1870319 - Announce title in add-ons sub-menu
  android-components/components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt
  android-components/components/browser/menu/src/main/res/values/strings.xml
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5521 Bug 1879339 - Add missing pairs of logs to ComposeTopSitesRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTopSitesRobot.kt
Labels: 🛬 needs landing, approved

#5534 Bug 1879509 - Add missing pairs of logs to DownloadRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt
Labels: 🛬 needs landing, approved

#5539 Bug 1879583 - Change the default for pull-to-refresh to enabled
  fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Labels: 🛬 needs landing, approved

#5542 Revert "Bug 1833666 - Update original RFC guidelines with stakeholders"
  docs/rfcs/0001-rfc-process.md
Labels: 🛬 needs landing, approved

#5475 Bug 1876140 - Translations UI Dropdown Checkmark
  fenix/app/src/main/java/org/mozilla/fenix/compose/Menu.kt
Labels: 🛬 needs landing, approved

#5532 Bug 1816066 - Fix verifyMultipleLoginsSelectionsTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
Labels: 🛬 needs landing, approved

#5210 Bug 1875379 - Update Private notification description text
  focus-android/app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
  focus-android/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5537 Bug 1879539 - Add test logs to LibrarySubMenusMultipleSelectionToolbarRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/LibrarySubMenusMultipleSelectionToolbarRobot.kt
Labels: 🛬 needs landing, approved

#5391 Bug 1868469 - Update the url immediately for existing engineSession
  android-components/components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt
  android-components/components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt
  docs/changelog.md
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
Labels: 🛬 needs landing, approved

#5414 Revert "Bug 1875294 - Record breadbcrumbs before crashing with Unsats…
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Labels: 🛬 needs landing, approved

#5574 Bug 1873486 - Update mockk to version 1.13.9
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5566 Bug 1879886 - Add test logs to NavigationToolbarRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Labels: 🛬 needs landing, approved

#5576 Bug 1879944 - Update Compose Compiler to version 1.5.9
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5582 Bug 1880047 - Add missing pairs of logs to NotificationRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Labels: 🛬 needs landing, approved

#5583 Bug 1880064 - Add logs to ReaderViewRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/PwaRobot.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ReaderViewRobot.kt
Labels: 🛬 needs landing, approved

#5570 Bug 1851947 - Update Google Accompanist to version 0.32.0
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5587 Bug 1880150 - Do not wait for attribution before dismissing splash screen
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Labels: 🛬 needs landing, approved

#5588 Bug 1880152 - Update Firebase Cloud Messaging to version 23.4.1
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5498 Bug 1877203 - Update Translations Page Settings
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationPageSettingOperation.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationPageSettings.kt
Labels: 🛬 needs landing, approved

#5593 Bug 1880221 - Add logs to RecentlyClosedTabsRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/RecentlyClosedTabsRobot.kt
Labels: 🛬 needs landing, approved

#5399 Bug 1877888 - Update Adjust to version 4.38.1
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
  focus-android/plugins/focusdependencies/src/main/java/FocusDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5398 Bug 1877887 - Update ZXing to version 3.5.3
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5595 Bug 1870701 - Replace straight quotes with curly quotes in RC onboarding
  fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5603 Bug 1880328 - Fix state checking issues
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/AppServicesStateMachineChecker.kt
Labels: 🛬 needs landing, approved

#5544 Bug 1877278 - AC Translations Check for if the Engine is Supported
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsBrowserState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationError.kt
  fenix/app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#5596 Bug 1807268 - Fix verifySavedAddressCanBeEditedTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Labels: 🛬 needs landing, approved

#5616 Bug 1880466 - Add logs to SettingsSubMenuAccessibilityRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAccessibilityRobot.kt
Labels: 🛬 needs landing, approved

#5618 Bug 1880494 - Update JUnit5 to version 5.10.2
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
  focus-android/plugins/focusdependencies/src/main/java/FocusDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5281 Bug 1876385 - Update AndroidX Benchmark to version 1.2.3
  fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5597 Bug 1815651 - Fix verifyAutofillToggleTest UI test
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
Labels: 🛬 needs landing, approved

#5635 Bug 1880759 - Update SnakeYAML to version 2.2
  shared-settings.gradle
Labels: 🛬 needs landing, approved

#5654 Bug 1880476 — Remove redundant nimbusFeature in NimbusMessagingStorage
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
Labels: 🛬 needs landing, approved

#5621 Bug 1880511 - Update Kotlin Coroutines to version 1.8.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5662 Bug 1875379 - Fix ambiguity in string description.
  focus-android/app/src/main/res/values/strings.xml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#5630 Bug 1880640 - Add pairs of logs to SettingsSubMenuAutofillRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Labels: 🛬 needs landing, approved

#5642 Bug 1880808 - Add logs to SearchRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Labels: 🛬 needs landing, approved

#5643 Bug 1880812 - Add logs to SettingsSubMenuCustomizeRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuCustomizeRobot.kt
Labels: 🛬 needs landing, approved

#5646 Bug 1880821 - Add test logs to SettingsSubMenuDataCollectionRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDataCollectionRobot.kt
Labels: 🛬 needs landing, approved

#5648 Bug 1880827 - Add test logs to SettingsSubMenuDeleteBrowsingDataOnQuitRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataOnQuitRobot.kt
Labels: 🛬 needs landing, approved

#5664 Bug 1880999 - Start the Nightly 125 development cycle
  docs/changelog.md
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5652 Bug 1880476 — Remove redundant caching and destroy jexl helper after use
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt
Labels: 🛬 needs landing, approved

#5649 Bug 1880829 - Restrict suggest to show a single open tab suggestion for identical tabs
  android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt
  android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
Labels: 🛬 needs landing, approved

#5656 Bug 1880912 - Remove TestRail Script and Dependencies from ui-test-apk TC Task
  taskcluster/ci/ui-test-apk/kind.yml
Labels: 🛬 needs landing, approved, urgent

#5665 Bug 1881010 - Add logs to SettingsSubMenuDeleteBrowsingDataRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataRobot.kt
Labels: 🛬 needs landing, approved

#5673 Bug 1881066 - Unschedule screenshots cron
  .cron.yml
Labels: 🛬 needs landing, approved

#5674 Bug 1880666 - Update Android command line tools to version 12.0
  taskcluster/ci/fetch/kind.yml
Labels: 🛬 needs landing, approved

#5677 Bug 1880912 - Remove TestRail Script and Dependencies from ui-test-apk TC Task
  taskcluster/scripts/lib/testrail_utils.py
Labels: 🛬 needs landing, approved

#5671 Bug 1880476 — Rename gleanplumb to nimbus messaging
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/onboarding/view/OnboardingMapperTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/DefaultMessageController.kt
Labels: 🛬 needs landing, approved

#5653 Bug 1880476 — Reduce visibility of fields in Message
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/Message.kt
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingController.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingControllerTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/MessageCardViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/MessageNotificationWorker.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/state/MessagingMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/messaging/state/MessagingMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#5651 Bug 1880476 — Validate control messages without message content
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
Labels: 🛬 needs landing, approved

#5617 Bug 1879507 - [Onboarding] Show Default prompt when default-browser card disabled
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt
Labels: 🛬 needs landing, approved

#5694 Bug 1881250 - Add logs to SettingsSubMenuLanguageRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLanguageRobot.kt
Labels: 🛬 needs landing, approved

#5693 Bug 1880476 — NimbusMessaging: Move filtering to getNextMessage
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
Labels: 🛬 needs landing, approved

#5691 Bug 1880476 — Move nimbus from components.analytics to components.nimbus
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/Experimentation.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingMessageTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingTriggerTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Analytics.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/NimbusComponents.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/MessageNotificationWorker.kt
  fenix/app/src/main/java/org/mozilla/fenix/nimbus/NimbusBranchesFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/nimbus/NimbusExperimentsFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/studies/StudiesFragment.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/BackgroundServicesTest.kt
Labels: 🛬 needs landing, approved

#5667 Bug 1880077 - Switch to using Compose BOM instead of individual versioning
  android-components/components/browser/state/build.gradle
  android-components/components/compose/awesomebar/build.gradle
  android-components/components/compose/cfr/build.gradle
  android-components/components/feature/autofill/build.gradle
  android-components/components/lib/state/build.gradle
  android-components/components/support/images/build.gradle
  android-components/components/ui/colors/build.gradle
  android-components/components/ui/tabcounter/build.gradle
  android-components/components/ui/widgets/build.gradle
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
  android-components/samples/browser/build.gradle
  android-components/samples/compose-browser/build.gradle
  fenix/app/build.gradle
  focus-android/app/build.gradle
Labels: 🛬 needs landing, approved

#5668 Bug 1881016 - Added experimental onboarding strings for Nimbus treatments C & D
  fenix/app/src/main/res/values/strings.xml
Labels: 🛬 needs landing, approved

#5689 Bug 1881238 - Add logs to SettingsSubMenuHttpsOnlyModeRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHttpsOnlyModeRobot.kt
Labels: 🛬 needs landing, approved

#5698 Bug 1877881 - Prevent crash when downloadStatus is not present.
  android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
  android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/manager/FetchDownloadManagerTest.kt
Labels: 🛬 needs landing, approved

#5699 Bug 1880476 — Promote messaging controller to nimbus.messaging
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingController.kt
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingControllerInterface.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingControllerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingMessageTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
  fenix/app/src/main/java/org/mozilla/fenix/components/NimbusComponents.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/DefaultMessageController.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/FenixNimbusMessagingController.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/MessageNotificationWorker.kt
  fenix/app/src/main/java/org/mozilla/fenix/messaging/state/MessagingMiddleware.kt
  fenix/app/src/test/java/org/mozilla/fenix/messaging/DefaultMessageControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/messaging/state/MessagingMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#5700 Bug 1881336 - Remove telemetry probes expiring in v125
  fenix/app/metrics.yaml
  fenix/app/src/main/java/org/mozilla/fenix/components/metrics/fonts/FontEnumerationWorker.kt
Labels: 🛬 needs landing, approved

#5701 Bug 1881338 - Update telemetry expiry handling in release checklist
  docs/contribute/release_checklist.md
Labels: 🛬 needs landing, approved

#5702 Bug 1881326 - Update Sentry to version 7.4.0
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#5721 Bug 1881561 - Update serp telemetry json dump
  android-components/components/feature/search/src/main/assets/search/search_telemetry_v2.json
Labels: 🛬 needs landing, approved

#5696 Bug 1881296 - Add item to release checklist to add search-telemtry-v2…
  docs/contribute/release_checklist.md
Labels: 🛬 needs landing, approved

#5722 Bug 1880476 — Refactor onMessageDisplayed bookkeeping
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingController.kt
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingControllerTest.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/messaging/DefaultMessageControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/messaging/state/MessagingMiddlewareTest.kt
Labels: 🛬 needs landing, approved

#5715 Bug 1881489 - Add logs to SettingsSubMenuLoginsAndPasswordOptionsToSaveRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordOptionsToSaveRobot.kt
Labels: 🛬 needs landing, approved

#5716 Bug 1881491 - Add logs to SettingsSubMenuLoginsAndPasswordRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordRobot.kt
Labels: 🛬 needs landing, approved

#5734 Bug 1881733 - Add logs to SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
Labels: 🛬 needs landing, approved

#5703 Bug 1881347 - Update Compose Compiler to version 1.5.10
  android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Labels: 🛬 needs landing, approved

#2435 Bug 1804636 - Allow search terms to be refined in content
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt
  android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt
  android-components/components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
  android-components/config/detekt-baseline.xml
  android-components/plugins/dependencies/src/main/java/Gecko.kt
  docs/changelog.md
Labels: 🛬 needs landing, approved

#5752 Bug 1881976 - Replace web-de with bild-de pageload test.
  taskcluster/ci/browsertime/kind.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#5733 Bug 1881703 - Notify app store of mode change from TabsTray
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt
  fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
Labels: 🛬 needs landing, approved

#5536 Bug 1879525 - Create TestSetup helper: Compose Test classes
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeBookmarksTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeCollectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHistoryTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeMediaNotificationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeNavigationToolbarTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTopSitesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
Labels: 🛬 needs landing, approved

#5738 Bug 1878921 - Translations CouldNotLoadLanguagesError UI "Try Again"
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
Labels: 🛬 needs landing, approved

#5600 Bug 1875817 - Translations Integration Toolbar Showing
  android-components/components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt
  android-components/components/concept/toolbar/src/test/java/mozilla/components/concept/toolbar/ActionButtonTest.kt
  docs/changelog.md
  fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/TranslationsBinding.kt
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/browser/TranslationsBindingTest.kt
Labels: 🛬 needs landing, approved

#5758 Bug 1882035 - Disable non-sponsored suggestions UI tests in FirefoxSu…
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/FirefoxSuggestTest.kt
Labels: 🛬 needs landing, approved

#5459 Bug 1878386 - Rewrite ui-test.sh into Python
  taskcluster/ci/startup-test/kind.yml
  taskcluster/ci/ui-test-apk/kind.yml
  taskcluster/scripts/tests/test-lab.py
Labels: 🛬 needs landing, approved

#5723 Bug 1880483 — Add inverse triggers to messaging component
  android-components/components/service/nimbus/messaging.fml.yaml
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/Message.kt
  android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingControllerTest.kt
  android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
  fenix/app/messaging-evergreen-messages.fml.yaml
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingHomescreenTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/messaging/DefaultMessageControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/messaging/state/MessagingMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/messaging/state/MessagingReducerTest.kt
Labels: 🛬 needs landing, approved

#5727 Bug 1881604 - Helper for Transforming BCP 47 code to defined Language
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/state/TranslationSupportTest.kt
  android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationSupport.kt
Labels: 🛬 needs landing, approved

#5614 Bug 1870339 - Make list of add-ons more accessible
  android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt
  android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
Labels: 🛬 needs landing, approved

#5586 Bug 1880075 - Use single name field for addresses
  android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/Address.kt
  android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt
  android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/prompt/PromptRequestTest.kt
  android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt
  android-components/components/concept/storage/src/test/java/mozilla/components/concept/storage/AddressTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/address/AddressAdapterTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/address/AddressPickerTest.kt
  android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/address/AddressSelectBarTest.kt
  android-components/components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/Types.kt
  android-components/components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/AutofillCreditCardsAddressesStorageTest.kt
  android-components/plugins/dependencies/src/main/java/ApplicationServices.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/address/ext/Address.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/address/view/AddressEditorView.kt
  fenix/app/src/main/java/org/mozilla/fenix/settings/address/view/AddressList.kt
  fenix/app/src/main/res/layout/fragment_address_editor.xml
  fenix/app/src/main/res/values/strings.xml
  fenix/app/src/test/java/org/mozilla/fenix/settings/address/AddressEditorViewTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/address/controller/DefaultAddressEditorControllerTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/address/ext/AddressTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/settings/address/interactor/DefaultAddressEditorInteractorTest.kt
Labels: 🛬 needs landing, approved

#5771 Bug 1882170 - Disable Auto-Fill View Tests After Address Fields Were Consolidated
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
Labels: 🛬 needs landing, approved

#5765 Bug 1880284 - Show keyboard after voice input
  fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
Labels: 🛬 needs landing, approved

#5697 Bug 1881294 - Refine `isExpectedTranslate`
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
Labels: 🛬 needs landing, approved

#5764 Bug 1882136 - Fxa state machine checker fix
  android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/AppServicesStateMachineChecker.kt
Labels: 🛬 needs landing, approved

#5585 Bug 1880087 - TestSetup helper: Test classes D-L
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DeepLinkTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadFileTypesTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/FirefoxSuggestTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/GlobalPrivacyControlTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt
Labels: 🛬 needs landing, approved

#5619 Bug 1880497 - Create TestSetup helper: Test classes M-N
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MainMenuTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusEventTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingHomescreenTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingMessageTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingNotificationTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingTriggerTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NoNetworkAccessStartupTests.kt
Labels: 🛬 needs landing, approved

#5780 Bug 1882134 - Use jvmToolchain for setting target JVM version
  android-components/.config.yml
  android-components/build.gradle
  android-components/components/tooling/detekt/build.gradle
  android-components/components/tooling/lint/build.gradle
  fenix/app/build.gradle
  fenix/benchmark/build.gradle
  fenix/build.gradle
  fenix/mozilla-lint-rules/build.gradle
  focus-android/app/build.gradle
  focus-android/build.gradle
  shared-settings.gradle
Labels: 🛬 needs landing, approved

#5785 Bug 1882264 - Add logs to SettingsSubMenuOpenLinksInAppsRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuOpenLinksInAppsRobot.kt
Labels: 🛬 needs landing, approved

#5787 Bug 1882272 - Add logs to SettingsSubMenuPrivateBrowsingRobot
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuPrivateBrowsingRobot.kt
Labels: 🛬 needs landing, approved

#5757 Bug 1879512 - Added experimental onboarding images for Nimbus
  fenix/app/lint-baseline.xml
  fenix/app/src/main/res/drawable/ic_onboarding_key_features.xml
  fenix/app/src/main/res/drawable/ic_onboarding_key_features_icons_only.xml
  fenix/app/src/main/res/raw/keep.xml
Labels: 🛬 needs landing, approved

#5769 Bug 1882162 - remove jQuery slim test asset
  fenix/app/src/androidTest/assets/pages/jquery-3.4.1.slim.min.js
  fenix/app/src/androidTest/assets/pages/refresh.html
Labels: 🛬 needs landing, approved

#5781 Bug 1882213 - Fix address autofill view test over-scrolling
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Labels: 🛬 needs landing, approved

#5672 Bug 1881041 - TestSetup helper: refactor RetryTestRule
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/RetryTestRule.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
  fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt
Labels: 🛬 needs landing, approved

#5577 Bug 1876594 - Refactor ThumbnailStorage to be an implicit dependency
  fenix/app/src/main/java/org/mozilla/fenix/compose/TabThumbnail.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ThumbnailCard.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/ThumbnailImage.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTabViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeGridViewHolder.kt
  fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/compose/ComposeListViewHolder.kt
Labels: 🛬 needs landing, approved

#4126 Bug 1845409 - File RFC 0010 proposing handling navigation through middleware
  docs/rfcs/0010-add-state-based-navigation.md
Labels: 🛬 needs landing, approved

#5768 Bug 1882151 - Always and Never Page Settings Bug
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
Labels: 🛬 needs landing, approved

#5791 Bug 1881128 - Add additional headers for Google requests
  fenix/app/src/main/java/org/mozilla/fenix/components/UrlRequestInterceptor.kt
  fenix/app/src/test/java/org/mozilla/fenix/components/UrlRequestInterceptorTest.kt
Labels: 🛬 needs landing, approved

#5680 Bug 1880490 - Moving Translations `supportedLanguages`
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsBrowserState.kt
  android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsState.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
  android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
  fenix/app/src/main/java/org/mozilla/fenix/browser/TranslationsBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBinding.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogStore.kt
  fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsFlowState.kt
  fenix/app/src/test/java/org/mozilla/fenix/browser/TranslationsBindingTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
  fenix/app/src/test/java/org/mozilla/fenix/translations/TranslationsDialogBindingTest.kt
Labels: 🛬 needs landing, approved
